# Generated by Django 3.1.7 on 2021-03-31 01:24

from django.db import migrations, models
import django.db.models.deletion
import futurecosts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reo', '0103_auto_20210223_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureCostsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('base_year', models.IntegerField()),
                ('future_year1', models.IntegerField(blank=True, null=True)),
                ('future_year2', models.IntegerField(blank=True, null=True)),
                ('future_year3', models.IntegerField(blank=True, null=True)),
                ('future_year4', models.IntegerField(blank=True, null=True)),
                ('future_year5', models.IntegerField(blank=True, null=True)),
                ('future_year6', models.IntegerField(blank=True, null=True)),
                ('future_year7', models.IntegerField(blank=True, null=True)),
                ('future_year8', models.IntegerField(blank=True, null=True)),
                ('future_year9', models.IntegerField(blank=True, null=True)),
                ('future_year10', models.IntegerField(blank=True, null=True)),
                ('base_scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario1', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario10', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario10', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario2', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario3', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario4', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario4', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario5', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario5', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario6', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario6', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario7', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario7', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario8', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario8', to='reo.scenariomodel', to_field='run_uuid')),
                ('future_scenario9', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_scenario9', to='reo.scenariomodel', to_field='run_uuid')),
            ],
            bases=(futurecosts.models.BaseModel, models.Model),
        ),
    ]
