# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='spreadsheet_created',
            field=models.DateTimeField(null=True),
        ),
    ]
