from tastypie import fields
import os

def inputs(filter='',full_list=False,just_required=False):


    output = {
      'user_id': {'req': False, 'type': str, 'null': False, 'pct': False, "needed_for": [], 'default':None
                  ,"description": "User ID", "units":None,
                  "tool_tip":"Unique REopt user id."},

      # Required
      'analysis_period': {'req': False, 'type': int, 'null': True, 'pct': False, "needed_for": ['economics'],
                          'default': 25, 'min': 0, 'max': None,
                          "description": "Period of Analysis", "units": 'years',
                          "tool_tip":'The financial life of the project in years.'},
      
      'land_area': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': None,
                        "description": "Land Area avaialble for PV panel siting", "units": 'acres',
                        "tool_tip":'The land area available on-site, in acres, for solar panels. Include fields, parking lots and vacant lots.'},
       
      'roof_area': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': None,
                        "description": "Area of Roof Available for PV siting", "units": 'square feet',
                        "tool_tip":'The roof area available on-site, in square feet, for solar panels. For more accurate results, exclude areas known to be consistently shaded.'},

      'latitude': {'req': True, 'type': float, 'null': False, 'pct': False,
                   "needed_for": ['economics', 'gis', 'loads', 'pvwatts'],
                   "description": "Site Latitude", "units": 'degrees',
                   "tool_tip":'Approximate latitude of the site in degrees.'},

      'longitude': {'req': True, 'type': float, 'null': False, 'pct': False,
                    "needed_for": ['economics', 'gis', 'loads', 'pvwatts'],
                    "description": "Site Longitude", "units": 'degrees',
                    "tool_tip":'Approximate longitude of the site in degrees.'},

      'pv_cost': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['economics'], 'min': 0,
                  'max': None, 'default': 2160,
                  "description": "Nominal PV Cost", "units": 'dollars per kilowatt',
                  "tool_tip":'Approximate latitude of the site in degrees.',
                  "tool_tip":'Fully burdened cost of PV system in dollars per kilowatt. A baseline estimate may assume $2,160/kW.'},

      'pv_om': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['economics'], 'min': 0,
                'max': None, 'default': 20,
                "description": "Nominal PV Operation and Maintenance Cost", "units": 'dollars per kilowatt-year',
                "tool_tip":'Estimated annual PV operation and maintenance costs per installed kilowatt. O&M includes asset cleanings, administration costs and replacing broken components.'},

      'batt_cost_kw': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['economics'], 'min': 0,
                       'max': None, 'default': 1600,
                       "description": "Nominal Battery Inverter Cost", "units": 'dollars per kilowatt',
                       "tool_tip":'Fully burdened cost of Battery Storage system in dollars per kilowatt.'},

      'batt_cost_kwh': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['economics'], 'min': 0,
                        'max': None, 'default': 500,
                        "description": "Nominal Battery Cost", "units": 'dollars per kilowatt-hour',
                        "tool_tip":'Fully burdened cost of Battery Storage system in dollars per kilowatt-hour.'},

      'batt_kw_max': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': None,
                        "description": "Maximum Allowable Battery Power Size", "units": 'kilowatt',
                        "tool_tip":'Restriction on the Maximum Power of the Battery System in kilowatts.'},

      'batt_kw_min': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': 0,
                        "description": "Minimum Allowable Battery Power Size", "units": 'kilowatt',
                        "tool_tip":'Restriction on the Minimum Power of the Battery System in kilowatts.'},

      'batt_kwh_max': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': None,
                        "description": "Maximum Battery Energy Capacity", "units": 'kilowatt-hours',
                        "tool_tip":'Restriction on the Maximum Energy Storage of the Battery System in kilowatt-hours.'},

      'batt_kwh_min': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': 0,
                        "description": "Minimum Battery Energy Capacity", "units": 'kilowatt-hours',
                        "tool_tip":'Restriction on the Minimum Energy Storage of the Battery System in kilowatt-hours.'},

      'batt_time_min': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': 0,
                        "description": "Minimum Battery Energy Capacity", "units": 'hours',
                        "tool_tip":'Restriction on the Minimum Hours of Energy Storage of the Battery System.'},

      'batt_time_max': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': 0,
                        "description": "Minimum Battery Energy Capacity", "units": 'hours',
                        "tool_tip":'Restriction on the Maximum Hours of Energy Storage of the Battery System.'},

      'batt_replacement_cost_escalation': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": [], 'min': None,
                        'max': None, 'default': None,
                        "description": "Rate at which to escalate the future price of a battery", "units": 'percent',
                        "tool_tip":'The rate at which to discount the cost of replacing a Battery System components in the future.'},

      'interconnection_limit': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': None,
                        "description": "Limit on Power flowing from System to the Grid", "units": 'kilowatt',
                        "tool_tip":'The maximum power that can be transmitted to the grid at any one time, in kilowatts. Interconnection limits are typically established by state policy.'},

      'net_metering_limit': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': None,
                        "description": "System Size Limitation for Net Metering Purposes", "units": 'kilowatt',
                        "tool_tip":'The maximum power that can be sold back to utilities at any one time, in kilowatts. These values are typically established by utilities.'},

      'wholesale_rate': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": [], 'min': 0,
                        'max': None, 'default': 0.12,
                        "description": "Assumed price of electricity on the wholesale market", "units": 'dollars per kilowatt-hour',
                        "tool_tip":'The estimated price of electricity on the wholesale market in dollars per kilowatt.'},

      'pv_kw_max': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['economics'], 'min': 0,
                        'max': None, 'default': None,
                        "description": "Nominal Battery Cost", "units": 'dollars per kilowatt-hour',
                        "tool_tip":'Restriction on the Maximum Power of the PV System in kilowatt-hours.'},

      'pv_kw_min': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['economics'], 'min': 0,
                        'max': None, 'default': 0,
                        "description": "Nominal Battery Cost", "units": 'dollars per kilowatt-hour', 
                        "tool_tip":'Restriction on the Maximum Power of the PV System in kilowatt-hours.'},

      'owner_discount_rate': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['economics'],
                              'min': 0, 'max': 1, 'default': 0.08,
                              "description": "Owner Discount Rate", "units": 'decimal percent',
                              "tool_tip":'The rate at which the system owner discounts future savings and earnings from the installed system.'},

      'offtaker_discount_rate': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['economics'],
                                 'min': 0, 'max': 1, 'default': 0.08,
                                 "description": "Offtaker Discount Rate", "units": 'decimal percent',
                                 "tool_tip":'The rate at which the offtaker discounts future the value of excess energy electricity supplied by the installed system.'},

      'blended_utility_rate': {'req': True, 'depends_on': ['demand_charge'], 'swap_for': ['urdb_rate'], 'type': list,
                               'null': False, 'pct': False, "needed_for": ['economics', 'utility'],
                                "description": "Blended Utility Rate", "units": '$/kWh',
                                "tool_tip":'The average of on-peak, off-peak and any shoulder time of use pricing schedules for each month. These vary according to utility.'},


      'demand_charge': {'req': True, 'depends_on': ['blended_utility_rate'], 'swap_for': ['urdb_rate'], 'type': list,
                        'null': False, 'pct': False, "needed_for": ['economics', 'utility'],
                        "description": "Demand Charge", "units": '$/kW',
                        "tool_tip":'The price per kilowatt of demand charges established by your local utility.'},

      'urdb_rate': {'req': True, 'swap_for': ['demand_charge', 'blended_utility_rate'], 'type': dict, 'null': False,
                    'pct': False, "needed_for": ['economics'],
                    "tool_tip":'A JSON of the utility rate schedule as provided by the Utility Rate Database (en.openei.org/wiki/Utility_Rate_Database).'},

      # Not Required
      'load_profile_name': {'req': True,'swap_for':['load_8760_kw'], 'type': str, 'null': True, 'pct': False, "needed_for": ['economics'],
                       "description": "Generic Load Profile Type",
                       'restrict_to': default_load_profiles()+[None],
                       "tool_tip":'A typcial load for a conventional building type can be scaled to your annual load size.'},


      'load_size': {'req': True, 'swap_for':['load_8760_kw'],'type': float, 'null': True, 'pct': False, "needed_for": ['economics'], 'min': 0,
                    'max': None,
                    "description": "Annual Load Size", "units": 'kWh',
                    "tool_tip":'The annual load at the proposed site.'},

      'load_year': {'req': True, 'swap_for':['load_profile_name','load_size'], 'type': float, 'null': True, 'pct': False,
                      "needed_for": ['economics'], 'min': 0, 'max': None, 'default': 2018,
                      "description": "Year of input load profile", "units": '',
                      "tool_tip": 'The year of the input load profile'},

      'load_8760_kw': {'req': True, 'swap_for':['load_profile_name','load_size'], 'type': list, 'null': True, 'pct': False, "needed_for": ['economics'],
                       "description": "Hourly Power Demand", "units": 'kW',
                       "tool_tip":'The annual hourly power demand at the proposed site.'},

      'load_monthly_kwh': {'req': False, 'type': list, 'null': True, 'pct': False, "needed_for": ['economics'],
                           "description": "Monthly Energy Demand", "units": 'kWh',
                           "tool_tip":'The annual monthly energy demand at the proposed site.'},

      'utility_name': {'req': False, 'type': str, 'null': True, 'pct': False, "needed_for": ['economics', 'utility'],
                       "description": "Utility Name",
                       "tool_tip":'The name of the utility that currently serves the proposed site.'},

      'rate_name': {'req': False, 'type': str, 'null': True, 'pct': False, "needed_for": ['economics', 'utility'],
                    "description": "Rate Name",
                    "tool_tip":'The name of the utility rate structure that currently applies to the proposed site.'},

      'rate_degradation': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['economics'],
                           'min': 0, 'max': 1, 'default': 0.005,
                           "description": "Annual Degredation for Solar PV Panels", "units": 'decimal percent',
                           "tool_tip":'The percent at which the PV performance is expected to degrage annually.'},

      'rate_inflation': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['economics'], 'min': 0,
                         'max': 1, 'default': 0.02,
                         "description": "Annual Inflation Rate", "units": 'decimal percent per year',
                         "tool_tip":'The expected annual rate of inflation over the financial life of the system.'},

      'rate_escalation': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['economics'],
                          'min': -1, 'max': 1, 'default': 0.0039,
                          "description": "Annual Cost of  Electricity Escalation Rate", "units": 'decimal percent per year',
                          "tool_tip":'The expected annual rate of escalation for the price of electricity provided by the utility over the financial life of the system.'},

      'offtaker_tax_rate': {'req': False, 'type': float, 'null': True, 'pct': False, "needed_for": ['economics'], 'min': 0,
                   'max': 1, 'default': 0.35,
                   "description": "Tax Rate for Electricity Customer", "units": 'decimal percent',
                   "tool_tip":'The percent of income that goes to tax for the offtaker.'},

      'owner_tax_rate': {'req': False, 'type': float, 'null': True, 'pct': False, "needed_for": ['economics'],
                    'min': 0,
                    'max': 1, 'default': 0.35,
                    "description": "Tax Rate for System Developer", "units": 'decimal percent',
                    "tool_tip":'The percent of income that goes to tax for the system owner.'},

      'rate_itc': {'req': False, 'type': float, 'null': True, 'pct': False, "needed_for": ['economics'], 'min': 0,
                   'max': 1, 'default': 0.30,
                   "description": "Investment Tax Credit rate", "units": 'decimal percent',
                   "tool_tip":'The percent of system costs that are subsudized by the current Federal Investment Tax Credit.'},

      'batt_replacement_cost_kw': {'req': False, 'type': float, 'null': False, 'pct': False,
                                   "needed_for": ['economics'], 'min': 0, 'max': None, 'default': 200,
                                   "description": "Battery Inverter Replacement Cost", "units": '$/kW',
                                   "tool_tip":"The expected cost, in today's dollars,  of replacing battery components per installed kilowatt."},

      'batt_replacement_cost_kwh': {'req': False, 'type': float, 'null': False, 'pct': False,
                                    "needed_for": ['economics'], 'min': 0, 'max': None, 'default': 200,
                                    "description": "Battery Replacement Cost", "units": '$/kWh',
                                    "tool_tip":"The expected cost, in today's dollars, of replacing battery components per installed kilowatt-hour."},

      'batt_replacement_year': {'req': False, 'type': int, 'null': False, 'pct': False, "needed_for": ['economics'],
                                'min': 0, 'max': None, 'default': 10,
                                "description": "Battery Replacement Year", "units": 'year',
                                "tool_tip":'The year in which the battery system is expected to need to be replaced.'},

      'flag_macrs': {'req': False, 'type': bool, 'null': False, 'pct': False, "needed_for": ['economics'], 'default': 1,
                     'min': 0, 'max': 1,
                     "description": "Use Modified Advanced  Cost Recovery System (MACRS) Deductions", "units": 'boolean',
                     "tool_tip":'Indicates whether the Modified Accelerated Cost Recovery System (MACRS) should be used to depreciate system costs.'},

      'flag_itc': {'req': False, 'type': bool, 'null': False, 'pct': False, "needed_for": ['economics'], 'default': 1,
                   'min': 0, 'max': 1,
                   "description": "Use Investment Tax Credit Deductions", "units": 'boolean',
                   "tool_tip":'Indicates whether the Investment Tax Credit (ITC) should be used to subsidize system costs.'},

      'flag_bonus': {'req': False, 'type': bool, 'null': False, 'pct': False, "needed_for": ['economics'], 'default': 1,
                     'min': 0, 'max': 1,
                     "description": "Use Bonus Deductions", "units": 'boolean',
                     "tool_tip":'Indicates whether a Bonus Fraction should be factored in to system costs.'},

      'flag_replace_batt': {'req': False, 'type': bool, 'null': False, 'pct': False, "needed_for": ['economics'],
                            'default': 1, 'min': 0, 'max': 1,
                            "description": "Use Battery Replacement Scheme", "units": 'boolean',
                            "tool_tip":'Indicates whether a the battery is expected to be replaced over the life of the system.'},

      'macrs_years': {'req': False, 'type': int, 'null': False, 'pct': False, "needed_for": ['economics'], 'default': 5,
                      'min': 5, 'max': 7, 'restrict_to': [5, 7],
                      "description": "MACRS depreciation timeline for Solar and Storage", "units": 'years',
                      "tool_tip":'If MACRS is used, specify the duration over which depreciation will occur.'},

      'macrs_itc_reduction': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['economics'],
                              'default': 0.5, 'min': 0, 'max': 1,
                              "description": "If ITC is taken with MACRS, the depreciable value is reduced by this fraction of the ITC", "units": 'decimal percent',
                              "tool_tip": "If ITC is taken with MACRS, the depreciable value is reduced by this fraction of the ITC"},

      'bonus_fraction': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['economics'],
                         'default': 0.5, 'min': 0, 'max': 1,
                         "description": "This fraction of the depreciable value is taken in year 1 in addition to MACRS",
                         "units": 'decimal percent',
                         "tool_tip": "This fraction of the depreciable value is taken in year 1 in addition to MACRS"},


      'dataset': {'req': False, 'type': str, 'null': False, 'pct': False, "needed_for": ['pvwatts'], 'default': "tmy3",
                  'restrict_to': ['tmy2', 'tmy3', 'intl', 'IN'], "description": "Climate Dataset",
                  "tool_tip": "This solar insolation dataset to use when calling PVWatts"},

      'inv_eff': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['pvwatts'], 'default': 0.96,
                  'min': 0.9, 'max': 0.995, "description": "Inverter Efficiency at Rated Power",
                  "units": "decimal percent",
                  "tool_tip": "The expected inverter efficiency rate."},

      'dc_ac_ratio': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['pvwatts'],
                      'default': 1.1, 'min': 0, 'max': None, "description": "DC to AC ratio",
                      "tool_tip": "The expected DC to AC conversion ratio."},

      'azimuth': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['pvwatts'], 'default': 180,
                  'min': 0, 'max': 360, "description": "Azimuth Angle", "units": "degrees",
                   "tool_tip": "The azimuth of the proposed site."},

      'system_capacity': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['pvwatts'],
                          'default': 1, 'min': 0.05, 'max': 500000, "description": "Nameplate capacity", "units": "kW", 
                          "tool_tip": "The nameplate capacity of the proposed PV system."},

      'array_type': {'req': False, 'type': int, 'null': False, 'pct': False, "needed_for": ['pvwatts'], 'default': 0,
                     'restrict_to': [0, 1, 2, 3, 4], "description": "Fixed or Axis Type",
                     "tool_tip": "The type of arrays for proposed PV system (Fixed - Open Rack, Fixed - Roof Mounted, 1-Axis, 1-Axis Backtracking, 2-Axis)."}, 

      'module_type': {'req': False, 'type': int, 'null': False, 'pct': False, "needed_for": ['pvwatts'], 'default': 0,
                      'restrict_to': [0, 1, 2], "description": "Module Type",
                      "tool_tip": "The type of modules for proposed PV system (Standard, Premium, Thin Film)."},  # standard

      'timeframe': {'req': False, 'type': str, 'null': False, 'pct': False, "needed_for": ['pvwatts'],
                    'default': 'hourly', 'restrict_to': ['hourly', 'monthly'],
                    "description": "Granularity of Output Response",
                    "tool_tip": "The granularity of the solar data used to model PV system performance."},

      'losses': {'req': False, 'type': float, 'null': False, 'pct': True, "needed_for": ['pvwatts'], 'default': 0.14,
                 'min': -0.05, 'max': 0.99, "description": "System Losses type", "units": "decimal percent",
                 "tool_tip": "Expected total system losses."},

      'radius': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['pvwatts'], 'default': 0,
                 'min': 0, 'max': None, "description": "Search Distance to  Nearest Climate Data Station",
                 "units": "miles",
                 "tool_tip": "Search Distance to  Nearest Climate Data Station"},

      'tilt': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['pvwatts'], 'default': None,
               'min': 0, 'max': 90, "description": "Tilt Angle", "units": "degrees",
               "tool_tip": "The tilt of the proposed PV System, commonly matches the latitide for optimal performance."},

      'gcr': {'req': False, 'type': float, 'null': False, 'pct': False, "needed_for": ['pvwatts'], 'default': 0.4,
              'min': 0.01, 'max': 0.99, "description": "Ground  Cover Ratio",
              "tool_tip": "The Ground Cover Ratio of the proposed PV system."},
    }
    if full_list:
        return output

    if filter != '':
        output = {k:v for k, v in output.items() if filter in v['needed_for'] }

    if just_required:
        output = dict((k, v) for k, v in output.items() if v['req'])
    return output

def outputs():
    return {'status': {'type': str, 'null': True,'pct': False,
                    "description": "Problem Status", "units":'none'},

            'lcc': {'type': float, 'null': True,'pct': False,
                    "description": "Lifecycle Cost", "units":'dollars'},

           'npv': {'type': float, 'null': True,'pct': False,
                   "description": "Net Present  Value of System", "units":'dollars'},

           'irr': {'type': float, 'null': True, 'pct': True,
                    "description": "Internal Rate of Return for System", "units": 'percentage'},

           'utility_kwh': {'type': float, 'null': True,'pct': False,
                           "description": "Energy Supplied from the Grid", "units": 'kWh'},

           'pv_kw': {'type': float, 'null': True,'pct': False,
                     "description": "Recommended PV System Size", "units": 'kW'},

           'batt_kw': {'type': float, 'null': True,'pct': False,
                       "description": "Recommended Battery Inverter Size", "units": 'kW'},

           'batt_kwh': {'type': float, 'null': True,'pct': False,
                        "description": "Recommended Battery Size", "units": 'kWh'},

           'year_one_energy_cost': {'type': float, 'null': True, 'pct': False,
                         "description": "Year 1 utility energy charge", "units": '$'},

           'year_one_demand_cost': {'type': float, 'null': True, 'pct': False,
                                       "description": "Year 1 utility demand charge", "units": '$'}
            }

# default load profiles
def default_load_profiles():
    return  ['FastFoodRest', 'FlatLoad', 'FullServiceRest', 'Hospital', 'LargeHotel', 'LargeOffice',
                         'MediumOffice', 'MidriseApartment', 'Outpatient', 'PrimarySchool', 'RetailStore',
                         'SecondarySchool', 'SmallHotel', 'SmallOffice', 'StripMall', 'Supermarket', 'Warehouse']

def default_building():
    return "Hospital"

# default locations
def default_cities():
    return ['Miami', 'Houston', 'Phoenix', 'Atlanta', 'LosAngeles', 'SanFrancisco', 'LasVegas', 'Baltimore',
                'Albuquerque', 'Seattle', 'Chicago', 'Boulder', 'Minneapolis', 'Helena', 'Duluth', 'Fairbanks']

# default latitudes
def default_latitudes():
    return [25.761680, 29.760427, 33.448377, 33.748995, 34.052234, 37.774929, 36.114707, 39.290385,
                     35.085334, 47.606209, 41.878114, 40.014986, 44.977753, 46.588371, 46.786672, 64.837778]

# default longitudes
def default_longitudes():
    return [-80.191790, -95.369803, -112.074037, -84.387982, -118.243685, -122.419416, -115.172850,
                      -76.612189, -106.605553, -122.332071, -87.629798, -105.270546, -93.265011, -112.024505,
                      -92.100485, -147.716389]
def default_blended_rate():
    return [0.05066,0.05066,0.05066,0.05066,0.05066,0.05066,0.05066,0.05066,0.05066,0.05066,0.05066,0.05066]

def default_demand_charge():
    return [10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00]

def default_load_monthly():
    return [100,200,250,300,350,350,400,400,350,250,250,200]

def default_load_hourly():
    return [1,1,1,1,1,1,2,2,3,4,5,6,7,6,5,4,3,3,2,2,1,1,1,1]*365

def default_urdb_rate():
    return {
    "label": "55fc81bf682bea28da64e94a",
    "uri": "http://en.openei.org/apps/USURDB/rate/view/55fc81bf682bea28da64e94a",
    "sector": "Commercial",
    "energyweekendschedule": [
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    ],
    "enddate": 1451520000,
    "flatdemandunit": "kW",
    "supersedes": "53a0b1b65257a3186f04ca17",
    "demandrateunit": "kW",
    "eiaid": 6452,
    "phasewiring": "Single and 3-Phase",
    "demandratestructure": [
      [
        {
          "rate": 0,
          "adj": 2.9
        }
      ],
      [
        {
          "rate": 9.11,
          "adj": 2.9
        }
      ]
    ],
    "peakkwcapacitymin": 500,
    "revisions": [
      1431595766,
      1431596033,
      1449833552
    ],
    "energyratestructure": [
      [
        {
          "rate": 0.03701,
          "adj": 0.00267,
          "unit": "kWh"
        }
      ],
      [
        {
          "rate": 0.06239,
          "adj": 0.00267,
          "unit": "kWh"
        }
      ]
    ],
    "startdate": 1433116800,
    "demandcomments": "Demand adjustment includes conservation, capacity charges.",
    "utility": "Florida Power & Light Co.",
    "fixedmonthlycharge": 59.51,
    "demandweekdayschedule": [
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ]
    ],
    "name": "GLSDT-1 (General Service Large Demand - Time-Of-Use)",
    "source": "https://www.fpl.com/rates/pdf/June2015_Business.pdf   \r\n   https://www.fpl.com/rates/pdf/electric-tariff-section8.pdf",
    "demandweekendschedule": [
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    ],
    "energycomments": "Rate includes Energy base charge and fuel charge || Adjustment includes storm and environmental",
    "approved": True,
    "peakkwcapacitymax": 2000,
    "country": "USA",
    "energyweekdayschedule": [
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ],
      [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        0,
        0
      ]
    ],
    "sourceparent": "http://www.fpl.com/rates/"
  }
