max_big_number = 1e8
max_incentive = 1e10
max_years = 75
macrs_schedules = [0,5,7]
analysis_period = 20
providers = ['federal','state','utility']
default_buildings =  [  'FastFoodRest',
                    'FullServiceRest',
                    'Hospital',
                    'LargeHotel',
                    'LargeOffice',
                    'MediumOffice',
                    'MidriseApartment',
                    'Outpatient',
                    'PrimarySchool',
                    'RetailStore',
                    'SecondarySchool',
                    'SmallHotel',
                    'SmallOffice',
                    'StripMall',
                    'Supermarket',
                    'Warehouse']

def list_of_float(input):
    return ['float'(i) for i in input]

nested_input_definitions = {

    "Scenario": {
                "timeout_seconds":      { 'type': 'float','min': 1, 'max': 295, 'default': 295,
                                           'description':'The number of seconds allowed before the optimization times out' },
                "user_id":              { 'type': 'str',
                                            'description':'Not currently used.' },
                "time_steps_per_hour":  { 'type': 'float', 'min': 1, 'max': 1, 'default': 1,
                                        "description": 'The number of time steps per hour in the REopt simulation'}, #aspirational - we only handle 1 timetep per hour really, this touches all of the code really


                "Site": {
                             "latitude":            { 'type': 'float', 'min':-180, 'max':180, 'required': True,
                                                    "description": 'The approximate latitide of the site in decimal degrees' },
                             "longitude":           { 'type': 'float', 'min':-180, 'max':180, 'required': True,
                                                    "description": 'The approximate longitude of the site in decimal degrees' },
                             "land_acres":          { 'type': 'float', 'min': 0, 'max': 1e6,
                                                    "description": 'Land Area available for PV panel siting' },
                             "roof_squarefeet":     { 'type': 'float', 'min': 0, 'max': 1e9,
                                                    "description": "Area of Roof Available for PV siting" },
                             "outage_start_hour":   { 'type': 'int', 'min': 0, 'max': 8759,
                                                    "description": "Hour of year that grid outage starts. Must be less than outage_end." },
                             "outage_end_hour":     { 'type': 'int', 'min': 0, 'max': 8759,
                                                    "description": "Hour of year that grid outage ends. Must be greater than outage_start." },
                             "critical_load_pct":   { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.5,
                                                    "description": "Critical load factor is used to scale the load during an outage. Value must be between zero and one, inclusive." },

                             "Financial":
                                    {   "om_cost_growth_pct":   { 'type': 'float', 'min': -1, 'max': 1, 'default': 0.025,
                                                                    "description": "Annual O&M Cost Growth Rate" },                      
                                        "escalation_pct":       { 'type': 'float','min': -1, 'max': 1, 'default': 0.026,
                                                                    "description": "Annual Cost of  Electricity Escalation Rate" },
                                        "owner_tax_pct":        { 'type': 'float','min': -1, 'max': 1,
                                                                    "description": "Tax Rate for System Developer"},
                                        "offtaker_tax_pct":     { 'type': 'float','min': -1, 'max': 1, 'default': 0.4,
                                                                    "description": "Tax Rate for Electricity Customer"},
                                        "owner_discount_pct":   { 'type': 'float','min': -1, 'max': 1,
                                                                    "description": "Owner Discount Rate"},
                                        "offtaker_discount_pct":{ 'type': 'float','min': -1, 'max': 1, 'default': 0.081,
                                                                     "description": "Offtaker Discount Rate" },
                                        "analysis_years":       { 'type': 'int','min': 0, 'max': max_years, 'default': analysis_period,
                                                                    "description": "Period for Financial Analysis" }
                                        },

                            "LoadProfile":{
                                            "doe_reference_name":   { 'type': 'str', 'restrict_to':default_buildings,'depends_on':['annual_kwh or monthly_totals_kwh'],
                                                                    "description": "Generic Load Profile Type from DOE <a href='https://energy.gov/eere/buildings/commercial-reference-buildings' target='blank'>Commercial Reference Buildings</a>. Must be accompanied with annual_kwh or monthly_totals_kwh." },
                                            "annual_kwh":           { 'type': 'float', 'min': 0, 'max': 1e12,'replacements':[['loads_kw'],['doe_reference_name','monthly_totals_kwh']],'depends_on':['doe_reference_name'],
                                                                    "description": "Annual Load Size" },
                                            "year":                 { 'type': 'int', 'min': 2017, 'max': 2017+max_years, 'default': 2018,
                                                                    "description":"Year of Custom Load Profile" },
                                            "monthly_totals_kwh":   { 'type': 'list_of_float','replacements':[['loads_kw'],['doe_reference_name','annual_kwh']],'depends_on':['doe_reference_name'],
                                                                    "description":"12 item array of aggregate monthly energy usage" },
                                            "loads_kw":             { 'type': 'list_of_float','replacements':[['doe_reference_name','annual_kwh'],['doe_reference_name','monthly_totals_kwh']],
                                                                    "description":"Hourly energy use over all hours in one year" }
                                        },

                            "ElectricTariff": {
                                                "urdb_utilty_name":                         { 'type': 'str',
                                                                                            "description":"Name of Utility from  <a href='https://openei.org/wiki/Utility_Rate_Database' target='blank'>Utility Rate Database</a>" },
                                                "urdb_rate_name":                           { 'type': 'str',
                                                                                            "description":"Name of Utility Rate from  <a href='https://openei.org/wiki/Utility_Rate_Database' target='blank'>Utility Rate Database</a>" },
                                                "blended_monthly_rates_us_dollars_per_kwh": { 'type': 'list_of_float','replacements':['urdb_response'],
                                                                                            "description": "12 item array of average monthly utility rates per kWh" },
                                                "monthly_demand_charges_us_dollars_per_kw": { 'type': 'list_of_float','replacements':['urdb_response'],
                                                                                            "description": "12 item array of average monthly utility demand charges per kW"},
                                                "net_metering_limit_kw":                    { 'type': 'float','min': 0, 'max': 1e9, 'default':0,
                                                                                            "description": "System size above which net metering is not allowed"},
                                                "interconnection_limit_kw":                 { 'type': 'float','min': 0, 'max': 1e9,'default': max_big_number,
                                                                                            "description": "Limit on power flowing from system to the Grid" },
                                                "wholesale_rate_us_dollars_per_kwh":        { 'type': 'float', 'min': 0, 'default': 0,
                                                                                            "description": "Assumed price of electricity on the wholesale market" },
                                                "urdb_response":                            { 'type': 'dict', 'replacements':[['blended_monthly_rates_us_dollars_per_kwh','monthly_demand_charges_us_dollars_per_kw']],
                                                                                            "description": "Utility Rate Structure from <a href='https://openei.org/services/doc/rest/util_rates/?version=3' target='blank'>Utility Rate Database API</a>" },
                                                "urdb_label":                               { 'type': 'str',
                                                                                            "description": "Label attribute of Utility Rate Structure from <a href='https://openei.org/services/doc/rest/util_rates/?version=3' target='blank'>Utility Rate Database API</a>" }
                                        },

                            "Wind":{
                                                "min_kw":                               {  'type': 'float', 'min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Minimum wind power capacity constraint for optimization."  },
                                                "max_kw":                               { 'type': 'float', 'min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Maximum wind power capacity constraint for optimization. Set to zero to disable Wind. Disabled by default"  },
                                                "installed_cost_us_dollars_per_kw":     { 'type': 'float', 'min': 0, 'max': 1e5, 'default': 2000,
                                                                                            "description":"Total upfront installed costs." },
                                                "om_cost_us_dollars_per_kw":            { 'type': 'float', 'min': 0, 'max': 1e3, 'default': 35,
                                                                                            "description":"Total annual operations and maintenance costs." },
                                                "macrs_option_years":                   { 'type': 'int', 'restrict_to': macrs_schedules, 'default': 5,
                                                                                            "description":"MACRS schedule for financial analysis. Set to zero to disable."},
                                                "macrs_bonus_pct":                      { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.5,
                                                                                            "description":"Percent of upfront project costs to depreciate under MACRS." },
                                                "federal_itc_pct":                      { 'type': 'float','min': 0, 'max': 1, 'default': 0.3,
                                                                                            "description":"Percent of upfront project costs to discount under Federal ITC." },
                                                "state_ibi_pct":                        { 'type': 'float','min': 0, 'max': 1, 'default': 0,
                                                                                            "description":"Percent of upfront project costs to discount under state investment based incentives." },
                                                "state_ibi_max_us_dollars":             { 'type': 'float','min': 0, 'max': 1e10, 'default': max_incentive,
                                                                                            "description":"Maximum rebate allowed under state investment based incentives." },
                                                "utility_ibi_pct":                      { 'type': 'float','min': 0, 'max': 1, 'default': 0,
                                                                                            "description":"Percent of upfront project costs to discount under utility investment based incentives." },
                                                "utility_ibi_max_us_dollars":           { 'type': 'float','min': 0, 'max': 1e10, 'default': max_incentive,
                                                                                             "description":"Maximum rebate allowed under utility investment based incentives." },
                                                "federal_rebate_us_dollars_per_kw":     { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Federal rebates based on installed capacity." },
                                                "state_rebate_us_dollars_per_kw":       { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"State rebates based on installed capacity." },
                                                "state_rebate_max_us_dollars":          { 'type': 'float','min': 0, 'max': 1e10, 'default': max_incentive,
                                                                                            "description":"Maximum rebate allowed under state rebates." },
                                                "utility_rebate_us_dollars_per_kw":     { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Utility rebates based on installed capacity."  },
                                                "utility_rebate_max_us_dollars":        { 'type': 'float','min': 0, 'max': 1e10, 'default': max_incentive,
                                                                                            "description":"Maximum rebate allowed under utility rebates." },
                                                "pbi_us_dollars_per_kwh":               { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Production-based incentive value." },
                                                "pbi_max_us_dollars":                   { 'type': 'float','min': 0, 'max': 1e9, 'default': 1e9,
                                                                                            "description":"Maximum rebate allowed under utility production-based incentives." },
                                                "pbi_years":                            { 'type': 'float','min': 0, 'max': 1e9, 'default': analysis_period,
                                                                                            "description":"Duration of production-based incentives from installation date." },
                                                "pbi_system_max_kw":                    { 'type': 'float','min': 0, 'max': 1e9, 'default': 1e9,
                                                                                            "description":"Maximum system size for which production-based incentives apply."},
                                                },

                            "PV":{
                                                "min_kw":                               {  'type': 'float', 'min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Minimum PV size constraint for optimization."  },
                                                "max_kw":                               { 'type': 'float', 'min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Maximum PV size constraint for optimization. Set to zero to disable PV."  },
                                                "installed_cost_us_dollars_per_kw":     { 'type': 'float', 'min': 0, 'max': 1e5, 'default': 2000,
                                                                                            "description":"Total upfront installed costs." },
                                                "om_cost_us_dollars_per_kw":            { 'type': 'float', 'min': 0, 'max': 1e3, 'default': 35,
                                                                                            "description":"Total annual operations and maintenance costs." },
                                                "macrs_option_years":                   { 'type': 'int', 'restrict_to': macrs_schedules, 'default': 5,
                                                                                            "description":"MACRS schedule for financial analysis. Set to zero to disable."},
                                                "macrs_bonus_pct":                      { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.5,
                                                                                            "description":"Percent of upfront project costs to depreciate under MACRS." },
                                                "federal_itc_pct":                      { 'type': 'float','min': 0, 'max': 1, 'default': 0.3,
                                                                                            "description":"Percent of upfront project costs to discount under Federal ITC." },
                                                "state_ibi_pct":                        { 'type': 'float','min': 0, 'max': 1, 'default': 0,
                                                                                            "description":"Percent of upfront project costs to discount under state investment based incentives." },
                                                "state_ibi_max_us_dollars":             { 'type': 'float','min': 0, 'max': 1e10, 'default': max_incentive,
                                                                                            "description":"Maximum rebate allowed under state investment based incentives." },
                                                "utility_ibi_pct":                      { 'type': 'float','min': 0, 'max': 1, 'default': 0,
                                                                                            "description":"Percent of upfront project costs to discount under utility investment based incentives." },
                                                "utility_ibi_max_us_dollars":           { 'type': 'float','min': 0, 'max': 1e10, 'default': max_incentive,
                                                                                             "description":"Maximum rebate allowed under utility investment based incentives." },
                                                "federal_rebate_us_dollars_per_kw":     { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Federal rebates based on installed capacity." },
                                                "state_rebate_us_dollars_per_kw":       { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"State rebates based on installed capacity." },
                                                "state_rebate_max_us_dollars":          { 'type': 'float','min': 0, 'max': 1e10, 'default': max_incentive,
                                                                                            "description":"Maximum rebate allowed under state rebates." },
                                                "utility_rebate_us_dollars_per_kw":     { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Utility rebates based on installed capacity."  },
                                                "utility_rebate_max_us_dollars":        { 'type': 'float','min': 0, 'max': 1e10, 'default': max_incentive,
                                                                                            "description":"Maximum rebate allowed under utility rebates." },
                                                "pbi_us_dollars_per_kwh":               { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Production-based incentive value." },
                                                "pbi_max_us_dollars":                   { 'type': 'float','min': 0, 'max': 1e9, 'default': 1e9,
                                                                                            "description":"Maximum rebate allowed under utility production-based incentives." },
                                                "pbi_years":                            { 'type': 'float','min': 0, 'max': 1e9, 'default': analysis_period,
                                                                                            "description":"Duration of production-based incentives from installation date." },
                                                "pbi_system_max_kw":                    { 'type': 'float','min': 0, 'max': 1e9, 'default': 1e9,
                                                                                            "description":"Maximum system size for which production-based incentives apply."},
                                                "degradation_pct":                      { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.005,
                                                                                            "description":"Annual rate of system degradation in energy production."},
                                                "azimuth":                              { 'type': 'float', 'min': 0, 'max': 360, 'default': 180,
                                                                                            "description":"PV Watts azimuth angle" },
                                                "losses":                               { 'type': 'float','min': 0, 'max': 0.99, 'default': 0.14,
                                                                                           "description":"PV Watts system losses angle" },
                                                "array_type":                           { 'type': 'int', 'restrict_to': [0, 1, 2, 3, 4], 'default': 0,
                                                                                            "description":"PV Watts array type (0: Fixed-Open Rack; 1: Fixed-Roof Mounted; 2: 1-Axis; 3 : 1-Axis Backtracking; 4: 2-Axis)" },
                                                "module_type":                          { 'type': 'int', 'restrict_to': [0, 1, 2], 'default': 0,
                                                                                            "description":"PV Watts module type (0: Standard; 1: Premium; 2: Thin Film)" },
                                                "gcr":                                  { 'type': 'float', 'min': 0.01, 'max': 0.99, 'default': 0.4,
                                                                                            "description":"PV Watts ground cover ratio" },
                                                "dc_ac_ratio":                          { 'type': 'float', 'min': 0, 'max': 2, 'default': 1.1,
                                                                                            "description":"PV Watts DC-AC ratio"},
                                                "inv_eff":                              { 'type': 'float' ,'min': 0.9, 'max': 0.995, 'default': 0.96,
                                                                                             "description":"PV Watts inverter efficiency"},
                                                "radius":                               { 'type': 'float' , 'min': 0, 'default': 0,
                                                                                             "description":"PV Watts radius to use when searching for the closest climate data station. Use zero to use the closest station regardless of the distance." },
                                                "tilt":                                 { 'type': 'float', 'min': 0, 'max': 90,
                                                                                            "description":"PV Watts system tilt." } 
                                            },


                            "Storage":{         "min_kw":                               {  'type': 'float', 'min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Minimum Battery power size constraint for optimization."  },
                                                "max_kw":                               { 'type': 'float', 'min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Maximum Battery power size constraint for optimization. Set to zero to disable Storage."  },
                                                "min_kwh":                              { 'type': 'float','min': 0, 'default': 0,
                                                                                            "description":"Minimum Battery energy storage capacity constraint for optimization." },
                                                "max_kwh":                              { 'type': 'float','min': 0, 'default': 1000000,
                                                                                            "description":"Maximum Battery energy storage capacity constraint for optimization. Set to zero to disable Storage" },
                                                "internal_efficiency_pct":              { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.975,
                                                                                            "description":"Battery inherent efficiency independent of inverter and rectifier." },
                                                "inverter_efficiency_pct":              { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.96,
                                                                                            "description":"Battery inverter efficiency." },
                                                "rectifier_efficiency_pct":             { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.96,
                                                                                            "description":"Battery rectifier efficiency." },
                                                "soc_min_pct":                          { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.2,
                                                                                            "description":"Minimum allowable battery state of charge." },
                                                "soc_init_pct":                         { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.5,
                                                                                            "description":"Battery state of charge at first hour of optimization." },
                                                "canGridCharge":                        { 'type': 'bool', 'default': False,
                                                                                            "description":"Flag to set whether the battery can be charged from the grid, or just onsite generation." },
                                                "installed_cost_us_dollars_per_kw":     { 'type': 'float','min': 0, 'max': 1e4, 'default': 1000,
                                                                                            "description":"Total upfront inverter costs." },
                                                "installed_cost_us_dollars_per_kwh":    { 'type': 'float','min': 0, 'max': 1e4, 'default': 500,
                                                                                            "description":"Total upfront battery costs." },
                                                "replace_cost_us_dollars_per_kw":       { 'type': 'float', 'min': 0, 'max': 1e4, 'default': 460,
                                                                                            "description":"Inverter replacement cost at time of replacement year." },
                                                "replace_cost_us_dollars_per_kwh":      { 'type': 'float','min': 0, 'max': 1e4, 'default': 230,
                                                                                            "description":"Battery replacement cost at time of replacement year." },
                                                "inverter_replacement_year":            { 'type': 'float', 'min': 0, 'max': max_years, 'default': 10,
                                                                                             "description":"Number of years from start of optimization to replace inverter."  },
                                                "battery_replacement_year":             { 'type': 'float', 'min': 0, 'max': max_years, 'default': 10,
                                                                                            "description":"Number of years from start of optimization to replace battery."  },
                                                "macrs_option_years":                   { 'type': 'int', 'restrict_to': macrs_schedules, 'default': 5,
                                                                                            "description":"MACRS schedule for financial analysis. Set to zero to disable."},
                                                "macrs_bonus_pct":                      { 'type': 'float', 'min': 0, 'max': 1, 'default': 0.5,
                                                                                            "description":"Percent of upfront project costs to depreciate under MACRS." },
                                                "total_itc_pct":                        { 'type': 'float','min': 0, 'max': 1, 'default': 0.3,
                                                                                            "description":"Total percent of installed costs allowed to be discounted through investment based incentives." },
                                                "total_rebate_us_dollars_per_kw":       { 'type': 'float','min': 0, 'max': 1e9, 'default': 0,
                                                                                            "description":"Maximum allowed value from all investment incentives." },

                                        },

                }
    }
}

def flat_to_nested(i):

        return {
            "Scenario": {

                "timeout_seconds": i.get("timeout"),
                "user_id": i.get("user_id"),
                "time_steps_per_hour": i.get("time_steps_per_hour"),

                "Site": {
                    "latitude": i.get("latitude"),
                    "longitude": i.get("longitude"),
                    "land_acres": i.get("land_area"),
                    "roof_squarefeet": i.get("roof_area"),
                    "outage_start_hour": i.get("outage_start"),
                    "outage_end_hour": i.get("outage_end"),
                    "critical_load_pct": i.get("crit_load_factor"),

                    "LoadProfile":
                        {
                            "doe_reference_name": i.get("load_profile_name"),
                            "annual_kwh": i.get("load_size"),
                            "year": i.get("load_year"),
                            "monthly_totals_kwh": i.get("load_monthly_kwh"),
                            "loads_kw": i.get("load_8760_kw"),
                        },

                    "Financial":
                        {
                            "om_cost_growth_pct": i.get("om_cost_growth_rate"),
                            "escalation_pct": i.get("rate_escalation"),
                            "owner_tax_pct": i.get("owner_tax_rate"),
                            "offtaker_tax_pct": i.get("offtaker_tax_rate"),
                            "owner_discount_pct": i.get("owner_discount_rate"),
                            "offtaker_discount_pct": i.get("offtaker_discount_rate"),
                            "analysis_period_years": i.get("analysis_period"),
                        },

                    "ElectricTariff":
                        {
                            "urdb_utilty_name": i.get("utility_name"),
                            "urdb_rate_name": i.get("rate_name"),
                            "urdb_response": i.get("urdb_rate"),
                            "blended_monthly_rates_us_dollars_per_kwh": i.get("blended_utility_rate"),
                            "monthly_demand_charges_us_dollars_per_kw": i.get("demand_charge"),
                            "net_metering_limit_kw": i.get("net_metering_limit"),
                            "wholesale_rate_us_dollars_per_kwh": i.get("wholesale_rate"),
                            "interconnection_limit_kw": i.get("interconnection_limit"),
                        },


                    "PV":
                        {
                            "min_kw": i.get("pv_kw_min"),
                            "max_kw": i.get("pv_kw_max"),
                            "installed_cost_us_dollars_per_kw": i.get("pv_cost"),
                            "om_cost_us_dollars_per_kw": i.get("pv_om"),
                            "degradation_pct": i.get("pv_degradation_rate"),
                            "azimuth": i.get("azimuth"),
                            "losses": i.get("losses"),
                            "array_type": i.get("array_type"),
                            "module_type": i.get("module_type"),
                            "gcr": i.get("gcr"),
                            "dc_ac_ratio": i.get("dc_ac_ratio"),
                            "inv_eff": i.get("inv_eff"),
                            "radius": i.get("radius"),
                            "tilt": i.get("tilt"),
                            "macrs_option_years": i.get("pv_macrs_schedule"),
                            "macrs_bonus_pct": i.get("pv_macrs_bonus_fraction"),
                            "federal_itc_pct":i.get("pv_itc_federal"),
                            "state_ibi_pct": i.get("pv_itc_state"),
                            "state_ibi_max_us_dollars": i.get("pv_ibi_state_max"),
                            "utility_ibi_pct": i.get("pv_ibi_utility"),
                            "utility_ibi_max_us_dollars": i.get("pv_ibi_utility_max"),
                            "federal_rebate_us_dollars_per_kw": i.get("pv_rebate_federal"),
                            "state_rebate_us_dollars_per_kw": i.get("pv_rebate_state"),
                            "state_rebate_max_us_dollars": i.get("pv_rebate_state_max"),
                            "utility_rebate_us_dollars_per_kw": i.get("pv_rebate_utility"),
                            "utility_rebate_max_us_dollars":i.get("pv_rebate_utility_max"),
                            "pbi_us_dollars_per_kwh": i.get("pv_pbi"),
                            "pbi_max_us_dollars": i.get("pv_pbi_max"),
                            "pbi_years": i.get("pv_pbi_years"),
                            "pbi_system_max_kw": i.get("pv_pbi_system_max"),
                        },

                    "Wind":
                        {
                            "min_kw": i.get("wind_kw_min"),
                            "max_kw": i.get("wind_kw_max"),
                            "installed_cost_us_dollars_per_kw": i.get("wind_cost"),
                            "om_cost_us_dollars_per_kw": i.get("wind_om"),
                            "degradation_pct": i.get("wind_degradation_rate"),
                            "macrs_option_years": i.get("wind_macrs_schedule"),
                            "macrs_bonus_pct": i.get("wind_macrs_bonus_fraction"),
                            "federal_itc_pct": i.get("wind_itc_federal"),
                            "state_ibi_pct": i.get("wind_ibi_state"),
                            "state_ibi_max_us_dollars": i.get("wind_ibi_state_max"),
                            "utility_ibi_pct": i.get("wind_ibi_utility"),
                            "utility_ibi_max_us_dollars": i.get("wind_ibi_utility_max"),
                            "federal_rebate_us_dollars_per_kw": i.get("wind_rebate_federal"),
                            "state_rebate_us_dollars_per_kw": i.get("wind_rebate_state"),
                            "state_rebate_max_us_dollars": i.get("wind_rebate_state_max"),
                            "utility_rebate_us_dollars_per_kw": i.get("wind_rebate_utility"),
                            "utility_rebate_max_us_dollars": i.get("wind_rebate_utility_max"),
                            "pbi_us_dollars_per_kwh": i.get("wind_pbi"),
                            "pbi_max_us_dollars": i.get("wind_pbi_max"),
                            "pbi_years": i.get("wind_pbi_years"),
                            "pbi_system_max_kw": i.get("wind_pbi_system_max"),
                        },

                    "Storage":
                        {
                            "min_kw": i.get("batt_kw_min"),
                            "max_kw": i.get("batt_kw_max"),
                            "min_kwh": i.get("batt_kwh_min"),
                            "max_kwh": i.get("batt_kwh_max"),
                            "internal_efficiency_pct": i.get("batt_efficiency"),
                            "inverter_efficiency_pct": i.get("batt_inverter_efficiency"),
                            "rectifier_efficiency_pct": i.get("batt_rectifier_efficiency"),
                            "soc_min_pct": i.get("batt_soc_min"),
                            "soc_init_pct": i.get("batt_soc_init"),
                            "canGridCharge": i.get("batt_can_gridcharge"),
                            "installed_cost_us_dollars_per_kw": i.get("batt_cost_kw"),
                            "installed_cost_us_dollars_per_kwh": i.get("batt_cost_kwh"),
                            "replace_cost_us_dollars_per_kw": i.get("batt_replacement_cost_kw"),
                            "replace_cost_us_dollars_per_kwh": i.get("batt_replacement_cost_kwh"),
                            "inverter_replacement_year": i.get("batt_replacement_year_kw"),
                            "battery_replacement_year": i.get("batt_replacement_year_kwh"),
                            "macrs_option_years": i.get("batt_macrs_schedule"),
                            "macrs_bonus_pct": i.get("batt_macrs_bonus_fraction"),
                            "total_itc_pct":  i.get("batt_itc_total"),
                            "total_rebate_us_dollars_per_kw": i.get("batt_rebate_total"),
                        }
                    },
                }
            }
