version: "2.1"

services:

  redis:
    image: redis
    command: redis-server
    expose:
      - 6379

  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=reopt
      - POSTGRES_PASSWORD=reopt
      - POSTGRES_DB=reopt
    expose:
      - 5432

  celery:
    build:
      context: .
    image: base-api-image
    command:  >
      "celery -A reopt_api worker -l info"
    environment:
      - APP_ENV=local
      - SQL_HOST=db
      - SQL_PORT=5432
      - REDIS_HOST=redis
      - SOLVER=xpress
    volumes:
      - .:/opt/reopt
    depends_on:
      - db
      - redis
      - julia

  django:
    image: base-api-image
    command:  >
      "python manage.py migrate
      && /opt/reopt/bin/wait-for-it.bash -t 0 julia:8081 -- python manage.py runserver 0.0.0.0:8000"
    environment:
      - APP_ENV=local
      - SQL_HOST=db
      - SQL_PORT=5432
      - REDIS_HOST=redis
      - SOLVER=xpress
    depends_on:
      - db
      - redis
      - julia
      - celery
    ports:
      - 8000:8000
    volumes:
      - .:/opt/reopt

  licenseserver:
    container_name: xpress_license_server
    build:
      context: julia_src/xpress/licenseserver
    mac_address: c4:b3:01:d3:d5:eb
    command: xpserver
    expose:
      - 27100
  
  julia:
    container_name: julia_api
    build:
      context: julia_src/
      args:
        - XPRESS_LICENSE_HOST=xpress_license_server
    command: julia --project=/opt/julia_src http.jl
    ports:
      - "8081:8081"
    depends_on: 
      - licenseserver
    volumes:
      - ./julia_src:/opt/julia_src

volumes:
  pgdata:
