# *********************************************************************************
# REopt, Copyright (c) 2019-2020, Alliance for Sustainable Energy, LLC.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this list
# of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice, this
# list of conditions and the following disclaimer in the documentation and/or other
# materials provided with the distribution.
#
# Neither the name of the copyright holder nor the names of its contributors may be
# used to endorse or promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
# *********************************************************************************
import json
import os
import copy
import time
import numpy as np
import pandas as pd
from tastypie.test import ResourceTestCaseMixin
from unittest import TestCase, skip  # have to use unittest.TestCase to get tests to store to database, django.test.TestCase flushes db
from reo.models import ModelManager
from ghpghx.models import ModelManager as gModelManager
from reo.utilities import MMBTU_TO_KWH, TONHOUR_TO_KWHT


class GHPTest(ResourceTestCaseMixin, TestCase):
    REopt_tol = 1e-2

    def setUp(self):
        super(GHPTest, self).setUp()
        self.loads_view = '/v1/simulated_load/'
        self.ghpghx_base = '/v1/ghpghx/'
        self.reopt_base = '/v1/job/'
        self.test_ghpghx_post = os.path.join('ghpghx', 'tests', 'posts', 'test_ghpghx_POST.json')
        self.test_reopt_post = os.path.join('reo', 'tests', 'posts', 'test_ghp_POST.json')

    def get_loads_response(self, params_dict):
        return self.api_client.get(self.loads_view, data=params_dict)

    def get_ghpghx_response(self, data):
        return self.api_client.post(self.ghpghx_base, format='json', data=data)

    def get_reopt_response(self, data):
        return self.api_client.post(self.reopt_base, format='json', data=data)

    @skip("Skip 2-endpoint GHP test")
    def test_ghp(self):
        """
        GHP Testing
        """

        # Call to GHPGHX app to run GHPGHX model and return the "ghpghx_response" as input to REopt
        #   this mimicks the process the webtool (and API users) would call GHPGHX then REopt
        nested_data = json.load(open(self.test_reopt_post, 'rb'))
        ghpghx_post = json.load(open(self.test_ghpghx_post, 'rb'))
        # Get load data from /simulated_load endpoint using the self.test_reopt_post location and building type
        # Lat/long assumed to be generated by the webtool based on "city, state" location
        latitude = nested_data["Scenario"]["Site"]["latitude"]
        longitude = nested_data["Scenario"]["Site"]["longitude"]
        ghpghx_post["latitude"] = latitude
        ghpghx_post["longitude"] = longitude
        doe_reference_name = nested_data["Scenario"]["Site"]["LoadProfileBoilerFuel"]["doe_reference_name"]
        heating_params = {"latitude": latitude,
                            "longitude": longitude,
                            "doe_reference_name": doe_reference_name,
                            "load_type": "heating"}
        cooling_params = copy.deepcopy(heating_params)
        cooling_params["load_type"] = "cooling"
        
        heating_load_resp = self.get_loads_response(params_dict=heating_params)  # This is FUEL-based
        heating_load_dict = json.loads(heating_load_resp.content)
        # Only need boiler_efficiency if the user inputs this, otherwise uses default 0.8
        ghpghx_post["existing_boiler_efficiency"] = nested_data["Scenario"]["Site"]["Boiler"]["boiler_efficiency"]
        ghpghx_post["heating_fuel_load_mmbtu_per_hr"] = heating_load_dict["loads_mmbtu"]
        cooling_load_resp = self.get_loads_response(params_dict=cooling_params)
        cooling_load_dict = json.loads(cooling_load_resp.content)
        ghpghx_post["cooling_thermal_load_ton"] = cooling_load_dict["loads_ton"]

        # Heat pump performance maps
        hp_cop_filepath = os.path.join('ghpghx', 'tests', 'posts', "heatpump_cop_map.csv" )
        heatpump_copmap_df = pd.read_csv(hp_cop_filepath)
        heatpump_copmap_list_of_dict = heatpump_copmap_df.to_dict('records')
        ghpghx_post["cop_map_eft_heating_cooling"] = heatpump_copmap_list_of_dict        

        # TODO Call /ghpghx enpoint and pass ghpghx_response to REopt
        ghpghx_post_resp = self.get_ghpghx_response(data=ghpghx_post)
        self.assertHttpCreated(ghpghx_post_resp)
        ghpghx_post_resp_dict = json.loads(ghpghx_post_resp.content)
        ghp_uuid = ghpghx_post_resp_dict.get('ghp_uuid')
        ghpghx_results_url = "/v1/ghpghx/"+ghp_uuid+"/results/"
        ghpghx_results_resp = self.api_client.get(ghpghx_results_url)  # same as doing gMakeResponse(ghp_uuid)
        ghpghx_results_resp_dict = json.loads(ghpghx_results_resp.content)
        nested_data["Scenario"]["Site"]["GHP"]["ghpghx_response"] = []
        nested_data["Scenario"]["Site"]["GHP"]["ghpghx_response"].append(ghpghx_results_resp_dict)

        # Call API, get results in "d" dictionary
        nested_data["Scenario"]["timeout_seconds"] = 420  # Overwriting
        nested_data["Scenario"]["optimality_tolerance_techs"] = 0.01  # Overwriting
        nested_data["Scenario"]["optimality_tolerance_bau"] = 0.001                                                                    
        
        time.sleep(10)
        # Call REopt
        resp = self.get_reopt_response(data=nested_data)
        self.assertHttpCreated(resp)
        r = json.loads(resp.content)
        run_uuid = r.get('run_uuid')
        d = ModelManager.make_response(run_uuid=run_uuid)

        ghp_uuid = d["outputs"]["Scenario"]["Site"]["GHP"]["ghp_chosen_uuid"]
        print("GHP uuid chosen = ", ghp_uuid)

        #TODO index into the ghp_response with ghp_uuid to get GHP results
        # Could add actual index to outputs to index on list_of_dict instead, but that would be redundant
        # could instead get ghp_uuid after getting index of list_of_dict, but maybe we could instead do a 
        # ModelManager call in process_results to assign the chosen ghp_response
