# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0006_auto_20170530_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resiliencecase',
            name='init_soc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='resiliencecase',
            name='load',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='resiliencecase',
            name='prod_factor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
    ]
