# Generated by Django 4.0.1 on 2022-04-19 00:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0003_electricstorageinputs_electricstorageoutputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricstorageoutputs',
            name='initial_capital_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricstorageoutputs',
            name='maintenance_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricstorageoutputs',
            name='state_of_health',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, size=None),
        ),
    ]
