# Generated by Django 4.0.6 on 2022-11-01 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0011_chpoutputs_chpinputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpinputs',
            name='size_class',
            field=models.IntegerField(blank=True, default=1, help_text='CHP size class. Must be a strictly positive integer value', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
