# Generated by Django 4.0.6 on 2022-12-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0011_alter_existingboilerinputs_fuel_cost_per_mmbtu'),
        ('reoptjl', '0014_rename_thermal_to_tes_series_mmbtu_per_hour_existingboileroutputs_year_one_fuel_consumption_series_m'),
    ]

    operations = [
    ]
