# Generated by Django 4.0.4 on 2022-12-19 23:11

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0015_merge_20221213_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatorinputs',
            name='fuel_intercept_gal_per_hr',
        ),
        migrations.RemoveField(
            model_name='generatorinputs',
            name='fuel_slope_gal_per_kwh',
        ),
        migrations.AddField(
            model_name='generatorinputs',
            name='electric_efficiency_full_load',
            field=models.FloatField(blank=True, default=0.34, help_text='Electric efficiency of the generator running at full load.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='generatorinputs',
            name='electric_efficiency_half_load',
            field=models.FloatField(blank=True, help_text='Electric efficiency of the generator running at half load. Defaults to electric_efficiency_full_load.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='pvoutputs',
            name='production_factor_series',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='windoutputs',
            name='production_factor_series',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, size=None),
        ),
    ]
