# Generated by Django 4.0.4 on 2023-01-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0016_coldthermalstorageinputs_coldthermalstorageoutputs_and_more'),
        ('reoptjl', '0016_reoptjlmessageoutputs_and_more'),
    ]

    operations = [
    ]
