# Generated by Django 4.0.7 on 2023-01-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0016_remove_generatorinputs_fuel_intercept_gal_per_hr_and_more'),
        ('reoptjl', '0017_merge_20230102_1621'),
    ]

    operations = [
    ]
