# Generated by Django 4.0.7 on 2023-01-05 23:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0019_rename_production_curtailed_series_kw_pvoutputs_electric_curtailed_series_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpoutputs',
            name='thermal_production_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
