# Generated by Django 4.0.7 on 2023-01-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0017_domestichotwaterloadinputs_addressable_load_fraction_and_more'),
        ('reoptjl', '0020_chpoutputs_thermal_production_series_mmbtu_per_hour'),
    ]

    operations = [
    ]
