# Generated by Django 4.0.7 on 2023-02-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0022_ghpinputs_ghpoutputs'),
        ('reoptjl', '0024_alter_electrictariffinputs_blended_annual_demand_rate'),
    ]

    operations = [
    ]
