# Generated by Django 4.0.4 on 2023-03-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0023_alter_generatorinputs_fuel_avail_gal'),
        ('reoptjl', '0025_merge_20230202_1907'),
    ]

    operations = [
    ]
