# Generated by Django 4.0.7 on 2023-03-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0026_alter_chpinputs_federal_itc_fraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reoptjlmessageoutputs',
            name='has_stacktrace',
            field=models.BooleanField(blank=True, default=False, help_text='REopt.jl can return a handled error with corrective instructions or an unhandled error with a stacktrace of what went wrong for further insepction.This field is True if the error message has a stacktrace, False otherwise. Defaults to False.'),
        ),
    ]
