# Generated by Django 4.0.7 on 2023-03-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0027_rename_breakeven_cost_of_emissions_reduction_per_tonnes_co2_financialoutputs_breakeven_cost_of_emiss'),
        ('reoptjl', '0027_reoptjlmessageoutputs_has_stacktrace'),
    ]

    operations = [
    ]
