# Generated by Django 4.0.7 on 2023-03-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0029_alter_chpinputs_size_class'),
        ('reoptjl', '0029_merge_20230316_1432'),
    ]

    operations = [
    ]
