# Generated by Django 4.0.4 on 2023-03-20 22:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0030_merge_20230317_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outageoutputs',
            old_name='unserved_load_series',
            new_name='unserved_load_series_kw',
        ),
        migrations.RemoveField(
            model_name='outageoutputs',
            name='generator_fuel_used_per_outage',
        ),
        migrations.RemoveField(
            model_name='outageoutputs',
            name='unserved_load_per_outage',
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='generator_curtailed_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of generator power curtailed in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='generator_fuel_used_per_outage_gal',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, help_text='Generator fuel used in each outage modeled. Outage duration changes along the first dimension and outage start time changes along the second dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='generator_microgrid_size_kw',
            field=models.FloatField(blank=True, help_text='Optimal generator capacity included in the microgrid.', null=True),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='generator_microgrid_upgrade_cost',
            field=models.FloatField(blank=True, help_text='Capital cost of including the generator system in the microgrid.', null=True),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='generator_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of generator power used to meet load in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='generator_to_storage_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of generator power sent to the battery in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='pv_curtailed_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of PV power curtailed in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='pv_microgrid_size_kw',
            field=models.FloatField(blank=True, help_text='Optimal PV capacity included in the microgrid.', null=True),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='pv_microgrid_upgrade_cost',
            field=models.FloatField(blank=True, help_text='Capital cost of including the PV system in the microgrid.', null=True),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='pv_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of PV power used to meet load in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='pv_to_storage_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of PV power sent to the battery in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='storage_discharge_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of storage power discharged in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='storage_microgrid_upgrade_cost',
            field=models.FloatField(blank=True, help_text='Capital cost of including the electric storage system in the microgrid.', null=True),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='unserved_load_per_outage_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, help_text='The total unserved load for each outage start time and duration. Outage duration changes along the first dimension and outage start time changes along the second dimension.', size=None),
        ),
        migrations.AlterField(
            model_name='reoptjlmessageoutputs',
            name='has_stacktrace',
            field=models.BooleanField(blank=True, default=False, help_text='REopt.jl can return a handled error with corrective instructions or an unhandled error with a stacktrace of what went wrong for further insepction.This field is True if the error message has a stacktrace, otherwise False.'),
        ),
    ]
