# Generated by Django 4.0.7 on 2023-03-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0025_merge_20230210_1734'),
        ('reoptjl', '0030_merge_20230317_1434'),
    ]

    operations = [
    ]
