# Generated by Django 4.0.7 on 2023-03-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0032_alter_reoptjlmessageoutputs_has_stacktrace'),
        ('reoptjl', '0032_outageoutputs_chp_curtailed_series_kw_and_more'),
    ]

    operations = [
    ]
