# Generated by Django 4.0.7 on 2023-04-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0033_absorptionchillerinputs_absorptionchilleroutputs'),
        ('reoptjl', '0034_alter_financialinputs_value_of_lost_load_per_kwh_and_more'),
    ]

    operations = [
    ]
