# Generated by Django 4.0.7 on 2023-04-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0034_alter_windinputs_production_factor_series'),
        ('reoptjl', '0035_merge_20230406_1415'),
    ]

    operations = [
    ]
