# Generated by Django 4.0.7 on 2023-04-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0035_merge_20230401_2138'),
        ('reoptjl', '0035_merge_20230406_1415'),
    ]

    operations = [
    ]
