# Generated by Django 4.0.7 on 2023-06-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0035_boilerinputs_boileroutputs_steamturbineinputs_and_more'),
        ('reoptjl', '0036_merge_20230424_1645'),
    ]

    operations = [
    ]
