# Generated by Django 4.0.7 on 2023-10-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0031_merge_20230321_2118'),
        ('reoptjl', '0037_alter_generatorinputs_installed_cost_per_kw'),
        ('reoptjl', '0037_merge_20230505_1941'),
    ]

    operations = [
    ]
