# Generated by Django 4.0.7 on 2023-06-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0037_merge_20230605_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingboilerinputs',
            name='can_supply_steam_turbine',
            field=models.BooleanField(blank=True, default=False, help_text='If the boiler can supply steam to the steam turbine for electric production', null=True),
        ),
    ]
