# Generated by Django 4.0.7 on 2023-08-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0031_merge_20230321_2118'),
        ('reoptjl', '0037_alter_generatorinputs_installed_cost_per_kw'),
    ]

    operations = [
    ]
