# Generated by Django 4.0.7 on 2023-08-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0037_merge_20230604_1502'),
        ('reoptjl', '0038_alter_generatorinputs_installed_cost_per_kw'),
    ]

    operations = [
    ]
