# Generated by Django 4.0.7 on 2023-08-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0038_alter_generatorinputs_installed_cost_per_kw'),
        ('reoptjl', '0039_financialinputs_boiler_fuel_escalation_rate_fraction_and_more'),
    ]

    operations = [
    ]
