# Generated by Django 4.0.7 on 2023-08-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0037_merge_20230505_1941'),
        ('reoptjl', '0039_merge_20230807_1639'),
    ]

    operations = [
    ]
