# Generated by Django 4.0.7 on 2023-09-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0040_boilerinputs_boileroutputs_steamturbineinputs_and_more'),
        ('reoptjl', '0040_merge_20230815_2047'),
    ]

    operations = [
    ]
