# Generated by Django 4.0.7 on 2023-09-20 21:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0042_alter_boilerinputs_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outageoutputs',
            name='critical_loads_per_outage_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='The critical load in each outage time step for each outage start time and duration. Outage duration changes along the first dimension, outage start time step along the second, and time step in outage along the third.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='soc_series_fraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of storage state of charge (SOC) in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='wind_curtailed_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of Wind power curtailed in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='wind_microgrid_size_kw',
            field=models.FloatField(blank=True, help_text='Optimal Wind capacity included in the microgrid.', null=True),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='wind_microgrid_upgrade_cost',
            field=models.FloatField(blank=True, help_text='Capital cost of including the Wind system in the microgrid.', null=True),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='wind_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of Wind power used to meet load in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
        migrations.AddField(
            model_name='outageoutputs',
            name='wind_to_storage_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, size=None), blank=True, default=list, help_text='Array of Wind power sent to the battery in every outage modeled. Outage duration changes along the first dimension, outage start time changes along the second dimension, and hour within outage changes along the third dimension.', size=None),
        ),
    ]
