# Generated by Django 4.0.4 on 2023-09-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0042_alter_boilerinputs_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outageoutputs',
            name='electric_storage_microgrid_upgraded',
            field=models.BooleanField(blank=True, help_text='True/False for if ElectricStorage is included in the microgrid.', null=True),
        ),
    ]
