# Generated by Django 4.0.7 on 2023-10-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0042_alter_boilerinputs_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimeta',
            name='portfolio_uuid',
            field=models.TextField(blank=True, default='', help_text='The unique ID of a portfolio (set of associated runs) created by the REopt Webtool. Note that this ID can be shared by several REopt API Scenarios and one user can have one-to-many portfolio_uuid tied to them.'),
        ),
    ]
