# Generated by Django 4.0.7 on 2024-03-05 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0042_settings_solver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricutilityinputs',
            name='emissions_factor_CO2_decrease_fraction',
            field=models.FloatField(blank=True, help_text='Not applied with use of Cambium data for climate emissions. Annual percent decrease in the total annual CO2 emissions rate of the grid. A negative value indicates an annual increase.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
