# Generated by Django 4.0.7 on 2024-03-12 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0043_alter_electricutilityinputs_emissions_factor_co2_decrease_fraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricutilityinputs',
            name='emissions_factor_NOx_decrease_fraction',
            field=models.FloatField(blank=True, help_text='Annual percent decrease in the total annual NOx marginal emissions rate of the grid. A negative value indicates an annual increase.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='electricutilityinputs',
            name='emissions_factor_PM25_decrease_fraction',
            field=models.FloatField(blank=True, help_text='Annual percent decrease in the total annual PM2.5 marginal emissions rate of the grid. A negative value indicates an annual increase.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='electricutilityinputs',
            name='emissions_factor_SO2_decrease_fraction',
            field=models.FloatField(blank=True, help_text='Annual percent decrease in the total annual SO2 marginal emissions rate of the grid. A negative value indicates an annual increase.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
