# Generated by Django 4.0.7 on 2023-09-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0043_outageoutputs_critical_loads_per_outage_series_kw_and_more'),
        ('reoptjl', '0043_outageoutputs_electric_storage_microgrid_upgraded'),
    ]

    operations = [
    ]
