# Generated by Django 4.0.7 on 2023-09-24 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0043_ghpinputs_aux_cooler_installed_cost_per_ton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpinputs',
            name='avoided_capex_by_ghp_present_value',
            field=models.FloatField(blank=True, default=0.0, help_text='....', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000000.0)]),
        ),
    ]
