# Generated by Django 4.0.7 on 2023-09-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0044_alter_ghpinputs_avoided_capex_by_ghp_present_value'),
        ('reoptjl', '0044_merge_20230925_2105'),
    ]

    operations = [
    ]
