# Generated by Django 4.0.7 on 2023-10-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0046_ghpinputs_aux_cooler_installed_cost_per_ton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingboileroutputs',
            name='annual_thermal_production_mmbtu_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='existingboileroutputs',
            name='year_one_fuel_cost_before_tax_bau',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
