# Generated by Django 4.0.7 on 2023-10-16 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0048_existingboileroutputs_annual_fuel_consumption_mmbtu_bau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpinputs',
            name='size_class',
            field=models.IntegerField(blank=True, help_text='CHP size class. Must be an integer value between 0 and 7', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
