# Generated by Django 4.0.7 on 2023-11-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0049_alter_chpinputs_size_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimeta',
            name='api_key',
            field=models.TextField(blank=True, default='', help_text='NREL Developer API key of the user'),
        ),
    ]
