# Generated by Django 4.0.7 on 2023-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0050_apimeta_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_MG_upgrade_and_fuel_cost_bau',
            field=models.FloatField(blank=True, help_text='BAU Component of lifecycle costs (LCC). This is the cost to upgrade generation and storage technologies to be included in microgridplus present value of microgrid fuel costs.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_chp_standby_cost_after_tax_bau',
            field=models.FloatField(blank=True, help_text='BAU Component of lifecycle costs (LCC). This value is the present value of all CHP standby charges, after tax.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_elecbill_after_tax_bau',
            field=models.FloatField(blank=True, help_text='BAU Component of lifecycle costs (LCC). This value is the present value of all electric utility charges, after tax.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_outage_cost_bau',
            field=models.FloatField(blank=True, help_text='BAU Component of lifecycle costs (LCC). Expected outage cost.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_production_incentive_after_tax_bau',
            field=models.FloatField(blank=True, help_text='BAU Component of lifecycle costs (LCC). This value is the present value of all production-based incentives, after tax.', null=True),
        ),
    ]
