# Generated by Django 4.0.7 on 2024-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0051_financialoutputs_lifecycle_mg_upgrade_and_fuel_cost_bau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='solver_name',
            field=models.TextField(blank=True, choices=[('HiGHS', 'Highs'), ('Cbc', 'Cbc'), ('SCIP', 'Scip'), ('Xpress', 'Xpress')], default='Xpress', help_text='Solver used for REopt.jl. Options include HiGHS, Cbc, SCIP, and Xpress'),
        ),
    ]
