# Generated by Django 4.0.7 on 2024-04-04 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0055_alter_settings_optimality_tolerance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricloadinputs',
            name='annual_kwh',
            field=models.FloatField(blank=True, help_text="Annual site energy consumption from electricity, in kWh, used to scale simulated default building load profile for the site's climate zone", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000000)]),
        ),
        migrations.AlterField(
            model_name='steamturbineinputs',
            name='size_class',
            field=models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three')], help_text='Steam turbine size class for using appropriate default inputs', null=True),
        ),
    ]
