# Generated by Django 4.0.7 on 2024-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0056_alter_electricloadinputs_annual_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricstorageinputs',
            name='soc_min_applies_during_outages',
            field=models.BooleanField(blank=True, default=False, help_text='Whether the minimum allowable battery state of charge is enforced during outages in addition to normal operations.'),
        ),
    ]
