# Generated by Django 4.0.7 on 2024-04-23 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0056_alter_electricloadinputs_annual_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvinputs',
            name='tilt',
            field=models.FloatField(blank=True, help_text='PV system tilt: Set tilt angle to 20 degrees for fixed arrays (rooftop or ground-mounted). Set tilt angle to 0 degrees for axis-tracking systems.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
