# Generated by Django 4.0.7 on 2024-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0057_apimeta_portfolio_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioUnlinkedRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_uuid', models.UUIDField()),
                ('user_uuid', models.UUIDField()),
                ('run_uuid', models.UUIDField(unique=True)),
            ],
        ),
    ]
