# Generated by Django 4.0.7 on 2024-04-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0057_alter_pvinputs_tilt'),
        ('reoptjl', '0057_electricstorageinputs_soc_min_applies_during_outages'),
    ]

    operations = [
    ]
