# Generated by Django 4.0.7 on 2024-09-04 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0061_ashpspaceheaterinputs_ashpspaceheateroutputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashpspaceheateroutputs',
            name='annual_electric_consumption_for_cooling_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ashpspaceheateroutputs',
            name='annual_electric_consumption_for_heating_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ashpspaceheateroutputs',
            name='electric_consumption_for_cooling_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='ashpspaceheateroutputs',
            name='electric_consumption_for_heating_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
