# Generated by Django 4.0.7 on 2024-09-05 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0062_ashpspaceheateroutputs_annual_electric_consumption_for_cooling_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashpwaterheaterinputs',
            name='min_allowable_peak_capacity_fraction',
            field=models.FloatField(blank=True, help_text='Minimum nonzero thermal power as a function of coincident peak load / CF - constraint for optimization [ton]', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000.0)]),
        ),
        migrations.AlterField(
            model_name='ashpwaterheaterinputs',
            name='min_allowable_ton',
            field=models.FloatField(blank=True, help_text='Minimum nonzero thermal power size constraint for optimization [ton]', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000.0)]),
        ),
    ]
