# Generated by Django 4.0.7 on 2024-09-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0064_alter_ashpspaceheaterinputs_min_allowable_peak_capacity_fraction_and_more'),
        ('reoptjl', '0064_siteinputs_outdoor_air_temperature_degf'),
    ]

    operations = [
    ]
