# Generated by Django 4.0.7 on 2024-09-15 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0066_alter_siteinputs_outdoor_air_temperature_degf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashpwaterheaterinputs',
            name='sizing_factor',
            field=models.FloatField(blank=True, default=1.0, help_text='Size of system relative to max dispatch output [fraction]', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000.0)]),
        ),
    ]
