# Generated by Django 4.0.7 on 2024-09-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0067_alter_ashpwaterheaterinputs_sizing_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingboileroutputs',
            name='size_mmbtu_per_hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
