# Generated by Django 4.0.7 on 2024-09-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0061_portfoliounlinkedruns_apimeta_portfolio_uuid_and_more'),
        ('reoptjl', '0069_financialoutputs_initial_capital_costs_after_incentives_without_macrs_and_more'),
    ]

    operations = [
    ]
