# Generated by Django 4.0.7 on 2024-10-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0071_rename_industry_reference_name_processheatloadinputs_industrial_reference_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestichotwaterloadinputs',
            name='normalize_and_scale_load_profile_input',
            field=models.BooleanField(blank=True, default=True, help_text='Takes the input fuel_loads_mmbtu_per_hour and normalizes and scales it to annual or monthly energy inputs.'),
        ),
        migrations.AddField(
            model_name='electricloadinputs',
            name='normalize_and_scale_load_profile_input',
            field=models.BooleanField(blank=True, default=True, help_text='Takes the input loads_kw and normalizes and scales it to annual or monthly energy inputs.'),
        ),
        migrations.AddField(
            model_name='processheatloadinputs',
            name='normalize_and_scale_load_profile_input',
            field=models.BooleanField(blank=True, default=True, help_text='Takes the input fuel_loads_mmbtu_per_hour and normalizes and scales it to annual or monthly energy inputs.'),
        ),
        migrations.AddField(
            model_name='spaceheatingloadinputs',
            name='normalize_and_scale_load_profile_input',
            field=models.BooleanField(blank=True, default=True, help_text='Takes the input fuel_loads_mmbtu_per_hour and normalizes and scales it to annual or monthly energy inputs.'),
        ),
    ]
