# Generated by Django 4.0.7 on 2025-01-18 04:04

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0075_coolingloadinputs_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashpspaceheaterinputs',
            name='force_dispatch',
            field=models.BooleanField(default=True, help_text='Boolean indicator if ASHP space heater is forced to its maximize output if true', null=True),
        ),
        migrations.AddField(
            model_name='ashpwaterheaterinputs',
            name='force_dispatch',
            field=models.BooleanField(default=True, help_text='Boolean indicator if ASHP water heater is forced to its maximize output if true', null=True),
        ),
        migrations.AlterField(
            model_name='ashpwaterheaterinputs',
            name='force_into_system',
            field=models.BooleanField(blank=True, help_text='Boolean indicator if ASHP water heater serves compatible thermal loads exclusively in optimized scenario', null=True),
        ),
        migrations.AlterField(
            model_name='ashpwaterheaterinputs',
            name='heating_cf_reference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20.0)]), blank=True, default=list, help_text='Reference points for ASHP water heating system heating capacity factor(ratio of heating thermal power to rated capacity)', size=None),
        ),
        migrations.AlterField(
            model_name='ashpwaterheaterinputs',
            name='heating_cop_reference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20.0)]), blank=True, default=list, help_text='Reference points for ASHP water heating system heating coefficient of performance (COP) (ratio of usable heating thermal energy produced per unit electric energy consumed)', size=None),
        ),
        migrations.AlterField(
            model_name='ashpwaterheaterinputs',
            name='heating_reference_temps_degF',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-275.0), django.core.validators.MaxValueValidator(200.0)]), blank=True, default=list, help_text="Reference temperatures for ASHP water heating system's heating COP and CF [Fahrenheit]", size=None),
        ),
    ]
