# Generated by Django 4.0.7 on 2025-01-27 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0076_ashpspaceheaterinputs_force_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricstorageinputs',
            name='max_duration_hours',
            field=models.FloatField(blank=True, default=100000.0, help_text='Maximum amount of time storage can discharge at its rated power capacity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000.0)]),
        ),
        migrations.AddField(
            model_name='electricstorageinputs',
            name='min_duration_hours',
            field=models.FloatField(blank=True, default=0.0, help_text='Minimum amount of time storage can discharge at its rated power capacity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000.0)]),
        ),
    ]
