# Generated by Django 4.0.7 on 2025-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0077_boileroutputs_year_one_fuel_cost_after_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatoroutputs',
            name='year_one_fuel_cost_after_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatoroutputs',
            name='year_one_fuel_cost_after_tax_bau',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
