# Generated by Django 4.0.7 on 2025-01-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0077_electricstorageinputs_max_duration_hours_and_more'),
        ('reoptjl', '0077_rename_cambium_metric_col_electricutilityinputs_cambium_co2_metric_and_more'),
    ]

    operations = [
    ]
