# Generated by Django 4.0.7 on 2025-02-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0078_generatoroutputs_year_one_fuel_cost_after_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialoutputs',
            name='initial_capital_costs_after_incentives_without_macrs',
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='capital_costs_after_incentives_without_macrs',
            field=models.FloatField(blank=True, help_text='Capital costs for all technologies, including present value of replacement costs and incentives except for MACRS.', null=True),
        ),
        migrations.AlterField(
            model_name='financialoutputs',
            name='capital_costs_after_non_discounted_incentives',
            field=models.FloatField(blank=True, help_text='Capital costs for all technologies, including present value of replacement costs and all non-discounted incentives including MACRS.', null=True),
        ),
    ]
