# Generated by Django 4.0.7 on 2025-03-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0079_remove_financialoutputs_initial_capital_costs_after_incentives_without_macrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoutputs',
            name='year_one_chp_standby_cost_after_tax',
            field=models.FloatField(blank=True, help_text='Year one CHP standby charges, after tax.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='year_one_chp_standby_cost_before_tax',
            field=models.FloatField(blank=True, help_text='Year one CHP standby charges, before tax.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='year_one_total_cost_after_tax',
            field=models.FloatField(blank=True, help_text='Year one total operating (electricity, fuel, O&M) costs, after tax.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='year_one_total_cost_after_tax_bau',
            field=models.FloatField(blank=True, help_text='Year one total operating (electricity, fuel, O&M) costs, after tax in the BAU case.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='year_one_total_cost_before_tax',
            field=models.FloatField(blank=True, help_text='Year one total operating (electricity, fuel, O&M) costs, before tax.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='year_one_total_cost_before_tax_bau',
            field=models.FloatField(blank=True, help_text='Year one total operating (electricity, fuel, O&M) costs, before tax in the BAU case.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='year_one_total_cost_savings_after_tax',
            field=models.FloatField(blank=True, help_text='Year one total operating (electricity, fuel, O&M) cost savings compared to BAU case, after tax.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='year_one_total_cost_savings_before_tax',
            field=models.FloatField(blank=True, help_text='Year one total operating (electricity, fuel, O&M) cost savings compared to BAU case, before tax.', null=True),
        ),
    ]
