# Generated by Django 4.0.7 on 2025-03-04 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0080_electricloadoutputs_annual_electric_load_with_thermal_conversions_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvinputs',
            name='acres_per_kw',
            field=models.FloatField(blank=True, default=0.006, help_text='The acres per kW-DC for ground-mount PV systems in acres per kW, accounting for setbacks, row spacing, etc. The recommended PV system size is constrained based on the sum of land area available, assuming the ground-mount power density specified here, and roofspace available, assuming the specified rooftop power density.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='pvinputs',
            name='kw_per_square_foot',
            field=models.FloatField(blank=True, default=0.01, help_text='The installed power density for rooftop PV systems in kW per square foot, accounting for setbacks, row spacing, etc. The recommended PV system size is constrained based on the sum of land area available, assuming the specified ground-mount power density, and roofspace available, assuming the rooftop power density specified here.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
