# Generated by Django 4.0.7 on 2025-03-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0080_electricloadoutputs_annual_electric_load_with_thermal_conversions_kwh_and_more'),
        ('reoptjl', '0080_financialoutputs_year_one_chp_standby_cost_after_tax_and_more'),
    ]

    operations = [
    ]
