# Generated by Django 4.0.7 on 2025-04-22 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0080_electricloadoutputs_annual_electric_load_with_thermal_conversions_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpinputs',
            name='load_served_by_ghp',
            field=models.TextField(blank=True, default='nonpeak', help_text='How to split between load served by GHP and load served by backup system'),
        ),
        migrations.AddField(
            model_name='ghpinputs',
            name='max_number_of_boreholes',
            field=models.FloatField(blank=True, help_text='Maximum number of boreholes for GHX', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000.0)]),
        ),
        migrations.AddField(
            model_name='ghpinputs',
            name='max_ton',
            field=models.FloatField(blank=True, help_text='Maximum thermal power size constraint for GHP [ton]', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000.0)]),
        ),
    ]
