# Generated by Django 4.0.7 on 2025-03-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0081_merge_20250303_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialoutputs',
            old_name='capital_costs_after_incentives_without_macrs',
            new_name='capital_costs_after_non_discounted_incentives_without_macrs',
        ),
        migrations.RenameField(
            model_name='financialoutputs',
            old_name='year_one_total_cost_after_tax',
            new_name='year_one_total_operating_cost_after_tax',
        ),
        migrations.RenameField(
            model_name='financialoutputs',
            old_name='year_one_total_cost_after_tax_bau',
            new_name='year_one_total_operating_cost_after_tax_bau',
        ),
        migrations.RenameField(
            model_name='financialoutputs',
            old_name='year_one_total_cost_before_tax',
            new_name='year_one_total_operating_cost_before_tax',
        ),
        migrations.RenameField(
            model_name='financialoutputs',
            old_name='year_one_total_cost_before_tax_bau',
            new_name='year_one_total_operating_cost_before_tax_bau',
        ),
        migrations.RenameField(
            model_name='financialoutputs',
            old_name='year_one_total_cost_savings_after_tax',
            new_name='year_one_total_operating_cost_savings_after_tax',
        ),
        migrations.RenameField(
            model_name='financialoutputs',
            old_name='year_one_total_cost_savings_before_tax',
            new_name='year_one_total_operating_cost_savings_before_tax',
        ),
    ]
