# Generated by Django 4.0.7 on 2025-04-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0082_rename_capital_costs_after_incentives_without_macrs_financialoutputs_capital_costs_after_non_discoun'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricutilityoutputs',
            name='peak_grid_demand_kw',
            field=models.FloatField(blank=True, help_text='Maximum grid demand calculated as the maximum of (electric_to_load_series_kw .+ electric_to_storage_series_kw).', null=True),
        ),
        migrations.AddField(
            model_name='electricutilityoutputs',
            name='peak_grid_demand_kw_bau',
            field=models.FloatField(blank=True, help_text='Maximum grid demand in the BAU case calculated as the maximum of electric_to_load_series_kw.', null=True),
        ),
    ]
