# Generated by Django 4.0.7 on 2025-04-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0081_pvinputs_acres_per_kw_pvinputs_kw_per_square_foot'),
        ('reoptjl', '0083_electricutilityoutputs_peak_grid_demand_kw_and_more'),
    ]

    operations = [
    ]
