# Generated by Django 4.0.7 on 2025-04-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0081_ghpinputs_load_served_by_ghp_and_more'),
        ('reoptjl', '0083_electricutilityoutputs_peak_grid_demand_kw_and_more'),
    ]

    operations = [
    ]
