# Generated by Django 4.0.7 on 2025-05-09 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0084_merge_20250424_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvinputs',
            name='size_class',
            field=models.IntegerField(blank=True, help_text='PV size class. Must be an integer value between 1 and 5. Default is 2, representing commercial-scale', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='pvoutputs',
            name='installed_cost_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvoutputs',
            name='om_cost_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvinputs',
            name='installed_cost_per_kw',
            field=models.FloatField(blank=True, help_text='Installed PV cost in $/kW', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
        migrations.AlterField(
            model_name='pvinputs',
            name='om_cost_per_kw',
            field=models.FloatField(blank=True, help_text='Annual PV operations and maintenance costs in $/kW', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
