# Generated by Django 4.0.7 on 2025-05-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0081_cstoutputs_cstinputs'),
        ('reoptjl', '0084_merge_20250424_1814'),
    ]

    operations = [
    ]
