# Generated by Django 4.0.7 on 2025-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0084_merge_20250423_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpoutputs',
            name='annual_thermal_production_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpoutputs',
            name='annual_thermal_production_tonhour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
