# Generated by Django 4.0.7 on 2025-05-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0085_merge_20250507_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstinputs',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CSTInputs', to='reoptjl.apimeta'),
        ),
    ]
