# Generated by Django 4.0.7 on 2025-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0085_financialinputs_max_initial_capital_costs_before_incentives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpoutputs',
            name='initial_capital_costs',
            field=models.FloatField(blank=True, help_text='Initial capital costs of the CHP system, before incentives [\\$]', null=True),
        ),
    ]
