# Generated by Django 4.0.7 on 2025-06-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0086_chpoutputs_initial_capital_costs'),
        ('reoptjl', '0086_electricstorageinputs_om_cost_fraction_of_installed_cost_and_more'),
    ]

    operations = [
    ]
