# Generated by Django 4.0.7 on 2025-05-08 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0087_cstinputs_inlet_temp_degf_cstinputs_outlet_temp_degf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstinputs',
            name='acres_per_kw',
            field=models.FloatField(blank=True, default=0.000939, help_text='Power density for CST', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='charge_storage_only',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if CST can only supply hot TES', null=True),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='macrs_bonus_fraction',
            field=models.FloatField(blank=True, default=0.0, help_text='Percent of upfront project costs to depreciate in year one in addition to scheduled depreciation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='om_cost_per_kw',
            field=models.FloatField(blank=True, default=0.0, help_text='Annual CST operations and maintenance costs in $/kW', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='om_cost_per_kwh',
            field=models.FloatField(blank=True, default=0.0, help_text='Annual CST operations and maintenance costs in $/kWh', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
