# Generated by Django 4.0.7 on 2025-06-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0087_merge_20250604_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoutputs',
            name='initial_capital_costs_after_incentives_bau',
            field=models.FloatField(blank=True, help_text='Up-front capital costs for BAU technologies such as ExistingBoiler and ExistingChiller, in present value.', null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_capital_costs_bau',
            field=models.FloatField(blank=True, help_text='Net capital costs for BAU technologies such as ExistingBoiler and ExistingChiller, in present value.', null=True),
        ),
    ]
