# Generated by Django 4.0.7 on 2025-05-08 16:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0088_alter_cstinputs_acres_per_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricheateroutputs',
            name='thermal_to_hot_sensible_tes_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
