# Generated by Django 4.0.7 on 2025-06-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0085_ghpoutputs_annual_thermal_production_mmbtu_and_more'),
        ('reoptjl', '0090_existingboilerinputs_installed_cost_dollars_and_more'),
    ]

    operations = [
    ]
