# Generated by Django 4.0.7 on 2025-06-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0085_pvinputs_size_class_pvoutputs_installed_cost_per_kw_and_more'),
        ('reoptjl', '0091_merge_20250604_2023'),
    ]

    operations = [
    ]
