# Generated by Django 4.0.7 on 2025-05-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0091_cstoutputs_thermal_to_dhw_load_series_mmbtu_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstoutputs',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CSTOutputs', to='reoptjl.apimeta'),
        ),
    ]
