# Generated by Django 4.0.7 on 2025-09-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0092_merge_20250613_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinputs',
            name='federal_procurement_type',
            field=models.TextField(blank=True, choices=[('fedowned_dirpurch', 'Fedowned Dirpurch'), ('fedowned_thirdparty', 'Fedowned Third Party'), ('privateowned_thirdparty', 'Privateowned Third Party')], default=''),
        ),
        migrations.AddField(
            model_name='siteinputs',
            name='federal_sector_state',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteinputs',
            name='sector',
            field=models.TextField(blank=True, choices=[('commercial/industrial', 'Commercial'), ('federal', 'Federal')], default='commercial/industrial'),
        ),
    ]
