# Generated by Django 4.0.7 on 2025-05-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0093_hotsensibletesinputs_hotsensibletesoutputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsensibletesinputs',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='HotSensibleTesInputs', serialize=False, to='reoptjl.apimeta'),
        ),
        migrations.AlterField(
            model_name='hotsensibletesoutputs',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='HotSensibleTesOutputs', serialize=False, to='reoptjl.apimeta'),
        ),
    ]
