# Generated by Django 4.0.7 on 2025-08-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0092_merge_20250613_0525'),
        ('reoptjl', '0094_alter_hotsensibletesinputs_meta_and_more'),
    ]

    operations = [
    ]
