# Generated by Django 4.0.7 on 2025-08-08 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0095_merge_20250729_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstinputs',
            name='inlet_temp_degF',
            field=models.FloatField(blank=True, default=400, help_text="This is the temperature at which your process needs the heat transfer fluid specified above to be at when entering your facility. In other words, this is your 'hot' temperature.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(750)]),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='outlet_temp_degF',
            field=models.FloatField(blank=True, default=70, help_text="This is the temperature at which your the heat transfer fluid specified above returns from your process after heat has been extracted. In other words, this is your cold' temperature. If you have an open system, the inlet temperature will be assumed to be ambient temperature (20 C / 68 F).", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(750)]),
        ),
    ]
