# Generated by Django 4.0.7 on 2025-08-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0095_merge_20250808_1803'),
        ('reoptjl', '0096_alter_cstinputs_inlet_temp_degf_and_more'),
    ]

    operations = [
    ]
