# Generated by Django 4.0.7 on 2025-08-20 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0097_merge_20250811_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstinputs',
            name='can_serve_dhw',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if CST can serve hot water load', null=True),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='can_serve_space_heating',
            field=models.BooleanField(blank=True, default=False, help_text='Boolean indicator if CST can serve space heating load', null=True),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='macrs_bonus_fraction',
            field=models.FloatField(blank=True, default=0.6, help_text='Percent of upfront project costs to depreciate in year one in addition to scheduled depreciation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
