# Generated by Django 4.0.7 on 2025-08-18 17:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0097_merge_20250811_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamturbineoutputs',
            name='thermal_to_hot_sensible_tes_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, size=None),
        ),
    ]
