# Generated by Django 4.0.7 on 2025-08-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0098_alter_cstinputs_can_serve_dhw_and_more'),
        ('reoptjl', '0098_steamturbineoutputs_thermal_to_hot_sensible_tes_series_mmbtu_per_hour'),
    ]

    operations = [
    ]
