# Generated by Django 4.0.7 on 2025-08-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0100_hightempthermalstorageinputs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cstoutputs',
            old_name='thermal_to_hot_sensible_tes_storage_series_mmbtu_per_hour',
            new_name='thermal_to_high_temp_thermal_storage_series_mmbtu_per_hour',
        ),
        migrations.RenameField(
            model_name='electricheateroutputs',
            old_name='thermal_to_hot_sensible_tes_series_mmbtu_per_hour',
            new_name='thermal_to_high_temp_thermal_storage_series_mmbtu_per_hour',
        ),
        migrations.RenameField(
            model_name='steamturbineoutputs',
            old_name='thermal_to_hot_sensible_tes_series_mmbtu_per_hour',
            new_name='thermal_to_high_temp_thermal_storage_series_mmbtu_per_hour',
        ),
    ]
