# Generated by Django 4.0.7 on 2025-09-05 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0100_hightempthermalstorageinputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hightempthermalstorageinputs',
            name='installed_cost_per_kwh',
            field=models.FloatField(blank=True, default=62, help_text='Installed hot TES cost in $/kwh', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='hightempthermalstorageinputs',
            name='macrs_bonus_fraction',
            field=models.FloatField(blank=True, default=1.0, help_text='Percent of upfront project costs to depreciate in year one in addition to scheduled depreciation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hightempthermalstorageinputs',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, choices=[(0, 'Zero'), (5, 'Five'), (7, 'Seven')], default=5, help_text='Duration over which accelerated depreciation will occur. Set to zero to disable'),
        ),
    ]
