# Generated by Django 4.0.7 on 2025-09-07 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0101_alter_hightempthermalstorageinputs_installed_cost_per_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstinputs',
            name='installed_cost_per_kw',
            field=models.FloatField(blank=True, default=2200.0, help_text='Installed CST cost in $/kW', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='macrs_bonus_fraction',
            field=models.FloatField(blank=True, default=0.0, help_text='Percent of upfront project costs to depreciate in year one in addition to scheduled depreciation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, choices=[(0, 'Zero'), (5, 'Five'), (7, 'Seven')], default=0, help_text='Duration over which accelerated depreciation will occur. Set to zero to disable'),
        ),
        migrations.AlterField(
            model_name='cstinputs',
            name='om_cost_per_kw',
            field=models.FloatField(blank=True, default=33.0, help_text='Annual CST operations and maintenance costs in $/kW', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='hightempthermalstorageinputs',
            name='installed_cost_per_kwh',
            field=models.FloatField(blank=True, default=86.0, help_text='Installed hot TES cost in $/kwh', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
    ]
