# Generated by Django 4.0.7 on 2025-09-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0101_rename_thermal_to_hot_sensible_tes_storage_series_mmbtu_per_hour_cstoutputs_thermal_to_high_temp_the'),
    ]

    operations = [
        migrations.AddField(
            model_name='cstoutputs',
            name='size_mmbtu_per_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hightempthermalstorageinputs',
            name='fluid',
            field=models.TextField(blank=True, default='INCOMP::NaK', help_text='Type of Fluid for High Temp Thermal Storage System'),
        ),
    ]
