# Generated by Django 4.0.7 on 2025-09-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0094_alter_chpinputs_macrs_bonus_fraction_and_more'),
        ('reoptjl', '0102_alter_cstinputs_installed_cost_per_kw_and_more'),
    ]

    operations = [
    ]
