# Generated by Django 4.0.7 on 2025-09-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0103_merge_20250917_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cstinputs',
            name='can_waste_heat',
            field=models.BooleanField(blank=True, default=True, help_text='Boolean indicator if CST waste (not use) heat relative to its potential production', null=True),
        ),
    ]
