# Generated by Django 4.2.24 on 2025-09-30 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0104_cstinputs_can_waste_heat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpoutputs',
            name='initial_capital_costs',
            field=models.FloatField(blank=True, help_text='Initial capital costs of the CHP system, before incentives [$]', null=True),
        ),
        migrations.AlterField(
            model_name='chpoutputs',
            name='lifecycle_fuel_cost_after_tax',
            field=models.FloatField(blank=True, help_text='Present value of cost of fuel consumed by the CHP system, after tax [$]', null=True),
        ),
        migrations.AlterField(
            model_name='chpoutputs',
            name='year_one_fuel_cost_after_tax',
            field=models.FloatField(blank=True, help_text='Cost of fuel consumed by the CHP system in year one, after tax [$]', null=True),
        ),
        migrations.AlterField(
            model_name='chpoutputs',
            name='year_one_fuel_cost_before_tax',
            field=models.FloatField(blank=True, help_text='Cost of fuel consumed by the CHP system in year one [$]', null=True),
        ),
        migrations.AlterField(
            model_name='chpoutputs',
            name='year_one_standby_cost_after_tax',
            field=models.FloatField(blank=True, help_text='CHP standby charges in year one, after tax [$]', null=True),
        ),
        migrations.AlterField(
            model_name='chpoutputs',
            name='year_one_standby_cost_before_tax',
            field=models.FloatField(blank=True, help_text='CHP standby charges in year one [$]', null=True),
        ),
        migrations.AlterField(
            model_name='financialinputs',
            name='max_initial_capital_costs_before_incentives',
            field=models.FloatField(blank=True, help_text='Maximum up-front capital cost for all technologies, excluding replacement costs and incentives [$].', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000.0)]),
        ),
        migrations.AlterField(
            model_name='financialinputs',
            name='min_initial_capital_costs_before_incentives',
            field=models.FloatField(blank=True, help_text='Minimum up-front capital cost for all technologies, excluding replacement costs and incentives [$].', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000.0)]),
        ),
    ]
