# Generated by Django 4.0.7 on 2025-10-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0105_siteinputs_federal_procurement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpoutputs',
            name='number_of_boreholes_flipped_guess',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
