# Generated by Django 4.0.7 on 2025-09-30 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0105_siteinputs_federal_procurement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hightempthermalstorageinputs',
            name='macrs_bonus_fraction',
            field=models.FloatField(blank=True, help_text='Percent of upfront project costs to depreciate in year one in addition to scheduled depreciation', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hightempthermalstorageinputs',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, choices=[(0, 'Zero'), (5, 'Five'), (7, 'Seven')], help_text='Duration over which accelerated depreciation will occur. Set to zero to disable', null=True),
        ),
        migrations.AlterField(
            model_name='hightempthermalstorageinputs',
            name='total_itc_fraction',
            field=models.FloatField(blank=True, help_text='Total investment tax credit in percent applied toward capital costs', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
