# Generated by Django 4.0.7 on 2025-10-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0106_ghpoutputs_number_of_boreholes_flipped_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpoutputs',
            name='hybrid_solution_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpoutputs',
            name='iterations_auto_guess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpoutputs',
            name='iterations_flipped_guess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpoutputs',
            name='iterations_nonhybrid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpoutputs',
            name='number_of_boreholes_auto_guess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpoutputs',
            name='number_of_boreholes_nonhybrid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpoutputs',
            name='solve_time_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
