# Generated by Django 4.2.24 on 2025-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0106_electricloadoutputs_annual_peak_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_demand_comments',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_energy_comments',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_label',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_peak_kw_capacity_max',
            field=models.FloatField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_peak_kw_capacity_min',
            field=models.FloatField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_rate_additional_info',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_rate_description',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_rate_effective_date',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_rate_name',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_url_link',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_utility',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='urdb_voltage_level',
            field=models.TextField(blank=True, help_text='Business as usual life cycle utility minimum charge adder, after-tax', null=True),
        ),
    ]
