# Generated by Django 4.0.7 on 2025-10-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0105_alter_chpoutputs_initial_capital_costs_and_more'),
        ('reoptjl', '0107_ghpoutputs_hybrid_solution_type_and_more'),
    ]

    operations = [
    ]
