# Generated by Django 4.0.7 on 2025-10-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0108_merge_20251003_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghpoutputs',
            name='iterations_auto_guess',
        ),
        migrations.RemoveField(
            model_name='ghpoutputs',
            name='iterations_flipped_guess',
        ),
        migrations.RemoveField(
            model_name='ghpoutputs',
            name='iterations_nonhybrid',
        ),
        migrations.RemoveField(
            model_name='ghpoutputs',
            name='number_of_boreholes_auto_guess',
        ),
        migrations.RemoveField(
            model_name='ghpoutputs',
            name='number_of_boreholes_flipped_guess',
        ),
        migrations.RemoveField(
            model_name='ghpoutputs',
            name='number_of_boreholes_nonhybrid',
        ),
        migrations.RemoveField(
            model_name='ghpoutputs',
            name='solve_time_min',
        ),
    ]
