# Generated by Django 4.2.25 on 2025-10-28 21:29

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0109_remove_ghpoutputs_iterations_auto_guess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricloadinputs',
            name='monthly_peaks_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000.0)]), blank=True, default=list, help_text="Monthly peak power consumption (an array 12 entries long), in kW, used to scale either loads_kw series (with normalize_and_scale_load_profile_input) or the simulated default building load profile for the site's climate zone.Monthly energy is maintained while scaling to the monthly peaks.", size=None),
        ),
        migrations.AddField(
            model_name='electricloadoutputs',
            name='annual_peak_kw',
            field=models.FloatField(blank=True, help_text='Annual peak energy demand determined from load_series_kw. Does not include electric load for any new heating or cooling techs.', null=True),
        ),
        migrations.AddField(
            model_name='electricloadoutputs',
            name='monthly_calculated_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Monthly energy consumption calculated by summing up load_series_kw. Does not include electric load for any new heating or cooling techs.', size=None),
        ),
        migrations.AddField(
            model_name='electricloadoutputs',
            name='monthly_peaks_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Monthly peak energy demand determined from load_series_kw. Does not include electric load for any new heating or cooling techs.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffinputs',
            name='urdb_metadata',
            field=models.JSONField(blank=True, help_text='Utility rate meta data from Utility Rate Database API', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='demand_rate_average_series',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Series of average (across tiers) demand rates for each timestep in year one.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='energy_cost_series_before_tax',
            field=models.JSONField(blank=True, help_text='Series of cost of power purchased from grid to serve load in each timestep, by Tier_i.', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='energy_cost_series_before_tax_bau',
            field=models.JSONField(blank=True, help_text='Business as usual series of cost of power purchased from grid to serve load in each timestep, by Tier_i.', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='energy_rate_average_series',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Series of average (across tiers) energy rates for each timestep in year one.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='energy_rate_series',
            field=models.JSONField(blank=True, help_text='Series of billed energy rates for each timestep in year one.', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='energy_rate_tier_limits',
            field=models.JSONField(blank=True, help_text='Energy rate tier limits', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='facility_demand_monthly_rate_series',
            field=models.JSONField(blank=True, help_text='Facility (not dependent on TOU) demand charge rates by Tier_i', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='facility_demand_monthly_rate_tier_limits',
            field=models.JSONField(blank=True, help_text='Facility (not dependent on TOU) demand charge tier limits', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_demand_cost_series_before_tax',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Series of total (facility and TOU for all tiers) monthly demand charges for each month.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_demand_cost_series_before_tax_bau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Business as usual series of total (facility and TOU for all tiers) monthly demand charges for each month.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_energy_cost_series_before_tax',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Series of monthly cost of power purchased from grid to serve loads.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_energy_cost_series_before_tax_bau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Business as usual series of monthly cost of power purchased from grid to serve loads.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_facility_demand_cost_series_before_tax',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Series of total (all tiers) monthly facility demand charges by month.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_facility_demand_cost_series_before_tax_bau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Business as usual series of total (all tiers) monthly facility demand charges by month.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_fixed_cost',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Year one fixed utility costs for each month.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_fixed_cost_bau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Business as usual year one fixed utility costs for each month.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_tou_demand_cost_series_before_tax',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Series of total time-of-use demand charges for each month.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='monthly_tou_demand_cost_series_before_tax_bau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, help_text='Business as usual series of total time-of-use demand charges for each month.', size=None),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='tou_demand_metrics',
            field=models.JSONField(blank=True, help_text='Dictionary of TOU demand metrics, including month, tier, demand_rate, measured_tou_peak_demand, and demand_charge_before_tax', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='tou_demand_rate_series',
            field=models.JSONField(blank=True, help_text='Series of demand rates by Tier_i for each timestep.', null=True),
        ),
        migrations.AddField(
            model_name='electrictariffoutputs',
            name='tou_demand_rate_tier_limits',
            field=models.JSONField(blank=True, help_text='TOU demand rate tier limits', null=True),
        ),
        migrations.AlterField(
            model_name='electricloadinputs',
            name='monthly_totals_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000.0)]), blank=True, default=list, help_text="Monthly site energy consumption (an array 12 entries long), in kWh, used to scale either loads_kw series (with normalize_and_scale_load_profile_input) or the simulated default building load profile for the site's climate zone", size=None),
        ),
        migrations.AlterField(
            model_name='electricloadinputs',
            name='normalize_and_scale_load_profile_input',
            field=models.BooleanField(blank=True, default=False, help_text='Takes the input loads_kw and normalizes and scales it to the inputs annual_kwh, monthly_totals_kwh, and/or monthly_peaks_kw.'),
        ),
    ]
