# Generated by Django 4.2.25 on 2025-10-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0107_electrictariffoutputs_urdb_demand_comments_and_more'),
        ('reoptjl', '0109_remove_ghpoutputs_iterations_auto_guess_and_more'),
    ]

    operations = [
    ]
