# Generated by Django 4.2.25 on 2025-10-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0110_merge_20251022_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_demand_comments',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_energy_comments',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_label',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_peak_kw_capacity_max',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_peak_kw_capacity_min',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_rate_additional_info',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_rate_description',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_rate_effective_date',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_rate_name',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_url_link',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_utility',
        ),
        migrations.RemoveField(
            model_name='electrictariffoutputs',
            name='urdb_voltage_level',
        ),
        migrations.AddField(
            model_name='electrictariffinputs',
            name='urdb_metadata',
            field=models.JSONField(blank=True, help_text='Utility rate meta data from Utility Rate Database API', null=True),
        ),
    ]
