# Generated by Django 4.2.25 on 2025-10-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0110_electricloadinputs_monthly_peaks_kw_and_more'),
        ('reoptjl', '0110_electricloadoutputs_annual_peak_kw_and_more'),
    ]

    operations = [
    ]
