# Generated by Django 4.2.26 on 2025-12-01 23:45

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0110_electricloadinputs_monthly_peaks_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricloadinputs',
            name='monthly_totals_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000.0)]), blank=True, default=list, help_text="Monthly site energy consumption (an array 12 entries long), in kWh, used to scale either loads_kw series (with normalize_and_scale_load_profile_input) or the simulated default building load profile for the site's climate zone", size=None),
        ),
    ]
