# Generated by Django 4.2.25 on 2025-10-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0111_remove_electrictariffoutputs_urdb_demand_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='NEM_electric_to_grid_series_kw',
            new_name='net_metering_electric_to_grid_series_kw',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='EXC_electric_to_grid_series_kw',
            new_name='net_metering_excess_electric_to_grid_series_kw',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='EXC_export_rate_series',
            new_name='net_metering_excess_export_rate_series',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='EXC_monthly_export_cost_benefit_before_tax',
            new_name='net_metering_excess_monthly_export_cost_benefit_before_tax',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='EXC_monthly_export_series_kwh',
            new_name='net_metering_excess_monthly_export_series_kwh',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='NEM_export_rate_series',
            new_name='net_metering_export_rate_series',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='NEM_monthly_export_cost_benefit_before_tax',
            new_name='net_metering_monthly_export_cost_benefit_before_tax',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='NEM_monthly_export_series_kwh',
            new_name='net_metering_monthly_export_series_kwh',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='WHL_electric_to_grid_series_kw',
            new_name='wholesale_electric_to_grid_series_kw',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='WHL_export_rate_series',
            new_name='wholesale_export_rate_series',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='WHL_monthly_export_cost_benefit_before_tax',
            new_name='wholesale_monthly_export_cost_benefit_before_tax',
        ),
        migrations.RenameField(
            model_name='electrictariffoutputs',
            old_name='WHL_monthly_export_series_kwh',
            new_name='wholesale_monthly_export_series_kwh',
        ),
    ]
