# Generated by Django 4.2.26 on 2025-12-08 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0111_alter_electricloadinputs_monthly_totals_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='windinputs',
            name='acres_per_kw',
            field=models.FloatField(blank=True, default=0.03, help_text='Land area required per kW of wind capacity in acres/kW; only constrained by this for systems greater than 1500 kW', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
