# Generated by Django 4.2.26 on 2025-12-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0105_alter_coolingloadinputs_annual_tonhour_and_more'),
        ('reoptjl', '0112_windinputs_acres_per_kw'),
    ]

    operations = [
    ]
