# Generated by Django 4.2.25 on 2025-10-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reoptjl', '0112_rename_nem_electric_to_grid_series_kw_electrictariffoutputs_net_metering_electric_to_grid_series_kw_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricloadoutputs',
            old_name='monthly_peak_kw',
            new_name='monthly_peaks_kw',
        ),
    ]
