version: "2.1"

services: 
  licenseserver:
    container_name: xpress_license_server
    build:
      context: ./xpress/licenseserver
    mac_address: c4:b3:01:d3:d5:eb
    command: xpserver
    ports:
      - "27100:27100"
  
  julia:
    container_name: julia_api
    build:
      context: .
    command: julia --project="/opt/julia_src" api.jl
    ports:
      - "8081:8081"