# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 21:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResilienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resilience_by_timestep', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None)),
                ('resilience_hours_min', models.FloatField(null=True)),
                ('resilience_hours_max', models.FloatField(null=True)),
                ('resilience_hours_avg', models.FloatField(null=True)),
                ('outage_durations', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None)),
                ('probs_of_surviving', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None)),
                ('scenario_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reo.ScenarioModel')),
            ],
        ),
    ]
