# Generated by Django 2.2.6 on 2020-02-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0005_auto_20190731_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resiliencemodel',
            name='survives_specified_outage',
        ),
    ]
