# Generated by Django 2.2.10 on 2020-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0006_remove_resiliencemodel_survives_specified_outage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resiliencemodel',
            name='avoided_outage_costs_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
