# Generated by Django 4.0.4 on 2022-11-30 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0008_erpmeta_erpinputs_erpoutputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpinputs',
            name='battery_operational_availability',
            field=models.FloatField(blank=True, default=1.0, help_text='Fraction of year battery system not down for maintenance', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='erpinputs',
            name='pv_operational_availability',
            field=models.FloatField(blank=True, default=1.0, help_text='Fraction of year PV system not down for maintenance', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
