# Generated by Django 4.0.4 on 2022-09-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0008_erpmeta_erpinputs_erpoutputs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erpoutputs',
            old_name='cumulative_outage_survival_probability',
            new_name='cumulative_outage_survival_final_time_step',
        ),
        migrations.RenameField(
            model_name='erpoutputs',
            old_name='mean_cumulative_outage_survival_probability',
            new_name='mean_cumulative_outage_survival_final_time_step',
        ),
        migrations.RenameField(
            model_name='erpoutputs',
            old_name='mean_cumulative_duration_survival_probability',
            new_name='mean_cumulative_survival_by_duration',
        ),
        migrations.RenameField(
            model_name='erpoutputs',
            old_name='mean_marginal_duration_survival_probability',
            new_name='mean_marginal_survival_by_duration',
        ),
        migrations.RenameField(
            model_name='erpoutputs',
            old_name='min_cumulative_duration_survival_probability',
            new_name='min_cumulative_survival_by_duration',
        ),
        migrations.RenameField(
            model_name='erpoutputs',
            old_name='min_marginal_duration_survival_probability',
            new_name='min_marginal_survival_by_duration',
        ),
    ]
