# Generated by Django 4.0.6 on 2022-09-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0010_remove_erpinputs_starting_battery_soc_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpoutputs',
            name='mean_cumulative_outage_survival_final_time_step',
            field=models.FloatField(blank=True, help_text='The mean, calculated over outages starting at each hour of the year, of the probability of surviving the full max_outage_duration.', null=True),
        ),
    ]
