# Generated by Django 4.0.4 on 2022-12-01 22:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0010_erpinputs_fuel_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpoutputs',
            name='mean_marginal_survival_by_duration',
        ),
        migrations.RemoveField(
            model_name='erpoutputs',
            name='min_marginal_survival_by_duration',
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='fuel_outage_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, help_text='Whether there is sufficient fuel to survive the full max_outage_duration, for outages starting at each hour of the year. A 1 means true, a 0 means false.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='mean_fuel_survival_by_duration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The probability, averaged over outages starting at each hour of the year, of having sufficient fuel to survive up to and including each hour of max_outage_duration.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='monthly_cumulative_outage_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The monthly means, calculated over outages starting at each hour of the month, of the probability of surviving the full max_outage_duration.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='unlimited_fuel_cumulative_outage_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The probability of surviving the full max_outage_duration, for outages starting at each hour of the year, if generator fuel is unlimited.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='unlimited_fuel_mean_cumulative_survival_by_duration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The mean, calculated over outages starting at each hour of the year, of the probability of surviving up to and including each hour of max_outage_duration, if generator fuel is unlimited.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='unlimited_fuel_min_cumulative_survival_by_duration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The minimum, calculated over outages starting at each hour of the year, of the probability of surviving up to and including each hour of max_outage_duration, if generator fuel is unlimited.', size=None),
        ),
        migrations.AlterField(
            model_name='erpoutputs',
            name='mean_cumulative_survival_by_duration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The mean, calculated over outages starting at each hour of the year, of the probability of surviving up to and including each hour of max_outage_duration.', size=None),
        ),
        migrations.AlterField(
            model_name='erpoutputs',
            name='min_cumulative_survival_by_duration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The minimum, calculated over outages starting at each hour of the year, of the probability of surviving up to and including each hour of max_outage_duration.', size=None),
        ),
    ]
