# Generated by Django 4.0.4 on 2022-12-28 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0011_rename_cumulative_outage_survival_final_time_step_erpoutputs_cumulative_survival_final_time_step_and'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpoutputs',
            name='monthly_cumulative_survival_final_time_step',
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='monthly_lower_quartile_cumulative_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The monthly lower quartile cutoff, calculated over outages starting at each hour of the month, of the probability of surviving the full max_outage_duration.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='monthly_max_cumulative_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The monthly maximums, calculated over outages starting at each hour of the month, of the probability of surviving the full max_outage_duration.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='monthly_median_cumulative_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The monthly medians, calculated over outages starting at each hour of the month, of the probability of surviving the full max_outage_duration.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='monthly_min_cumulative_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The monthly minimums, calculated over outages starting at each hour of the month, of the probability of surviving the full max_outage_duration.', size=None),
        ),
        migrations.AddField(
            model_name='erpoutputs',
            name='monthly_upper_quartile_cumulative_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The monthly upper quartile cutoff, calculated over outages starting at each hour of the month, of the probability of surviving the full max_outage_duration.', size=None),
        ),
    ]
