# Generated by Django 4.0.4 on 2022-12-01 22:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0011_remove_erpoutputs_mean_marginal_survival_by_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpoutputs',
            name='monthly_cumulative_outage_survival_final_time_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='The monthly means, calculated over outages starting at each hour of the month, of the probability of surviving the full max_outage_duration.', size=None),
        ),
    ]
