# Generated by Django 4.0.4 on 2023-03-24 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0011_alter_erpgeneratorinputs_electric_efficiency_half_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpoutageinputs',
            name='max_outage_duration',
            field=models.IntegerField(help_text='Maximum outage duration modeled', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(672)]),
        ),
    ]
