# Generated by Django 4.0.4 on 2023-01-01 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0012_remove_erpoutputs_monthly_cumulative_survival_final_time_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpgeneratorinputs',
            name='failure_to_start',
            field=models.FloatField(blank=True, default=0.0094, help_text='Chance of generator not starting when an outage occurs', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='erpgeneratorinputs',
            name='mean_time_to_failure',
            field=models.FloatField(blank=True, default=1100, help_text="Average number of time steps between a generator's failures. 1/(failure to run probability).", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='erpgeneratorinputs',
            name='operational_availability',
            field=models.FloatField(blank=True, default=0.995, help_text='Fraction of year generators not down for maintenance', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
