# Generated by Django 4.0.4 on 2023-05-31 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0012_alter_erpoutageinputs_max_outage_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpelectricstorageinputs',
            name='num_battery_bins',
            field=models.IntegerField(blank=True, help_text='Number of bins for discretely modeling battery state of charge', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
