# Generated by Django 4.0.4 on 2022-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0013_remove_erpinputs_battery_starting_soc_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmeta',
            name='status',
            field=models.TextField(blank=True, default='', help_text='Status of the ERP job.'),
        ),
    ]
