# Generated by Django 4.0.7 on 2023-09-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0014_erpwindinputs_and_more'),
        ('resilience_stats', '0014_rename_fuel_outage_survival_final_time_step_erpoutputs_fuel_survival_final_time_step'),
    ]

    operations = [
    ]
