# Generated by Django 4.0.4 on 2023-01-03 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0014_alter_erpprimegeneratorinputs_mean_time_to_failure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpgeneratorinputs',
            name='mean_time_to_failure',
            field=models.FloatField(blank=True, default=1100, help_text="Average number of time steps between a generator's failures. 1/(failure to run probability).", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
