# Generated by Django 4.0.7 on 2024-09-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience_stats', '0015_merge_20230925_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpmeta',
            name='reopt_version',
            field=models.TextField(blank=True, default='', help_text='Version number of the REopt Julia package that is used to calculate reliability.', null=True),
        ),
    ]
