# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.postgres.fields
import uuid
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunInput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_id', models.TextField(default=b'', blank=True)),
                ('api_version', models.TextField(default=b'', blank=True)),
                ('timeout', models.IntegerField(default=295, null=True, blank=True)),
                ('time_steps_per_hour', models.IntegerField(null=True, blank=True)),
                ('latitude', models.FloatField(null=True, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('land_area', models.FloatField(null=True, blank=True)),
                ('roof_area', models.FloatField(null=True, blank=True)),
                ('urdb_rate', picklefield.fields.PickledObjectField(null=True, editable=False)),
                ('load_profile_name', models.TextField(default=b'', null=True, blank=True)),
                ('load_size', models.FloatField(null=True, blank=True)),
                ('load_year', models.IntegerField(default=2018, null=True, blank=True)),
                ('load_8760_kw', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('load_monthly_kwh', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('utility_name', models.TextField(default=b'', blank=True)),
                ('rate_name', models.TextField(default=b'', blank=True)),
                ('blended_utility_rate', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('demand_charge', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('analysis_period', models.IntegerField(null=True, blank=True)),
                ('offtaker_discount_rate', models.FloatField(null=True, blank=True)),
                ('offtaker_tax_rate', models.FloatField(null=True, blank=True)),
                ('owner_discount_rate', models.FloatField(null=True, blank=True)),
                ('owner_tax_rate', models.FloatField(null=True, blank=True)),
                ('rate_escalation', models.FloatField(null=True, blank=True)),
                ('rate_inflation', models.FloatField(null=True, blank=True)),
                ('net_metering_limit', models.FloatField(null=True, blank=True)),
                ('wholesale_rate', models.FloatField(null=True, blank=True)),
                ('interconnection_limit', models.FloatField(null=True, blank=True)),
                ('pv_cost', models.FloatField(null=True, blank=True)),
                ('pv_om', models.FloatField(null=True, blank=True)),
                ('pv_kw_max', models.FloatField(null=True, blank=True)),
                ('pv_kw_min', models.FloatField(null=True, blank=True)),
                ('module_type', models.IntegerField(null=True, blank=True)),
                ('azimuth', models.FloatField(null=True, blank=True)),
                ('losses', models.FloatField(null=True, blank=True)),
                ('dc_ac_ratio', models.FloatField(null=True, blank=True)),
                ('gcr', models.FloatField(null=True, blank=True)),
                ('dataset', models.TextField(default=b'', blank=True)),
                ('inv_eff', models.FloatField(null=True, blank=True)),
                ('system_capacity', models.FloatField(null=True, blank=True)),
                ('array_type', models.IntegerField(null=True, blank=True)),
                ('timeframe', models.TextField(default=b'', blank=True)),
                ('radius', models.FloatField(null=True, blank=True)),
                ('tilt', models.FloatField(null=True, blank=True)),
                ('pv_degradation_rate', models.FloatField(null=True, blank=True)),
                ('pv_itc_federal', models.FloatField(null=True, blank=True)),
                ('pv_itc_state', models.FloatField(null=True, blank=True)),
                ('pv_itc_utility', models.FloatField(null=True, blank=True)),
                ('pv_itc_federal_max', models.FloatField(null=True, blank=True)),
                ('pv_itc_state_max', models.FloatField(null=True, blank=True)),
                ('pv_itc_utility_max', models.FloatField(null=True, blank=True)),
                ('pv_rebate_federal', models.FloatField(null=True, blank=True)),
                ('pv_rebate_state', models.FloatField(null=True, blank=True)),
                ('pv_rebate_utility', models.FloatField(null=True, blank=True)),
                ('pv_rebate_federal_max', models.FloatField(null=True, blank=True)),
                ('pv_rebate_state_max', models.FloatField(null=True, blank=True)),
                ('pv_rebate_utility_max', models.FloatField(null=True, blank=True)),
                ('pv_pbi', models.FloatField(null=True, blank=True)),
                ('pv_pbi_max', models.FloatField(null=True, blank=True)),
                ('pv_pbi_years', models.FloatField(null=True, blank=True)),
                ('pv_pbi_system_max', models.FloatField(null=True, blank=True)),
                ('pv_macrs_schedule', models.IntegerField(null=True, blank=True)),
                ('pv_macrs_bonus_fraction', models.FloatField(null=True, blank=True)),
                ('batt_cost_kwh', models.FloatField(null=True, blank=True)),
                ('batt_cost_kw', models.FloatField(null=True, blank=True)),
                ('batt_replacement_cost_kw', models.FloatField(null=True, blank=True)),
                ('batt_replacement_cost_kwh', models.FloatField(null=True, blank=True)),
                ('batt_replacement_year_kw', models.IntegerField(null=True, blank=True)),
                ('batt_replacement_year_kwh', models.IntegerField(null=True, blank=True)),
                ('batt_kw_max', models.FloatField(null=True, blank=True)),
                ('batt_kw_min', models.FloatField(null=True, blank=True)),
                ('batt_kwh_max', models.FloatField(null=True, blank=True)),
                ('batt_kwh_min', models.FloatField(null=True, blank=True)),
                ('batt_efficiency', models.FloatField(null=True, blank=True)),
                ('batt_inverter_efficiency', models.FloatField(null=True, blank=True)),
                ('batt_rectifier_efficiency', models.FloatField(null=True, blank=True)),
                ('batt_soc_min', models.FloatField(null=True, blank=True)),
                ('batt_soc_init', models.FloatField(null=True, blank=True)),
                ('batt_can_gridcharge', models.FloatField(null=True, blank=True)),
                ('batt_itc_federal', models.FloatField(null=True, blank=True)),
                ('batt_itc_state', models.FloatField(null=True, blank=True)),
                ('batt_itc_utility', models.FloatField(null=True, blank=True)),
                ('batt_itc_federal_max', models.FloatField(null=True, blank=True)),
                ('batt_itc_state_max', models.FloatField(null=True, blank=True)),
                ('batt_itc_utility_max', models.FloatField(null=True, blank=True)),
                ('batt_rebate_federal', models.FloatField(null=True, blank=True)),
                ('batt_rebate_state', models.FloatField(null=True, blank=True)),
                ('batt_rebate_utility', models.FloatField(null=True, blank=True)),
                ('batt_rebate_federal_max', models.FloatField(null=True, blank=True)),
                ('batt_rebate_state_max', models.FloatField(null=True, blank=True)),
                ('batt_rebate_utility_max', models.FloatField(null=True, blank=True)),
                ('batt_macrs_schedule', models.IntegerField(null=True, blank=True)),
                ('batt_macrs_bonus_fraction', models.FloatField(null=True, blank=True)),
                ('batt_macrs_itc_reduction', models.FloatField(null=True, blank=True)),
                ('outage_start', models.IntegerField(null=True, blank=True)),
                ('outage_end', models.IntegerField(null=True, blank=True)),
                ('crit_load_factor', models.FloatField(null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunOutput',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('run_input_id', models.IntegerField()),
                ('user_id', models.TextField(default=b'', null=True, blank=True)),
                ('api_version', models.TextField(default=b'', blank=True)),
                ('timeout', models.IntegerField(default=295, null=True, blank=True)),
                ('time_steps_per_hour', models.IntegerField(null=True, blank=True)),
                ('latitude', models.FloatField(null=True, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('land_area', models.FloatField(null=True, blank=True)),
                ('roof_area', models.FloatField(null=True, blank=True)),
                ('urdb_rate', picklefield.fields.PickledObjectField(null=True, editable=False)),
                ('load_profile_name', models.TextField(default=b'', null=True, blank=True)),
                ('load_size', models.FloatField(null=True, blank=True)),
                ('load_year', models.IntegerField(default=2018, null=True, blank=True)),
                ('load_8760_kw', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('load_monthly_kwh', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('utility_name', models.TextField(default=b'', blank=True)),
                ('rate_name', models.TextField(default=b'', blank=True)),
                ('blended_utility_rate', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('demand_charge', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('pv_kw_ac_hourly', django.contrib.postgres.fields.ArrayField(default=[], null=True, base_field=models.FloatField(blank=True), size=None, blank=True)),
                ('analysis_period', models.IntegerField(null=True, blank=True)),
                ('offtaker_discount_rate', models.FloatField(null=True, blank=True)),
                ('offtaker_tax_rate', models.FloatField(null=True, blank=True)),
                ('owner_discount_rate', models.FloatField(null=True, blank=True)),
                ('owner_tax_rate', models.FloatField(null=True, blank=True)),
                ('rate_escalation', models.FloatField(null=True, blank=True)),
                ('rate_inflation', models.FloatField(null=True, blank=True)),
                ('net_metering_limit', models.FloatField(null=True, blank=True)),
                ('wholesale_rate', models.FloatField(null=True, blank=True)),
                ('interconnection_limit', models.FloatField(null=True, blank=True)),
                ('pv_cost', models.FloatField(null=True, blank=True)),
                ('pv_om', models.FloatField(null=True, blank=True)),
                ('pv_kw_max', models.FloatField(null=True, blank=True)),
                ('pv_kw_min', models.FloatField(null=True, blank=True)),
                ('module_type', models.IntegerField(null=True, blank=True)),
                ('azimuth', models.FloatField(null=True, blank=True)),
                ('losses', models.FloatField(null=True, blank=True)),
                ('dc_ac_ratio', models.FloatField(null=True, blank=True)),
                ('gcr', models.FloatField(null=True, blank=True)),
                ('dataset', models.TextField(default=b'', blank=True)),
                ('inv_eff', models.FloatField(null=True, blank=True)),
                ('system_capacity', models.FloatField(null=True, blank=True)),
                ('array_type', models.IntegerField(null=True, blank=True)),
                ('timeframe', models.TextField(default=b'', blank=True)),
                ('radius', models.FloatField(null=True, blank=True)),
                ('tilt', models.FloatField(null=True, blank=True)),
                ('pv_degradation_rate', models.FloatField(null=True, blank=True)),
                ('pv_itc_federal', models.FloatField(null=True, blank=True)),
                ('pv_itc_state', models.FloatField(null=True, blank=True)),
                ('pv_itc_utility', models.FloatField(null=True, blank=True)),
                ('pv_itc_federal_max', models.FloatField(null=True, blank=True)),
                ('pv_itc_state_max', models.FloatField(null=True, blank=True)),
                ('pv_itc_utility_max', models.FloatField(null=True, blank=True)),
                ('pv_rebate_federal', models.FloatField(null=True, blank=True)),
                ('pv_rebate_state', models.FloatField(null=True, blank=True)),
                ('pv_rebate_utility', models.FloatField(null=True, blank=True)),
                ('pv_rebate_federal_max', models.FloatField(null=True, blank=True)),
                ('pv_rebate_state_max', models.FloatField(null=True, blank=True)),
                ('pv_rebate_utility_max', models.FloatField(null=True, blank=True)),
                ('pv_pbi', models.FloatField(null=True, blank=True)),
                ('pv_pbi_max', models.FloatField(null=True, blank=True)),
                ('pv_pbi_years', models.FloatField(null=True, blank=True)),
                ('pv_pbi_system_max', models.FloatField(null=True, blank=True)),
                ('pv_macrs_schedule', models.IntegerField(null=True, blank=True)),
                ('pv_macrs_bonus_fraction', models.FloatField(null=True, blank=True)),
                ('batt_cost_kwh', models.FloatField(null=True, blank=True)),
                ('batt_cost_kw', models.FloatField(null=True, blank=True)),
                ('batt_replacement_cost_kw', models.FloatField(null=True, blank=True)),
                ('batt_replacement_cost_kwh', models.FloatField(null=True, blank=True)),
                ('batt_replacement_year_kw', models.IntegerField(null=True, blank=True)),
                ('batt_replacement_year_kwh', models.IntegerField(null=True, blank=True)),
                ('batt_kw_max', models.FloatField(null=True, blank=True)),
                ('batt_kw_min', models.FloatField(null=True, blank=True)),
                ('batt_kwh_max', models.FloatField(null=True, blank=True)),
                ('batt_kwh_min', models.FloatField(null=True, blank=True)),
                ('batt_efficiency', models.FloatField(null=True, blank=True)),
                ('batt_inverter_efficiency', models.FloatField(null=True, blank=True)),
                ('batt_rectifier_efficiency', models.FloatField(null=True, blank=True)),
                ('batt_soc_min', models.FloatField(null=True, blank=True)),
                ('batt_soc_init', models.FloatField(null=True, blank=True)),
                ('batt_can_gridcharge', models.FloatField(null=True, blank=True)),
                ('batt_itc_federal', models.FloatField(null=True, blank=True)),
                ('batt_itc_state', models.FloatField(null=True, blank=True)),
                ('batt_itc_utility', models.FloatField(null=True, blank=True)),
                ('batt_itc_federal_max', models.FloatField(null=True, blank=True)),
                ('batt_itc_state_max', models.FloatField(null=True, blank=True)),
                ('batt_itc_utility_max', models.FloatField(null=True, blank=True)),
                ('batt_rebate_federal', models.FloatField(null=True, blank=True)),
                ('batt_rebate_state', models.FloatField(null=True, blank=True)),
                ('batt_rebate_utility', models.FloatField(null=True, blank=True)),
                ('batt_rebate_federal_max', models.FloatField(null=True, blank=True)),
                ('batt_rebate_state_max', models.FloatField(null=True, blank=True)),
                ('batt_rebate_utility_max', models.FloatField(null=True, blank=True)),
                ('batt_macrs_schedule', models.IntegerField(null=True, blank=True)),
                ('batt_macrs_bonus_fraction', models.FloatField(null=True, blank=True)),
                ('batt_macrs_itc_reduction', models.FloatField(null=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(null=True, blank=True)),
                ('lcc', models.FloatField(null=True, blank=True)),
                ('lcc_bau', models.FloatField(null=True, blank=True)),
                ('npv', models.FloatField(null=True, blank=True)),
                ('irr', models.FloatField(null=True, blank=True)),
                ('year_one_utility_kwh', models.FloatField(null=True, blank=True)),
                ('pv_kw', models.FloatField(null=True, blank=True)),
                ('batt_kw', models.FloatField(null=True, blank=True)),
                ('batt_kwh', models.FloatField(null=True, blank=True)),
                ('year_one_energy_cost', models.FloatField(null=True, blank=True)),
                ('year_one_demand_cost', models.FloatField(null=True, blank=True)),
                ('year_one_energy_cost_bau', models.FloatField(null=True, blank=True)),
                ('year_one_demand_cost_bau', models.FloatField(null=True, blank=True)),
                ('year_one_payments_to_third_party_owner', models.FloatField(null=True, blank=True)),
                ('total_energy_cost', models.FloatField(null=True, blank=True)),
                ('total_demand_cost', models.FloatField(null=True, blank=True)),
                ('total_energy_cost_bau', models.FloatField(null=True, blank=True)),
                ('total_demand_cost_bau', models.FloatField(null=True, blank=True)),
                ('total_payments_to_third_party_owner', models.FloatField(null=True, blank=True)),
                ('net_capital_costs_plus_om', models.FloatField(null=True, blank=True)),
                ('average_yearly_pv_energy_produced', models.FloatField(null=True, blank=True)),
                ('year_one_electric_load_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_pv_to_battery_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_pv_to_load_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_pv_to_grid_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_grid_to_load_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_grid_to_battery_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_battery_to_load_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_battery_to_grid_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_battery_soc_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_energy_cost_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_demand_cost_series', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('year_one_datetime_start', models.DateTimeField(null=True, blank=True)),
                ('resilience_by_timestep', django.contrib.postgres.fields.ArrayField(size=None, null=True, base_field=models.FloatField(null=True, blank=True), blank=True)),
                ('resilience_hours_min', models.FloatField(null=True, blank=True)),
                ('resilience_hours_max', models.FloatField(null=True, blank=True)),
                ('resilience_hours_avg', models.FloatField(null=True, blank=True)),
                ('outage_start', models.IntegerField(null=True, blank=True)),
                ('outage_end', models.IntegerField(null=True, blank=True)),
                ('crit_load_factor', models.FloatField(null=True, blank=True)),
            ],
        ),
    ]
