# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runoutput',
            old_name='r_list',
            new_name='resilience_by_timestep',
        ),
        migrations.RenameField(
            model_name='runoutput',
            old_name='r_avg',
            new_name='resilience_hours_avg',
        ),
        migrations.RenameField(
            model_name='runoutput',
            old_name='r_max',
            new_name='resilience_hours_max',
        ),
        migrations.RenameField(
            model_name='runoutput',
            old_name='r_min',
            new_name='resilience_hours_min',
        ),
    ]
