# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='scenario_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reo.ScenarioModel', to_field=b'run_uuid'),
        ),
    ]
