# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0002_runoutput_average_annual_energy_exported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runoutput',
            name='batt_kw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='batt_kwh',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='pv_kw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
