# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0003_auto_20170718_1734'),
        ('reo', '0004_auto_20170714_2008'),
    ]

    operations = [
    ]
