# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reo', '0006_auto_20170718_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runinput',
            name='user_id',
        ),
        migrations.AddField(
            model_name='runinput',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
