# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0010_auto_20170822_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='URDBError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, default=b'')),
                ('type', models.TextField(blank=True, default=b'')),
                ('message', models.TextField(blank=True, default=b'')),
            ],
        ),
    ]
