# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0025_auto_20170530_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='runoutput',
            name='pv_resource',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=[], null=True, size=None),
        )
    ]
