# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0026_auto_20170613_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runoutput',
            old_name='pv_resource',
            new_name='prod_factor',
        )
    ]
