# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 20:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0027_auto_20170613_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinput',
            name='blended_utility_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runinput',
            name='demand_charge',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runinput',
            name='load_8760_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runinput',
            name='load_monthly_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='blended_utility_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='demand_charge',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='load_8760_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='load_monthly_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='prod_factor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=[], null=True, size=None),
        ),
    ]
