# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0028_auto_20170614_2047'),
        ('reo', '0025_merge'),
    ]

    operations = [
    ]
