# *********************************************************************************
# REopt, Copyright (c) 2019-2020, Alliance for Sustainable Energy, LLC.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this list
# of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice, this
# list of conditions and the following disclaimer in the documentation and/or other
# materials provided with the distribution.
#
# Neither the name of the copyright holder nor the names of its contributors may be
# used to endorse or promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
# *********************************************************************************
# Generated by Django 2.2.6 on 2019-10-30 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0048_alter_wholesale_rates_array_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='blended_monthly_demand_charges_us_dollars_per_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='blended_monthly_rates_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_label',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_rate_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_utility_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='wholesale_rate_above_site_load_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[0]), size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='wholesale_rate_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[0]), size=None),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='run_uuid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='task',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='traceback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='user_uuid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='critical_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='critical_loads_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='doe_reference_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='loads_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='monthly_totals_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='year_one_electric_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='api_version',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='label',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='size_class',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
