# REopt®, Copyright (c) Alliance for Sustainable Energy, LLC. See also https://github.com/NREL/REopt_API/blob/master/LICENSE.
# Generated by Django 2.2.6 on 2019-10-30 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0048_alter_wholesale_rates_array_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='blended_monthly_demand_charges_us_dollars_per_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='blended_monthly_rates_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_label',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_rate_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_utility_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='wholesale_rate_above_site_load_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[0]), size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='wholesale_rate_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=[0]), size=None),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='run_uuid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='task',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='traceback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='user_uuid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='critical_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='critical_loads_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='doe_reference_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='loads_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='monthly_totals_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='year_one_electric_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='api_version',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='label',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='size_class',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
