# *********************************************************************************
# REopt, Copyright (c) 2019-2020, Alliance for Sustainable Energy, LLC.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this list
# of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice, this
# list of conditions and the following disclaimer in the documentation and/or other
# materials provided with the distribution.
#
# Neither the name of the copyright holder nor the names of its contributors may be
# used to endorse or promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
# *********************************************************************************
# Generated by Django 2.2.6 on 2019-10-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0052_auto_20191030_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='parse_run_outputs_seconds2',
            new_name='parse_run_outputs_seconds',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='pre_setup_scenario_seconds2',
            new_name='pre_setup_scenario_seconds',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='reopt_bau_seconds2',
            new_name='reopt_bau_seconds',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='reopt_seconds2',
            new_name='reopt_seconds',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='setup_scenario_seconds2',
            new_name='setup_scenario_seconds',
        ),
    ]
