# REopt®, Copyright (c) Alliance for Sustainable Energy, LLC. See also https://github.com/NREL/REopt_API/blob/master/LICENSE.
# Generated by Django 2.2.6 on 2019-12-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0053_auto_20191030_1817'),
        ('reo', '0052_financialmodel_net_om_us_dollars_bau'),
    ]

    operations = [
    ]
