# Generated by Django 2.2.6 on 2020-04-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0054_merge_20191204_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='owner_discount_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='owner_tax_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='two_party_ownership',
            field=models.BooleanField(default=False),
        ),
    ]
