# Generated by Django 2.2.6 on 2020-04-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0054_merge_20191204_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodel',
            name='location',
            field=models.TextField(blank=True, default='both', null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='pv_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='pv_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='run_uuid',
            field=models.UUIDField(),
        ),
    ]
