# Generated by Django 2.2.6 on 2020-04-10 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0054_merge_20191204_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodel',
            name='prod_factor_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='prod_factor_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
    ]
