# Generated by Django 2.2.6 on 2020-04-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0054_merge_20191204_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='initial_capital_costs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='initial_capital_costs_after_incentives',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='replacement_costs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
