# Generated by Django 2.2.6 on 2019-12-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0054_merge_20191204_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='solver',
            field=models.TextField(default='Xpress'),
        ),
    ]
