# Generated by Django 2.2.6 on 2020-04-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0055_auto_20200410_2245'),
        ('reo', '0055_auto_20200409_2129'),
    ]

    operations = [
    ]
