# Generated by Django 2.2.6 on 2020-04-27 19:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0056_merge_20200416_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='add_tou_energy_rates_to_urdb_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='tou_energy_rates_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
    ]
