# Generated by Django 2.2.6 on 2020-04-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0056_merge_20200416_2240'),
        ('reo', '0055_auto_20200410_1911'),
    ]

    operations = [
    ]
