# Generated by Django 2.2.6 on 2020-04-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0057_auto_20200427_1900'),
        ('reo', '0057_merge_20200427_2324'),
    ]

    operations = [
    ]
