# Generated by Django 2.2.6 on 2020-04-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0057_auto_20200427_1900'),
        ('reo', '0055_auto_20200416_1645'),
    ]

    operations = [
    ]
