# Generated by Django 2.2.6 on 2020-05-06 22:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0057_auto_20200427_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='owner_discount_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='owner_tax_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='two_party_ownership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='total_fixed_om_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_fixed_om_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        )
    ]
