# Generated by Django 2.2.10 on 2020-05-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0057_auto_20200427_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatormodel',
            name='total_fixed_om_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_fixed_om_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
