# Generated by Django 2.2.10 on 2020-06-03 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0058_auto_20200529_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodel',
            name='prod_factor_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='prod_factor_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
    ]
