# Generated by Django 2.2.6 on 2020-04-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0058_auto_20200224_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatormodel',
            name='total_fixed_om_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_fixed_om_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
