# Generated by Django 2.2.6 on 2020-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0058_auto_20200506_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_export_benefit_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_export_benefit_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='year_one_energy_produced_bau_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
