# Generated by Django 2.2.6 on 2020-05-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0059_auto_20200508_2218'),
        ('reo', '0058_merge_20200428_0302'),
    ]

    operations = [
    ]
