# Generated by Django 2.2.10 on 2020-06-03 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0060_two_party_finance_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_export_benefit_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_export_benefit_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
