# Generated by Django 2.2.6 on 2020-05-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0060_merge_20200519_1928'),
        ('reo', '0060_pvmodel_year_one_curtailed_production_series_kw'),
    ]

    operations = [
    ]
