# Generated by Django 2.2.10 on 2020-06-03 18:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0061_bau_export_benefit_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodel',
            name='year_one_curtailed_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='year_one_energy_produced_bau_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
