# Generated by Django 2.2.6 on 2020-04-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0062_pvmodel_year_one_energy_produced_bau_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_export_benefit_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_export_benefit_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
