# Generated by Django 2.2.6 on 2020-05-21 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0062_alter_table_reo_loadprofile_model_annual_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprofilemodel',
            name='percent_share',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='annual_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        )
    ]
