# Generated by Django 2.2.10 on 2020-06-16 17:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0063_auto_20200521_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='julia_input_construction_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_input_construction_seconds_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_constriants_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_constriants_seconds_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_optimize_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_optimize_seconds_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_postprocess_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_postprocess_seconds_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_preamble_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_preamble_seconds_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_variables_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='julia_reopt_variables_seconds_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='doe_reference_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=list, size=None),
        ),
    ]
