# Generated by Django 2.2.6 on 2020-04-25 15:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0063_auto_20200420_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='add_tou_energy_rates_to_urdb_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='tou_energy_rates_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
    ]
