# Generated by Django 2.2.10 on 2020-06-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0065_auto_20200616_1810'),
        ('reo', '0064_auto_20200612_0437'),
    ]

    operations = [
    ]
