# Generated by Django 2.2.10 on 2020-07-01 18:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0066_merge_20200619_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpmodel',
            name='year_one_thermal_to_waste_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
