# Generated by Django 2.2.10 on 2020-07-07 02:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0066_auto_20200707_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_to_load_series_bau_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
