# Generated by Django 2.2.10 on 2020-07-01 21:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0067_chpmodel_year_one_thermal_to_waste_series_mmbtu_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_thermal_to_load_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_thermal_to_tes_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
