# Generated by Django 2.2.10 on 2020-07-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0068_auto_20200701_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='optimality_tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
