# Generated by Django 2.2.10 on 2020-07-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0068_auto_20200708_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='emissions_region',
            field=models.TextField(blank=True, null=True),
        ),
    ]
