# Generated by Django 2.2.10 on 2020-07-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0069_electrictariffmodel_emissions_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='irr_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
