# Generated by Django 2.2.10 on 2020-07-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0070_auto_20200715_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_boiler_thermal_production_bau_mmbtu',
        ),
        migrations.RemoveField(
            model_name='electricchillermodel',
            name='year_one_electric_chiller_thermal_production_bau_tonhr',
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='max_thermal_factor_on_peak_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electricchillermodel',
            name='max_thermal_factor_on_peak_load',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
