# Generated by Django 2.2.10 on 2020-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0070_financialmodel_irr_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='emissions_reduction_accounting_method',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='emissions_reduction_max_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='emissions_reduction_min_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='renewable_generation_accounting_method',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='renewable_generation_max_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='renewable_generation_min_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
