# Generated by Django 2.2.10 on 2020-09-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0071_windmodel_year_one_curtailed_production_series_kw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmodel',
            old_name='two_party_ownership',
            new_name='third_party_ownership',
        ),
    ]
