# Generated by Django 2.2.10 on 2020-07-24 18:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0071_auto_20200722_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='outdoor_air_temp_degF',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
