# Generated by Django 2.2.10 on 2020-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0071_auto_20200727_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='renewable_electricity_energy_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
