# Generated by Django 2.2.10 on 2020-08-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0072_sitemodel_renewable_electricity_energy_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='optimality_gap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
