# Generated by Django 2.2.10 on 2020-09-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0072_auto_20200929_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='net_present_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
