# Generated by Django 2.2.10 on 2020-08-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0071_windmodel_year_one_curtailed_production_series_kw'),
        ('reo', '0073_auto_20200818_2200'),
    ]

    operations = [
    ]
