# Generated by Django 2.2.10 on 2020-07-24 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0073_auto_20200724_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='year_one_to_load_bau_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='year_one_electric_load_series_kw_bau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
    ]
