# Generated by Django 2.2.10 on 2020-09-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0073_financialmodel_net_present_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='annualized_payment_to_third_party_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
