# Generated by Django 2.2.13 on 2020-08-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0074_merge_20200821_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadprofilemodel',
            name='year_one_electric_load_series_kw_bau',
        ),
    ]
