# Generated by Django 2.2.13 on 2020-12-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0074_financialmodel_annualized_payment_to_third_party_us_dollars'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprofilemodel',
            name='outage_end_time_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadprofilemodel',
            name='outage_start_time_step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
