# Generated by Django 2.2.13 on 2020-12-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0074_financialmodel_annualized_payment_to_third_party_us_dollars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadprofilemodel',
            old_name='outage_end_hour',
            new_name='outage_end_time_step',
        ),
        migrations.RenameField(
            model_name='loadprofilemodel',
            old_name='outage_start_hour',
            new_name='outage_start_time_step',
        ),
        migrations.AddField(
            model_name='loadprofilemodel',
            name='bau_sustained_time_steps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
