# Generated by Django 2.2.10 on 2020-11-25 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0074_financialmodel_annualized_payment_to_third_party_us_dollars'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='developer_annual_free_cashflow_series_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='offtaker_annual_free_cashflow_series_bau_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='offtaker_annual_free_cashflow_series_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='offtaker_discounted_annual_free_cashflow_series_bau_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='offtaker_discounted_annual_free_cashflow_series_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
