# Generated by Django 2.2.10 on 2020-07-24 19:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0074_auto_20200724_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='emissions_factor_series_lb_CO2_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
    ]
