# Generated by Django 2.2.10 on 2020-12-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0075_auto_20201125_1947'),
        ('reo', '0072_auto_20200925_0417'),
    ]

    operations = [
    ]
