# Generated by Django 2.2.10 on 2020-07-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0070_financialmodel_irr_pct'),
        ('reo', '0075_auto_20200724_1925'),
    ]

    operations = [
    ]
