# Generated by Django 2.2.13 on 2020-09-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0075_remove_loadprofilemodel_year_one_electric_load_series_kw_bau'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenariomodel',
            old_name='optimality_tolerance',
            new_name='optimality_tolerance_bau',
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='optimality_tolerance_decomp_subproblem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='optimality_tolerance_techs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='use_decomposition_model',
            field=models.BooleanField(default=False),
        ),
    ]
