# Generated by Django 2.2.13 on 2020-12-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0076_merge_20201210_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatormodel',
            name='can_curtail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='can_net_meter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='can_wholesale',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='can_curtail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='can_net_meter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='can_wholesale',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='can_curtail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='can_net_meter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='can_wholesale',
            field=models.BooleanField(null=True),
        ),
    ]
