# Generated by Django 2.2.10 on 2021-01-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0077_auto_20201210_2229'),
        ('reo', '0076_merge_20201208_2014'),
    ]

    operations = [
    ]
