# Generated by Django 2.2.13 on 2021-01-19 23:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0077_auto_20201210_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='ra_demand_pricing_us_dollars_per_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='ra_energy_pricing_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='ra_event_day_flags_boolean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='ra_lookback_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_demand_response_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_demand_response_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
