# Generated by Django 2.2.10 on 2020-12-29 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0077_auto_20201210_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='coincident_peak_load_active_timesteps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='coincident_peak_load_charge_us_dollars_per_kw',
            field=models.FloatField(null=True),
        ),
    ]
