# Generated by Django 2.2.10 on 2021-01-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0077_auto_20201210_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemodel',
            name='soc_max_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
