# Generated by Django 2.2.13 on 2020-09-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0077_scenariomodel_timeout_decomp_subproblem_seconds'),
        ('reo', '0076_cost_curve'),
    ]

    operations = [
    ]
