# Generated by Django 2.2.13 on 2021-01-19 10:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0077_auto_20201210_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='contract_quantities_series_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='contract_rates_series_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='real_time_market_rates_series_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_contract_energy_cost_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_contract_energy_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_contract_excess_deficit_energy_cost_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_contract_excess_deficit_energy_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
