# Generated by Django 2.2.13 on 2021-02-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0078_auto_20210119_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodel',
            name='pv_ppa_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
