# Generated by Django 2.2.13 on 2020-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0076_auto_20200916_1556'),
        ('reo', '0078_cost_curve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariomodel',
            name='use_decomposition_model',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
