# Generated by Django 2.2.13 on 2020-10-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0079_auto_20200925_2116'),
        ('reo', '0074_financialmodel_annualized_payment_to_third_party_us_dollars'),
    ]

    operations = [
    ]
