# Generated by Django 2.2.13 on 2020-10-20 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0080_merge_20201001_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexTechACModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('existing_kw', models.FloatField(blank=True, default=0, null=True)),
                ('min_kw', models.FloatField(blank=True, default=0, null=True)),
                ('max_kw', models.FloatField(blank=True, default=0, null=True)),
                ('installed_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('om_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('prod_factor_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('operating_penalty_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('year_one_power_production_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FlexTechHPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('existing_kw', models.FloatField(blank=True, default=0, null=True)),
                ('min_kw', models.FloatField(blank=True, default=0, null=True)),
                ('max_kw', models.FloatField(blank=True, default=0, null=True)),
                ('installed_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('om_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('prod_factor_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('operating_penalty_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('year_one_power_production_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RCModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('use_flexloads_model', models.BooleanField(default=False)),
                ('a_matrix', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('b_matrix', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('u_inputs', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('space_node', models.IntegerField(blank=True, null=True)),
                ('temperatures_degree_C', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
