# Generated by Django 2.2.13 on 2020-11-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0080_merge_20201001_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='chp_allowed_to_export',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
