# Generated by Django 2.2.13 on 2020-11-25 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0081_electrictariffmodel_chp_allowed_to_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpmodel',
            name='chp_unavailability_hourly',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
