# Generated by Django 2.2.13 on 2020-12-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0075_auto_20201125_1947'),
        ('reo', '0082_chpmodel_chp_unavailability_hourly'),
    ]

    operations = [
    ]
