# Generated by Django 2.2.13 on 2020-10-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0082_auto_20201022_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcmodel',
            name='n_input_nodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='n_temp_nodes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
