# Generated by Django 2.2.13 on 2020-12-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0083_merge_20201207_1317'),
    ]

    operations = [
    	migrations.RenameModel('LoadProfileChillerElectricModel', 'LoadProfileChillerThermalModel')
    ]
