# Generated by Django 2.2.13 on 2020-12-15 17:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0083_merge_20201207_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='absorptionchillermodel',
            name='chiller_elec_cop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absorptionchillermodel',
            name='year_one_absorp_chl_electric_consumption_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absorptionchillermodel',
            name='year_one_absorp_chl_electric_consumption_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
