# Generated by Django 2.2.13 on 2020-10-23 21:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0083_auto_20201023_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcmodel',
            name='init_temperatures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
