# Generated by Django 2.2.13 on 2020-12-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0077_auto_20201210_2229'),
        ('reo', '0083_merge_20201207_1317'),
    ]

    operations = [
    ]
