# Generated by Django 2.2.13 on 2020-12-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0084_merge_20201219_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='chp_allowed_to_export',
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='can_curtail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='can_net_meter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='can_wholesale',
            field=models.BooleanField(null=True),
        ),
    ]
