# Generated by Django 2.2.10 on 2020-12-17 23:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0084_rename_chiller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absorptionchillermodel',
            name='chiller_cop',
        ),
        migrations.RemoveField(
            model_name='electricchillermodel',
            name='chiller_cop',
        ),
        migrations.AddField(
            model_name='loadprofilechillerthermalmodel',
            name='annual_tonhour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='loadprofilechillerthermalmodel',
            name='cop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadprofilechillerthermalmodel',
            name='loads_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='loadprofilechillerthermalmodel',
            name='monthly_tonhour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, size=None),
        ),
    ]
