# Generated by Django 2.2.13 on 2020-10-29 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0084_rcmodel_init_temperatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='flextechacmodel',
            name='year_one_power_consumption_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='flextechhpmodel',
            name='year_one_power_consumption_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
