# Generated by Django 2.2.13 on 2020-12-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0085_auto_20201219_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='year_one_opex_costs_before_tax_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
