# Generated by Django 2.2.13 on 2020-12-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0085_auto_20201219_2026'),
        ('reo', '0084_merge_20201208_1636'),
    ]

    operations = [
    ]
