# Generated by Django 2.2.13 on 2020-11-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0085_auto_20201029_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcmodel',
            name='injection_node',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='temperature_lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='temperature_upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
