# Generated by Django 2.2.13 on 2020-12-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0085_auto_20201219_2026'),
        ('reo', '0084_auto_20201215_1743'),
    ]

    operations = [
    ]
