# Generated by Django 2.2.13 on 2020-12-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0086_auto_20201110_1618'),
    ]

    operations = [
    ]
