# Generated by Django 2.2.13 on 2020-12-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0086_financialmodel_year_one_opex_costs_before_tax_us_dollars'),
        ('reo', '0086_merge_20201228_1949'),
    ]

    operations = [
    ]
