# Generated by Django 2.2.13 on 2020-12-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0086_merge_20201223_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuclearmodel',
            name='can_curtail',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nuclearmodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nuclearmodel',
            name='can_net_meter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='nuclearmodel',
            name='can_wholesale',
            field=models.BooleanField(null=True),
        ),
    ]
