# Generated by Django 2.2.13 on 2020-12-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0087_merge_20201228_2004'),
        ('reo', '0087_auto_20201223_2127'),
    ]

    operations = [
    ]
