# Generated by Django 2.2.13 on 2020-12-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0087_auto_20201204_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flextechacmodel',
            old_name='crankcase_power_kW',
            new_name='crankcase_power_kw',
        ),
    ]
