# Generated by Django 2.2.13 on 2020-12-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0087_auto_20201218_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadprofilechillerthermalmodel',
            old_name='cop',
            new_name='chiller_cop',
        ),
    ]
