# Generated by Django 2.2.13 on 2020-12-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0085_auto_20201219_2026'),
        ('reo', '0088_auto_20201221_2230'),
    ]

    operations = [
    ]
