# Generated by Django 2.2.13 on 2020-12-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0088_auto_20201204_1540'),
        ('reo', '0087_merge_20201213_1837'),
    ]

    operations = [
    ]
