# Generated by Django 2.2.13 on 2020-12-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0089_merge_20201221_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='absorptionchillermodel',
            name='chiller_cop',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
