# Generated by Django 2.2.13 on 2020-12-16 18:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0089_merge_20201213_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcmodel',
            name='shr',
        ),
        migrations.AddField(
            model_name='flextechacmodel',
            name='shr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
