# Generated by Django 2.2.13 on 2020-12-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0090_absorptionchillermodel_chiller_cop'),
        ('reo', '0087_merge_20201228_2004'),
    ]

    operations = [
    ]
