# Generated by Django 2.2.13 on 2020-12-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0091_flextechwhmodel_hotwatertankmodel_loadprofilewaterheatermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadprofilewaterheatermodel',
            old_name='loads_GPH',
            new_name='loads_gal',
        ),
    ]
