# Generated by Django 2.2.13 on 2020-12-31 19:16

import django.contrib.postgres.fields
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0091_merge_20201228_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chpmodel',
            name='chp_unavailability_hourly',
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='chp_unavailability_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), default=list, null=True, size=None),
        ),
    ]
