# Generated by Django 2.2.13 on 2020-12-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0092_auto_20201217_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotwatertankmodel',
            old_name='max_size_gal',
            new_name='max_gal',
        ),
        migrations.RenameField(
            model_name='hotwatertankmodel',
            old_name='min_size_gal',
            new_name='min_gal',
        ),
    ]
