# Generated by Django 2.2.13 on 2021-01-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0093_remove_absorptionchillermodel_macrs_itc_reduction'),
        ('reo', '0092_auto_20201231_1916'),
    ]

    operations = [
    ]
