# Generated by Django 2.2.13 on 2020-12-18 00:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0093_auto_20201217_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprofilewaterheatermodel',
            name='annual_calculated_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadprofilewaterheatermodel',
            name='year_one_water_load_series_gal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
