# Generated by Django 2.2.13 on 2021-01-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0094_merge_20210105_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpmodel',
            name='cooling_thermal_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
