# Generated by Django 2.2.13 on 2021-01-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0094_merge_20210105_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='add_soc_incentive',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
