# Generated by Django 2.2.13 on 2021-01-15 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0095_scenariomodel_add_soc_incentive'),
        ('reo', '0095_chpmodel_cooling_thermal_factor'),
    ]

    operations = [
    ]
