# Generated by Django 2.2.13 on 2020-12-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0095_auto_20201221_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='flextechwhmodel',
            name='use_wh_model',
            field=models.BooleanField(default=False),
        ),
    ]
