# Generated by Django 2.2.13 on 2020-12-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0096_flextechwhmodel_use_wh_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadProfileWaterHeaterModel',
        ),
    ]
