# Generated by Django 2.2.13 on 2021-01-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0096_remove_loadprofileboilerfuelmodel_year_one_boiler_fuel_load_series_mmbtu_per_hr_bau'),
        ('reo', '0096_merge_20210115_0019'),
    ]

    operations = [
    ]
