# Generated by Django 2.2.10 on 2021-01-15 23:40

import django.contrib.postgres.fields
from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0097_merge_20210115_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absorptionchillermodel',
            name='min_ton',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absorptionchillermodel',
            name='year_one_absorp_chl_electric_consumption_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='absorptionchillermodel',
            name='year_one_absorp_chl_thermal_consumption_series_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=list, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='absorptionchillermodel',
            name='year_one_absorp_chl_thermal_to_load_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='absorptionchillermodel',
            name='year_one_absorp_chl_thermal_to_tes_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='badpost',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badpost',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='existing_boiler_production_type_steam_or_hw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='installed_cost_us_dollars_per_mmbtu_per_hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='min_mmbtu_per_hr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='year_one_boiler_fuel_consumption_series_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='year_one_boiler_thermal_production_series_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='year_one_thermal_to_load_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='year_one_thermal_to_tes_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='can_curtail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='can_net_meter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='can_wholesale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='chp_unavailability_periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='installed_cost_us_dollars_per_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='prime_mover',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='tech_size_for_cost_curve',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='year_one_electric_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='year_one_thermal_to_load_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='year_one_thermal_to_tes_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='year_one_thermal_to_waste_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='year_one_to_battery_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='year_one_to_grid_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chpmodel',
            name='year_one_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='installed_cost_us_dollars_per_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='internal_efficiency_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='macrs_bonus_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='max_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='min_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='om_cost_us_dollars_per_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='soc_init_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='soc_min_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='thermal_decay_rate_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='year_one_cold_tes_soc_series_pct',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='coldtesmodel',
            name='year_one_thermal_from_cold_tes_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electricchillermodel',
            name='installed_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricchillermodel',
            name='min_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricchillermodel',
            name='year_one_electric_chiller_electric_consumption_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electricchillermodel',
            name='year_one_electric_chiller_thermal_to_load_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electricchillermodel',
            name='year_one_electric_chiller_thermal_to_tes_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='add_tou_energy_rates_to_urdb_rate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='blended_monthly_demand_charges_us_dollars_per_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='blended_monthly_rates_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='emissions_factor_series_lb_CO2_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='interconnection_limit_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='net_metering_limit_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='tou_energy_rates_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_rate_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='urdb_utility_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='wholesale_rate_above_site_load_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=list, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='wholesale_rate_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='year_one_demand_cost_series_us_dollars_per_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='year_one_energy_cost_series_us_dollars_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='year_one_to_battery_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='year_one_to_load_series_bau_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='year_one_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='run_uuid',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='task',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='traceback',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='errormodel',
            name='user_uuid',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='analysis_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='developer_annual_free_cashflow_series_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='escalation_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='offtaker_annual_free_cashflow_series_bau_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='offtaker_annual_free_cashflow_series_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='offtaker_discount_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='offtaker_discounted_annual_free_cashflow_series_bau_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='offtaker_discounted_annual_free_cashflow_series_us_dollars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='offtaker_tax_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='om_cost_escalation_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialmodel',
            name='third_party_ownership',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fueltariffmodel',
            name='boiler_fuel_blended_monthly_rates_us_dollars_per_mmbtu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fueltariffmodel',
            name='chp_fuel_blended_monthly_rates_us_dollars_per_mmbtu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fueltariffmodel',
            name='chp_fuel_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fueltariffmodel',
            name='existing_boiler_fuel_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='can_curtail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='can_net_meter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='can_wholesale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='existing_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='generator_only_runs_during_grid_outage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='generator_sells_energy_back_to_grid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='min_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='year_one_power_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='year_one_to_grid_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='year_one_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='installed_cost_us_dollars_per_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='internal_efficiency_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='macrs_bonus_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='max_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='min_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='om_cost_us_dollars_per_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='soc_init_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='soc_min_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='thermal_decay_rate_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='year_one_hot_tes_soc_series_pct',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='hottesmodel',
            name='year_one_thermal_from_hot_tes_series_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofileboilerfuelmodel',
            name='doe_reference_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofileboilerfuelmodel',
            name='loads_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofileboilerfuelmodel',
            name='monthly_mmbtu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofileboilerfuelmodel',
            name='percent_share',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofileboilerfuelmodel',
            name='year_one_boiler_fuel_load_series_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofileboilerfuelmodel',
            name='year_one_boiler_thermal_load_series_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='annual_calculated_kwh_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='doe_reference_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='loads_fraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='loads_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='monthly_fraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='monthly_tonhour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='percent_share',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='year_one_chiller_electric_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='year_one_chiller_electric_load_series_kw_bau',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilechillerthermalmodel',
            name='year_one_chiller_thermal_load_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='critical_load_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='critical_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='critical_loads_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='critical_loads_kw_is_net',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='doe_reference_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='loads_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='loads_kw_is_net',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='monthly_totals_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='outage_is_major_event',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='percent_share',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='resilience_check_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadprofilemodel',
            name='year_one_electric_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='array_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='azimuth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='can_curtail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='can_net_meter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='can_wholesale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='dc_ac_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='existing_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='federal_itc_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='federal_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='gcr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='installed_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='inv_eff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='losses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='macrs_bonus_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='macrs_itc_reduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='max_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='min_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='module_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='om_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='pbi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='pbi_system_max_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='pbi_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='pbi_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='prod_factor_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='pv_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='pv_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='state_ibi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='state_ibi_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='state_rebate_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='state_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='tilt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='utility_ibi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='utility_ibi_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='utility_rebate_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='utility_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='year_one_curtailed_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='year_one_power_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='year_one_to_battery_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='year_one_to_grid_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pvmodel',
            name='year_one_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='api_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='time_steps_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenariomodel',
            name='timeout_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='battery_replacement_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='canGridCharge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='installed_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='installed_cost_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='internal_efficiency_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='inverter_efficiency_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='inverter_replacement_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='macrs_bonus_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='macrs_itc_reduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='max_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='max_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='min_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='min_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='rectifier_efficiency_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='replace_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='replace_cost_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='soc_init_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='soc_min_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='total_itc_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='total_rebate_us_dollars_per_kw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='total_rebate_us_dollars_per_kwh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='year_one_soc_series_pct',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='year_one_to_grid_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='storagemodel',
            name='year_one_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='urdberror',
            name='type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='can_curtail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='can_export_beyond_site_load',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='can_net_meter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='can_wholesale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='federal_itc_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='federal_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='installed_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='macrs_bonus_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='macrs_itc_reduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='max_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='min_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='om_cost_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='pbi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='pbi_system_max_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='pbi_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='pbi_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='pressure_atmospheres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='prod_factor_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='size_class',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='state_ibi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='state_ibi_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='state_rebate_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='state_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='temperature_celsius',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='utility_ibi_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='utility_ibi_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='utility_rebate_max_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='utility_rebate_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='wind_direction_degrees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='wind_meters_per_sec',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='year_one_curtailed_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='year_one_power_production_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='year_one_to_battery_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='year_one_to_grid_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='windmodel',
            name='year_one_to_load_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
