# Generated by Django 2.2.13 on 2021-01-01 01:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0097_delete_loadprofilewaterheatermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flextechwhmodel',
            name='operating_penalty_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='flextechwhmodel',
            name='prod_factor_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
