# Generated by Django 2.2.13 on 2021-01-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0098_auto_20210115_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmodel',
            old_name='total_opex_costs_us_dollars',
            new_name='total_om_costs_us_dollars',
        ),
        migrations.RenameField(
            model_name='financialmodel',
            old_name='year_one_opex_costs_before_tax_us_dollars',
            new_name='year_one_om_costs_before_tax_us_dollars',
        ),
        migrations.RenameField(
            model_name='financialmodel',
            old_name='year_one_opex_costs_us_dollars',
            new_name='year_one_om_costs_us_dollars',
        ),
    ]
