# Generated by Django 2.2.13 on 2021-01-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0099_auto_20210108_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flextechwhmodel',
            old_name='use_wh_model',
            new_name='use_hpwh_model',
        ),
    ]
