# Generated by Django 2.2.13 on 2021-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0099_auto_20210119_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='om_and_replacement_present_cost_after_tax_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
