# Generated by Django 2.2.13 on 2021-01-11 03:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0100_auto_20210110_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexTechERWHModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('min_kw', models.FloatField(blank=True, default=0, null=True)),
                ('max_kw', models.FloatField(blank=True, default=0, null=True)),
                ('installed_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('size_kw', models.FloatField(blank=True, null=True)),
                ('year_one_power_production_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('year_one_power_consumption_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FlexTechHPWHModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('min_kw', models.FloatField(blank=True, default=0, null=True)),
                ('max_kw', models.FloatField(blank=True, default=0, null=True)),
                ('installed_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('prod_factor_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('operating_penalty_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('size_kw', models.FloatField(blank=True, null=True)),
                ('year_one_power_production_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('year_one_power_consumption_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='HotWaterTankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('a_matrix', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('b_matrix', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('u_inputs', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('init_temperatures_degC', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
                ('n_temp_nodes', models.IntegerField(blank=True, null=True)),
                ('n_input_nodes', models.IntegerField(blank=True, null=True)),
                ('injection_node', models.IntegerField(blank=True, null=True)),
                ('water_node', models.IntegerField(blank=True, null=True)),
                ('temperature_lower_bound_degC', models.FloatField(blank=True, null=True)),
                ('temperature_upper_bound_degC', models.FloatField(blank=True, null=True)),
                ('installed_cost_us_dollars_per_kw', models.FloatField(blank=True, null=True)),
                ('year_one_temperature_series_degC', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='FlexTechWHModel',
        ),
    ]
