# Generated by Django 2.2.10 on 2021-01-27 01:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0100_financialmodel_om_and_replacement_present_cost_after_tax_us_dollars'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='coincident_peak_load_active_timesteps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='coincident_peak_load_charge_us_dollars_per_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_coincident_peak_cost_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_coincident_peak_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_coincident_peak_cost_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_coincident_peak_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='add_blended_rates_to_urdb_rate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
