# Generated by Django 2.2.13 on 2021-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0101_auto_20210127_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprofilemodel',
            name='outage_utility_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadprofilemodel',
            name='use_default_outage',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
