# Generated by Django 2.2.13 on 2021-01-14 04:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0101_auto_20210110_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwatertankmodel',
            name='comfort_penalty_degC',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
