# Generated by Django 2.2.13 on 2021-02-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0101_auto_20210127_0151'),
        ('reo', '0079_auto_20210202_2122'),
    ]

    operations = [
    ]
