# Generated by Django 2.2.13 on 2021-02-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0102_financialmodel_developer_om_and_replacement_present_cost_after_tax_us_dollars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilermodel',
            name='installed_cost_us_dollars_per_mmbtu_per_hr',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='max_mmbtu_per_hr',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='min_mmbtu_per_hr',
        ),
        migrations.RemoveField(
            model_name='electricchillermodel',
            name='installed_cost_us_dollars_per_kw',
        ),
        migrations.RemoveField(
            model_name='electricchillermodel',
            name='max_kw',
        ),
        migrations.RemoveField(
            model_name='electricchillermodel',
            name='min_kw',
        ),
    ]
