# Generated by Django 2.2.13 on 2021-01-14 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0102_hotwatertankmodel_comfort_penalty_degc'),
    ]

    operations = [
        migrations.AddField(
            model_name='flextecherwhmodel',
            name='fraction_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='flextechhpwhmodel',
            name='fraction_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
