# Generated by Django 2.2.13 on 2021-03-04 18:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0102_auto_20210301_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprofilemodel',
            name='load_met_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
    ]
