# Generated by Django 2.2.13 on 2021-03-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0102_auto_20210209_1745'),
        ('reo', '0102_financialmodel_developer_om_and_replacement_present_cost_after_tax_us_dollars'),
    ]

    operations = [
    ]
