# Generated by Django 3.1.7 on 2021-04-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0103_auto_20210223_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariomodel',
            name='optimality_tolerance_decomp_subproblem',
        ),
        migrations.RemoveField(
            model_name='scenariomodel',
            name='timeout_decomp_subproblem_seconds',
        ),
        migrations.RemoveField(
            model_name='scenariomodel',
            name='use_decomposition_model',
        ),
    ]
