# Generated by Django 2.2.10 on 2021-03-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0103_merge_20210301_2107'),
        ('reo', '0103_auto_20210223_1608'),
    ]

    operations = [
    ]
