# Generated by Django 2.2.13 on 2021-03-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0103_loadprofilemodel_load_met_series_kw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='offgrid_flag',
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='container_cost_us_dollars_per_sqft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='distribution_system_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='labor_cost_us_dollars_per_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='land_lease_us_dollars_per_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='pre_operating_expenses_us_dollars_per_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenariomodel',
            name='off_grid_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
