# Generated by Django 2.2.13 on 2021-01-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0103_auto_20210114_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwatertankmodel',
            name='comfort_temp_limit_degC',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
