# Generated by Django 2.2.13 on 2021-03-08 21:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0104_auto_20210308_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodel',
            name='sr_provided_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='sr_provided_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
    ]
