# Generated by Django 3.1.12 on 2021-06-28 20:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0104_auto_20210409_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='emissions_factor_lb_NOx_per_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_bau_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='emissions_factor_lb_NOx_per_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='year_one_emissions_bau_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='year_one_emissions_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='emissions_factor_series_lb_NOx_per_kwh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_bau_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='emissions_factor_lb_NOx_per_gal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_bau_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_bau_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
