# Generated by Django 2.2.13 on 2021-03-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0104_auto_20210303_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='newboilermodel',
            name='macrs_bonus_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newboilermodel',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steamturbinemodel',
            name='macrs_bonus_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steamturbinemodel',
            name='macrs_option_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
