# Generated by Django 2.2.13 on 2021-01-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0104_hotwatertankmodel_comfort_temp_limit_degc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flextechacmodel',
            old_name='operating_penalty_kw',
            new_name='cop',
        ),
        migrations.RenameField(
            model_name='flextechhpmodel',
            old_name='operating_penalty_kw',
            new_name='cop',
        ),
        migrations.RenameField(
            model_name='flextechhpwhmodel',
            old_name='operating_penalty_kw',
            new_name='cop',
        ),
    ]
