# Generated by Django 2.2.13 on 2021-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0105_auto_20210308_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemodel',
            name='battery_room_size_sqft_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='inverter_room_size_sqft',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
