# Generated by Django 2.2.13 on 2021-01-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0105_auto_20210114_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flextecherwhmodel',
            name='max_kw',
        ),
        migrations.RemoveField(
            model_name='flextecherwhmodel',
            name='min_kw',
        ),
        migrations.RemoveField(
            model_name='flextechhpwhmodel',
            name='max_kw',
        ),
        migrations.RemoveField(
            model_name='flextechhpwhmodel',
            name='min_kw',
        ),
        migrations.AlterField(
            model_name='flextecherwhmodel',
            name='size_kw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flextechhpwhmodel',
            name='size_kw',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
