# Generated by Django 2.2.13 on 2021-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0106_auto_20210309_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmodel',
            old_name='container_cost_us_dollars_per_sqft',
            new_name='powerhouse_civil_cost_us_dollars_per_sqft',
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='lc_labor_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='lc_land_lease_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='microgrid_lcoe_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='powerhouse_civil_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='pre_operating_expenses_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='total_distribution_system_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
