# Generated by Django 3.1.8 on 2021-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0106_auto_20210315_0341'),
        ('reo', '0104_auto_20210409_1454'),
    ]

    operations = [
    ]
