# Generated by Django 3.1.12 on 2021-07-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0107_auto_20210630_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='CO2_cost_escalation_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='CO2_cost_us_dollars_per_tonne',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
