# Generated by Django 2.2.13 on 2021-01-20 22:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0107_auto_20210115_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcmodel',
            name='comfort_penalty_degC',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='comfort_temp_lower_bound_degC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='comfort_temp_upper_bound_degC',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
