# Generated by Django 3.1.12 on 2021-08-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0107_auto_20210320_0358'),
        ('reo', '0104_auto_20210409_1454'),
    ]

    operations = [
    ]
