# Generated by Django 3.1.8 on 2021-04-29 14:23

import django.contrib.postgres.fields
from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0107_merge_20210420_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(unique=True)),
                ('force_ghp', models.BooleanField(blank=True, null=True)),
                ('installed_cost_heatpump_us_dollars_per_ton', models.FloatField(blank=True, null=True)),
                ('heatpump_capacity_sizing_factor_on_peak_load', models.FloatField(blank=True, null=True)),
                ('installed_cost_ghx_us_dollars_per_ft', models.FloatField(blank=True, null=True)),
                ('installed_cost_building_hydronic_loop_us_dollars_per_sqft', models.FloatField(blank=True, null=True)),
                ('om_cost_us_dollars_per_sqft_year', models.FloatField(blank=True, null=True)),
                ('building_sqft', models.FloatField(blank=True, null=True)),
                ('ghpghx_response', django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), null=True, size=None)),
                ('macrs_option_years', models.IntegerField(blank=True, null=True)),
                ('macrs_bonus_pct', models.FloatField(blank=True, null=True)),
                ('macrs_itc_reduction', models.FloatField(blank=True, null=True)),
                ('federal_itc_pct', models.FloatField(blank=True, null=True)),
                ('state_ibi_pct', models.FloatField(blank=True, null=True)),
                ('state_ibi_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('utility_ibi_pct', models.FloatField(blank=True, null=True)),
                ('utility_ibi_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('federal_rebate_us_dollars_per_ton', models.FloatField(blank=True, null=True)),
                ('state_rebate_us_dollars_per_ton', models.FloatField(blank=True, null=True)),
                ('state_rebate_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('utility_rebate_us_dollars_per_ton', models.FloatField(blank=True, null=True)),
                ('utility_rebate_max_us_dollars', models.FloatField(blank=True, null=True)),
                ('ghp_chosen_uuid', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
