# Generated by Django 2.2.13 on 2021-03-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0108_auto_20210309_1633'),
        ('reo', '0103_auto_20210223_1608'),
    ]

    operations = [
    ]
