# Generated by Django 2.2.13 on 2021-02-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0101_auto_20210127_0151'),
        ('reo', '0108_auto_20210120_1538'),
    ]

    operations = [
    ]
