# Generated by Django 3.1.12 on 2021-07-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0108_auto_20210707_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmodel',
            old_name='CO2_cost_escalation_pct',
            new_name='co2_cost_escalation_pct',
        ),
        migrations.RenameField(
            model_name='financialmodel',
            old_name='CO2_cost_us_dollars_per_tonne',
            new_name='co2_cost_us_dollars_per_tonne',
        ),
    ]
