# Generated by Django 2.2.13 on 2021-03-23 22:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0109_merge_20210310_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadprofilemodel',
            name='total_sr_provided',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='loadprofilemodel',
            name='total_sr_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), default=list, null=True, size=None),
        ),
    ]
