# Generated by Django 2.2.13 on 2021-02-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0109_merge_20210202_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='flextechacmodel',
            name='dse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flextechacmodel',
            name='fan_power_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flextechhpmodel',
            name='dse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flextechhpmodel',
            name='fan_power_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
