# Generated by Django 3.1.12 on 2021-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0109_auto_20210707_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='emissions_factor_series_CO2_pct_decrease',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
