# Generated by Django 2.2.13 on 2021-02-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0110_auto_20210204_1404'),
        ('reo', '0102_merge_20210209_1047'),
    ]

    operations = [
    ]
