# Generated by Django 3.1.12 on 2021-07-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0110_electrictariffmodel_emissions_factor_series_co2_pct_decrease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boilermodel',
            old_name='year_one_emissions_bau_lb_C02',
            new_name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RenameField(
            model_name='boilermodel',
            old_name='year_one_emissions_lb_C02',
            new_name='year_one_emissions_lb_CO2',
        ),
        migrations.RenameField(
            model_name='chpmodel',
            old_name='year_one_emissions_bau_lb_C02',
            new_name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RenameField(
            model_name='chpmodel',
            old_name='year_one_emissions_lb_C02',
            new_name='year_one_emissions_lb_CO2',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='year_one_emissions_bau_lb_C02',
            new_name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='year_one_emissions_lb_C02',
            new_name='year_one_emissions_lb_CO2',
        ),
        migrations.RenameField(
            model_name='generatormodel',
            old_name='year_one_emissions_bau_lb_C02',
            new_name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RenameField(
            model_name='generatormodel',
            old_name='year_one_emissions_lb_C02',
            new_name='year_one_emissions_lb_CO2',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_bau_lb_C02',
            new_name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_lb_C02',
            new_name='year_one_emissions_from_elec_grid_purchase',
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='include_exported_elec_emissions_in_total',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_elec_grid_purchase_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_lb_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_offset_from_elec_exports',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_offset_from_elec_exports_bau',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
