# Generated by Django 3.1.7 on 2021-06-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0104_auto_20210409_1454'),
        ('reo', '0110_auto_20210204_1404'),
    ]

    operations = [
    ]
