# Generated by Django 3.1.8 on 2021-05-24 17:39

import django.contrib.postgres.fields
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0110_ghpmodel_ghpghx_chosen_outputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpmodel',
            name='ghpghx_inputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ghpmodel',
            name='ghpghx_response',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), default=list, null=True, size=None),
        ),
    ]
