# Generated by Django 3.1.7 on 2021-03-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0103_auto_20210223_1608'),
        ('reo', '0111_merge_20210210_1941'),
    ]

    operations = [
    ]
