# Generated by Django 3.1.12 on 2021-07-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0111_merge_20210608_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwatertankmodel',
            name='comfort_WH_value_usd_per_degC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='comfort_HVAC_value_usd_per_degC',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
