# Generated by Django 3.1.12 on 2021-07-13 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0111_auto_20210708_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_from_elec_grid_purchase',
            new_name='year_one_CO2_emissions_from_elec_grid_purchase',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_from_elec_grid_purchase_bau',
            new_name='year_one_CO2_emissions_from_elec_grid_purchase_bau',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_from_fuelburn',
            new_name='year_one_CO2_emissions_from_fuelburn',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_from_fuelburn_bau',
            new_name='year_one_CO2_emissions_from_fuelburn_bau',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_offset_from_elec_exports',
            new_name='year_one_CO2_emissions_offset_from_elec_exports',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_offset_from_elec_exports_bau',
            new_name='year_one_CO2_emissions_offset_from_elec_exports_bau',
        ),
    ]
