# Generated by Django 3.1.7 on 2021-04-27 21:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0111_generatormodel_useful_life_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatormodel',
            name='fuel_used_series_gal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='generatormodel',
            name='sr_provided_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
