# Generated by Django 3.1.12 on 2021-07-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0112_auto_20210713_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_lb_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
