# Generated by Django 3.1.7 on 2021-04-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0112_merge_20210326_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwatertankmodel',
            name='comfort_WH_value_usd_per_degC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='comfort_HVAC_value_usd_per_degC',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
