# Generated by Django 3.1.12 on 2021-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0112_auto_20210706_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpmodel',
            name='size_heat_pump_ton',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
