# Generated by Django 3.1.12 on 2021-08-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0113_ghpmodel_size_heat_pump_ton'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamturbinemodel',
            name='size_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
