# Generated by Django 3.1.7 on 2021-05-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0104_auto_20210409_1454'),
        ('reo', '0113_auto_20210430_1833'),
    ]

    operations = [
    ]
