# Generated by Django 3.1.12 on 2021-07-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0113_sitemodel_lifetime_emissions_lb_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_cost_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
