# Generated by Django 3.1.8 on 2021-06-02 03:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0114_merge_20210419_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_demand_cost_by_ratchet_us_dollars_per_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_peak_demand_by_ratchet_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
