# Generated by Django 3.1.12 on 2021-08-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0114_steamturbinemodel_size_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldtesmodel',
            name='chilled_supply_water_temp_degF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coldtesmodel',
            name='warmed_return_water_temp_degF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hottesmodel',
            name='cooled_return_water_temp_degF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hottesmodel',
            name='hot_supply_water_temp_degF',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
