# Generated by Django 3.1.7 on 2021-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0114_merge_20210506_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='lcoe_component_diesel_capex_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='lcoe_component_fuel_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='lcoe_component_om_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='lcoe_component_other_annual_costs_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='lcoe_component_other_capex_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='lcoe_component_re_capex_us_dollars_per_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='pv_om_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
