# Generated by Django 3.1.12 on 2021-07-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0114_sitemodel_lifetime_emissions_cost_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariomodel',
            name='include_climate_in_objective',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
