# Generated by Django 3.1.12 on 2021-09-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0116_auto_20210818_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boilermodel',
            old_name='can_supply_st',
            new_name='can_supply_steam_turbine',
        ),
        migrations.RenameField(
            model_name='chpmodel',
            old_name='can_supply_st',
            new_name='can_supply_steam_turbine',
        ),
        migrations.RenameField(
            model_name='newboilermodel',
            old_name='can_supply_st',
            new_name='can_supply_steam_turbine',
        ),
    ]
