# Generated by Django 3.1.8 on 2021-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0116_auto_20210520_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='generator_fuel_escalation_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
