# Generated by Django 3.1.12 on 2021-09-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0117_auto_20210920_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghpmodel',
            old_name='force_ghp',
            new_name='require_ghp_purchase',
        ),
    ]
