# Generated by Django 3.1.12 on 2021-09-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0117_chpmodel_supplementary_firing_capital_cost_per_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpmodel',
            name='size_supplementary_firing_kw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
