# Generated by Django 3.1.12 on 2021-07-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0117_auto_20210715_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_cost_Health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_cost_Health_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_lb_NOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_lb_NOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_lb_PM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_lb_PM_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_lb_SO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifetime_emissions_lb_SO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
