# Generated by Django 3.1.12 on 2021-09-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0118_auto_20210920_2155'),
        ('reo', '0117_auto_20210920_1545'),
    ]

    operations = [
    ]
