# Generated by Django 3.1.12 on 2021-07-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0118_auto_20210715_2148'),
        ('reo', '0115_auto_20210602_0328'),
    ]

    operations = [
    ]
