# Generated by Django 3.1.12 on 2021-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0118_auto_20210715_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmodel',
            old_name='nox_cost_us_dollars_per_tonne',
            new_name='nox_cost_us_dollars_per_tonne_grid',
        ),
        migrations.RenameField(
            model_name='financialmodel',
            old_name='pm_cost_us_dollars_per_tonne',
            new_name='pm_cost_us_dollars_per_tonne_grid',
        ),
        migrations.RenameField(
            model_name='financialmodel',
            old_name='so2_cost_us_dollars_per_tonne',
            new_name='so2_cost_us_dollars_per_tonne_grid',
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='nox_cost_us_dollars_per_tonne_onsite_fuelburn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='pm_cost_us_dollars_per_tonne_onsite_fuelburn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='so2_cost_us_dollars_per_tonne_onsite_fuelburn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
