# Generated by Django 3.1.12 on 2021-09-27 20:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0119_merge_20210923_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghpmodel',
            name='ghpghx_response',
        ),
        migrations.AddField(
            model_name='ghpmodel',
            name='ghpghx_response_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=list, null=True, size=None),
        ),
    ]
