# Generated by Django 3.1.12 on 2021-10-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0119_auto_20210729_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='emissions_factor_series_CO2_pct_decrease',
            new_name='emissions_factor_CO2_pct_decrease',
        ),
    ]
