# Generated by Django 3.1.12 on 2021-10-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0120_auto_20211008_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='nox_cost_escalation_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
