# Generated by Django 3.1.13 on 2021-10-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0120_auto_20210927_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='total_om_costs_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='year_one_om_costs_before_tax_bau_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
