# Generated by Django 3.1.12 on 2021-10-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0121_financialmodel_nox_cost_escalation_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='pm25_cost_escalation_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='so2_cost_escalation_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
