# Generated by Django 3.1.13 on 2021-11-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0121_merge_20211001_1841'),
        ('reo', '0122_loadprofilemodel_load_met_pct'),
    ]

    operations = [
    ]
