# Generated by Django 3.1.12 on 2021-10-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0122_auto_20211018_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='breakeven_cost_of_emissions_reduction_us_dollars_per_ton_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='emissions_reduction_max_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='emissions_reduction_min_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='include_exported_renewable_electricity_in_total',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='include_outage_emissions_in_total',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='preprocessed_year_one_emissions_bau_lb_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='renewable_electricity_max_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='renewable_electricity_min_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_reduction_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_bau_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_bau_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_bau_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_bau_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
