# Generated by Django 3.1.12 on 2021-10-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0122_auto_20211018_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='emissions_factor_NOx_pct_decrease',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='emissions_factor_PM_pct_decrease',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='emissions_factor_SO2_pct_decrease',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
