# Generated by Django 3.1.13 on 2021-12-01 19:53

import django.contrib.postgres.fields
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0123_merge_20211103_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpmodel',
            name='ghpghx_responses',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), default=list, null=True, size=None),
        ),
    ]
