# Generated by Django 3.1.12 on 2021-10-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0123_auto_20211029_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boilermodel',
            old_name='emissions_factor_lb_PM_per_mmbtu',
            new_name='emissions_factor_lb_PM25_per_mmbtu',
        ),
        migrations.RenameField(
            model_name='boilermodel',
            old_name='year_one_emissions_bau_lb_PM',
            new_name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RenameField(
            model_name='boilermodel',
            old_name='year_one_emissions_lb_PM',
            new_name='year_one_emissions_lb_PM25',
        ),
        migrations.RenameField(
            model_name='chpmodel',
            old_name='emissions_factor_lb_PM_per_mmbtu',
            new_name='emissions_factor_lb_PM25_per_mmbtu',
        ),
        migrations.RenameField(
            model_name='chpmodel',
            old_name='year_one_emissions_bau_lb_PM',
            new_name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RenameField(
            model_name='chpmodel',
            old_name='year_one_emissions_lb_PM',
            new_name='year_one_emissions_lb_PM25',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='emissions_factor_PM_pct_decrease',
            new_name='emissions_factor_PM25_pct_decrease',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='emissions_factor_series_lb_PM_per_kwh',
            new_name='emissions_factor_series_lb_PM25_per_kwh',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='year_one_emissions_bau_lb_PM',
            new_name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='year_one_emissions_lb_PM',
            new_name='year_one_emissions_lb_PM25',
        ),
        migrations.RenameField(
            model_name='financialmodel',
            old_name='pm_cost_us_dollars_per_tonne_grid',
            new_name='pm25_cost_us_dollars_per_tonne_grid',
        ),
        migrations.RenameField(
            model_name='financialmodel',
            old_name='pm_cost_us_dollars_per_tonne_onsite_fuelburn',
            new_name='pm25_cost_us_dollars_per_tonne_onsite_fuelburn',
        ),
        migrations.RenameField(
            model_name='generatormodel',
            old_name='emissions_factor_lb_PM_per_gal',
            new_name='emissions_factor_lb_PM25_per_gal',
        ),
        migrations.RenameField(
            model_name='generatormodel',
            old_name='year_one_emissions_bau_lb_PM',
            new_name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RenameField(
            model_name='generatormodel',
            old_name='year_one_emissions_lb_PM',
            new_name='year_one_emissions_lb_PM25',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='lifetime_emissions_lb_PM',
            new_name='lifetime_emissions_lb_PM25',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='lifetime_emissions_lb_PM_bau',
            new_name='lifetime_emissions_lb_PM25_bau',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_bau_lb_PM',
            new_name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_lb_PM',
            new_name='year_one_emissions_lb_PM25',
        ),
    ]
