# Generated by Django 3.1.12 on 2021-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0125_generatormodel_generator_fuel_percent_re'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmodel',
            name='year_one_exported_emissions_offset_bau_lb_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvmodel',
            name='year_one_exported_emissions_offset_lb_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='year_one_exported_emissions_offset_bau_lb_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='windmodel',
            name='year_one_exported_emissions_offset_lb_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
