# Generated by Django 3.1.12 on 2021-11-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0124_auto_20211029_2053'),
        ('reo', '0127_auto_20211105_1627'),
    ]

    operations = [
    ]
