# Generated by Django 3.1.12 on 2021-11-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0128_merge_20211105_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_reduction_pct',
            new_name='year_one_emissions_CO2_reduction_pct',
        ),
    ]
