# Generated by Django 3.1.12 on 2021-11-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0129_auto_20211108_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_CO2_reduction_pct',
            new_name='year_one_CO2_emissions_reduction_pct',
        ),
    ]
