# Generated by Django 3.1.12 on 2021-11-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0130_auto_20211108_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvmodel',
            name='year_one_exported_emissions_offset_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='pvmodel',
            name='year_one_exported_emissions_offset_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='windmodel',
            name='year_one_exported_emissions_offset_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='windmodel',
            name='year_one_exported_emissions_offset_lb_CO2',
        ),
    ]
