# Generated by Django 3.1.12 on 2021-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0130_auto_20211108_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvmodel',
            name='year_one_exported_emissions_offset_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='pvmodel',
            name='year_one_exported_emissions_offset_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='windmodel',
            name='year_one_exported_emissions_offset_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='windmodel',
            name='year_one_exported_emissions_offset_lb_CO2',
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='preprocessed_lifetime_emissions_bau_lb_CO2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
