# Generated by Django 3.1.12 on 2021-11-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0132_auto_20211109_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_CO2_emissions_reduction_pct',
            new_name='lifecycle_CO2_emissions_reduction_pct',
        ),
    ]
