# Generated by Django 3.1.12 on 2021-11-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0133_auto_20211109_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='annual_elec_kwh_for_testing',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='annual_elec_kwh_for_testing_bau',
        ),
    ]
