# Generated by Django 3.1.12 on 2021-11-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0134_auto_20211110_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='include_outage_emissions_in_total',
        ),
    ]
