# Generated by Django 3.1.14 on 2022-01-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0124_ghpmodel_ghpghx_responses'),
        ('reo', '0135_remove_sitemodel_include_outage_emissions_in_total'),
    ]

    operations = [
    ]
