# Generated by Django 3.1.12 on 2021-11-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0136_auto_20211110_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_emissions_bau_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_emissions_bau_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_emissions_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_emissions_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_emissions_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='year_one_emissions_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='chpmodel',
            name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='chpmodel',
            name='year_one_emissions_bau_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='chpmodel',
            name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='chpmodel',
            name='year_one_emissions_bau_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='chpmodel',
            name='year_one_emissions_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='chpmodel',
            name='year_one_emissions_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='chpmodel',
            name='year_one_emissions_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='chpmodel',
            name='year_one_emissions_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_emissions_bau_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_emissions_bau_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_emissions_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_emissions_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_emissions_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_emissions_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='generatormodel',
            name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='generatormodel',
            name='year_one_emissions_bau_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='generatormodel',
            name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='generatormodel',
            name='year_one_emissions_bau_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='generatormodel',
            name='year_one_emissions_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='generatormodel',
            name='year_one_emissions_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='generatormodel',
            name='year_one_emissions_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='generatormodel',
            name='year_one_emissions_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='breakeven_cost_of_emissions_reduction_us_dollars_per_ton_CO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_CO2_emissions_reduction_pct',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_emissions_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_emissions_lb_CO2_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_emissions_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_emissions_lb_NOx_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_emissions_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_emissions_lb_PM25_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_emissions_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='lifecycle_emissions_lb_SO2_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='preprocessed_lifecycle_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='preprocessed_year_one_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_CO2_emissions_from_elec_grid_purchase',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_CO2_emissions_from_elec_grid_purchase_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_CO2_emissions_from_fuelburn',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_CO2_emissions_from_fuelburn_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_CO2_emissions_offset_from_elec_exports',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_CO2_emissions_offset_from_elec_exports_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_emissions_bau_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_emissions_bau_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_emissions_bau_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_emissions_bau_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_emissions_lb_CO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_emissions_lb_NOx',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_emissions_lb_PM25',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_emissions_lb_SO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_bau_kwh',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_bau_pct',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_heat_bau_mmbtu',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_heat_bau_pct',
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='lifecycle_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='lifecycle_emissions_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='lifecycle_emissions_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='lifecycle_emissions_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='lifecycle_emissions_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='lifecycle_emissions_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='lifecycle_emissions_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='lifecycle_emissions_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='year_one_emissions_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='lifecycle_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='lifecycle_emissions_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='lifecycle_emissions_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='lifecycle_emissions_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='year_one_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='year_one_emissions_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='year_one_emissions_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chpmodel',
            name='year_one_emissions_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_gross_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_gross_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_gross_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_gross_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_gross_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_gross_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_gross_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_gross_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_net_if_selected_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_net_if_selected_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_net_if_selected_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_net_if_selected_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_net_if_selected_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_net_if_selected_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_net_if_selected_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_net_if_selected_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_offset_from_elec_exports_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_offset_from_elec_exports_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_offset_from_elec_exports_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_offset_from_elec_exports_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_offset_from_elec_exports_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_offset_from_elec_exports_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_offset_from_elec_exports_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='lifecycle_emissions_offset_from_elec_exports_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_gross_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_gross_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_gross_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_gross_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_gross_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_gross_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_gross_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_gross_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_net_if_selected_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_net_if_selected_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_net_if_selected_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_net_if_selected_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_net_if_selected_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_net_if_selected_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_net_if_selected_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_net_if_selected_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_offset_from_elec_exports_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_offset_from_elec_exports_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_offset_from_elec_exports_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_offset_from_elec_exports_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_offset_from_elec_exports_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_offset_from_elec_exports_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_offset_from_elec_exports_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='year_one_emissions_offset_from_elec_exports_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='lifecycle_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='lifecycle_emissions_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='lifecycle_emissions_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='lifecycle_emissions_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='lifecycle_emissions_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='lifecycle_emissions_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='lifecycle_emissions_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='lifecycle_emissions_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatormodel',
            name='year_one_emissions_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='breakeven_cost_of_emissions_reduction_us_dollars_per_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_PM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_from_fuelburn_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_from_fuelburn_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_from_fuelburn_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_from_fuelburn_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_from_fuelburn_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_from_fuelburn_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_from_fuelburn_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_from_fuelburn_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_reduction_CO2_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='lifecycle_emissions_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='preprocessed_BAU_lifecycle_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='preprocessed_BAU_year_one_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_PM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_tPM25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_from_fuelburn_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_tCO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_tCO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_tNOx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_tNOx_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_tPM25_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_tSO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_emissions_tSO2_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_kwh_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_pct_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_mmbtu_bau',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_renewable_heat_pct_bau',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
