# Generated by Django 3.1.14 on 2022-01-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0137_auto_20220103_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_demand_cost_by_ratchet_us_dollars_per_kw',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='year_one_peak_demand_by_ratchet_kw',
        ),
    ]
