# Generated by Django 4.0.2 on 2022-04-21 22:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0138_auto_20220106_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='event_hours',
            new_name='ra_flexload_baseline_kw',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='hourly_reductions',
            new_name='ra_hourly_reductions',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_dr_total_value',
            new_name='ra_pricing_us_dollars_per_kwh',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='monthly_ra_energy_total_value',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='monthly_ra_reduction_kw',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='monthly_ra_total_value',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='ra_demand_pricing_us_dollars_per_kw',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='ra_energy_pricing_us_dollars_per_kwh',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='ra_event_day_flags_boolean',
        ),
        migrations.RemoveField(
            model_name='electrictariffmodel',
            name='ra_lookback_days',
        ),
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='coincident_peak_load_active_timesteps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, null=True, size=None), default=list, null=True, size=None),
        ),
    ]
