# Generated by Django 3.1.12 on 2021-11-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0138_auto_20211112_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='lifecycle_emissions_PM25',
            new_name='lifecycle_emissions_tPM25',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_emissions_PM25',
            new_name='year_one_emissions_tPM25',
        ),
    ]
