# Generated by Django 4.0.6 on 2022-08-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0139_alter_electrictariffmodel_coincident_peak_load_active_timesteps'),
        ('reo', '0139_rename_event_hours_electrictariffmodel_ra_flexload_baseline_kw_and_more'),
    ]

    operations = [
    ]
