# Generated by Django 3.1.13 on 2021-11-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0139_auto_20211115_2257'),
        ('reo', '0123_merge_20211103_1453'),
    ]

    operations = [
    ]
