# Generated by Django 3.1.13 on 2021-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0141_auto_20211117_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newboilermodel',
            name='year_one_emissions_lb_C02',
        ),
        migrations.AddField(
            model_name='fueltariffmodel',
            name='newboiler_fuel_percent_RE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newboilermodel',
            name='emissions_factor_lb_NOx_per_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newboilermodel',
            name='emissions_factor_lb_PM25_per_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newboilermodel',
            name='emissions_factor_lb_SO2_per_mmbtu',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
