# Generated by Django 3.1.13 on 2021-12-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0141_auto_20211202_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='preprocessed_BAU_lifecycle_emissions_tCO2',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='preprocessed_BAU_year_one_emissions_tCO2',
        ),
    ]
