# Generated by Django 3.1.14 on 2022-01-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0124_ghpmodel_ghpghx_responses'),
        ('reo', '0141_auto_20211202_2315'),
    ]

    operations = [
    ]
