# Generated by Django 3.1.13 on 2021-12-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0142_auto_20211206_2100'),
        ('reo', '0124_ghpmodel_ghpghx_responses'),
    ]

    operations = [
    ]
