# Generated by Django 3.1.13 on 2021-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0142_auto_20211206_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_electricity_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='year_one_electricity_kwh_bau',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
