# Generated by Django 3.1.14 on 2022-01-03 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0142_merge_20220103_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='hourly_reductions',
            new_name='hourly_reductions_kWh',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_dr',
            new_name='monthly_ra_dr_total_value',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_energy',
            new_name='monthly_ra_energy_total_value',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_reduction',
            new_name='monthly_ra_reduction_kw',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_value',
            new_name='monthly_ra_total_value',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='preprocessed_BAU_lifecycle_emissions_tCO2',
            new_name='annual_renewable_electricity_kwh',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='preprocessed_BAU_year_one_emissions_tCO2',
            new_name='annual_renewable_electricity_kwh_bau',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_heat_load_mmbtu',
            new_name='annual_renewable_electricity_pct',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_heat_load_mmbtu_bau',
            new_name='annual_renewable_electricity_pct_bau',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_electricity_kwh',
            new_name='annual_total_renewable_energy_pct',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_electricity_kwh_bau',
            new_name='annual_total_renewable_energy_pct_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_pct',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_electricity_pct_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_heat_mmbtu',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_heat_mmbtu_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_heat_pct',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_heat_pct_bau',
        ),
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_ra_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='total_production_incentive_after_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fueltariffmodel',
            name='total_fuel_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpmodel',
            name='cooling_efficiency_thermal_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpmodel',
            name='cooling_thermal_reduction_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='ghpmodel',
            name='space_heating_efficiency_thermal_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpmodel',
            name='space_heating_thermal_reduction_series_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='hotwatertankmodel',
            name='hvac_comfort_cost_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='wh_comfort_cost_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
