# Generated by Django 3.1.13 on 2021-12-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0143_merge_20211209_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpmodel',
            name='cooling_efficiency_thermal_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ghpmodel',
            name='space_heating_efficiency_thermal_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
