# Generated by Django 3.1.13 on 2021-11-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0142_auto_20211118_1948'),
        ('reo', '0143_auto_20211129_2237'),
    ]

    operations = [
    ]
