# Generated by Django 3.1.13 on 2021-12-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0143_auto_20211209_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_electricity_kwh',
            new_name='annual_renewable_electricity_kwh',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_electricity_kwh_bau',
            new_name='annual_renewable_electricity_kwh_bau',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_electricity_pct',
            new_name='annual_renewable_electricity_pct',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_electricity_pct_bau',
            new_name='annual_renewable_electricity_pct_bau',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_heat_pct',
            new_name='annual_total_renewable_energy_pct',
        ),
        migrations.RenameField(
            model_name='sitemodel',
            old_name='year_one_renewable_heat_pct_bau',
            new_name='annual_total_renewable_energy_pct_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_electricity_kwh',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_electricity_kwh_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_heat_load_mmbtu',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_heat_load_mmbtu_bau',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_heat_mmbtu',
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='year_one_renewable_heat_mmbtu_bau',
        ),
    ]
