# Generated by Django 3.1.13 on 2021-12-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0144_auto_20211210_2306'),
        ('reo', '0144_auto_20211210_2052'),
    ]

    operations = [
    ]
