# Generated by Django 3.1.14 on 2022-01-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0144_auto_20220103_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotwatertankmodel',
            old_name='hvac_comfort_cost_total',
            new_name='wh_comfort_cost_total',
        ),
    ]
