# Generated by Django 3.1.13 on 2021-12-16 21:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0145_merge_20211213_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpmodel',
            name='cooling_thermal_reduction_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='ghpmodel',
            name='space_heating_thermal_reduction_series_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
