# Generated by Django 3.1.14 on 2022-01-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0145_auto_20220103_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='hourly_reductions_kWh',
            new_name='hourly_reductions_kwh',
        ),
    ]
