# Generated by Django 3.1.14 on 2021-12-30 15:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0146_auto_20211216_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrictariffmodel',
            name='total_ra_value_after_tax',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='financialmodel',
            name='total_production_incentive_after_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fueltariffmodel',
            name='total_fuel_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotwatertankmodel',
            name='hvac_comfort_cost_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmodel',
            name='wh_comfort_cost_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
