# Generated by Django 4.0.2 on 2022-03-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0146_auto_20211216_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmodel',
            name='total_production_incentive_after_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fueltariffmodel',
            name='total_fuel_cost_us_dollars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
