# Generated by Django 3.1.14 on 2022-01-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0146_auto_20220103_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='hourly_reductions_kwh',
            new_name='hourly_reductions',
        ),
    ]
