# Generated by Django 4.0.1 on 2022-04-18 23:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0147_financialmodel_total_production_incentive_after_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrictariffmodel',
            name='coincident_peak_load_active_timesteps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, null=True, size=None), default=list, null=True, size=None),
        ),
    ]
