# Generated by Django 3.1.14 on 2021-12-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0147_auto_20211230_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='hourly_reductions',
            new_name='hourly_reductions_kWh',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_dr',
            new_name='monthly_ra_dr_total_value',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_energy',
            new_name='monthly_ra_energy_total_value',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_reduction',
            new_name='monthly_ra_reduction_kw',
        ),
        migrations.RenameField(
            model_name='electrictariffmodel',
            old_name='monthly_ra_value',
            new_name='monthly_ra_total_value',
        ),
    ]
