# Generated by Django 4.0.7 on 2023-02-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0148_alter_electrictariffmodel_coincident_peak_load_active_timesteps'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='messagemodel',
            index_together={('run_uuid',)},
        ),
        migrations.AlterIndexTogether(
            name='pvmodel',
            index_together={('run_uuid',)},
        ),
    ]
