# Generated by Django 4.0.7 on 2023-03-12 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0150_remove_ghpmodel_is_hybrid_ghx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghpmodel',
            name='aux_cooler_energy_use_intensity_kwe_per_kwt',
        ),
        migrations.RemoveField(
            model_name='ghpmodel',
            name='aux_heater_thermal_efficiency',
        ),
    ]
