# Generated by Django 4.0.7 on 2023-03-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0149_alter_messagemodel_index_together_and_more'),
        ('reo', '0152_ghpmodel_aux_unit_capacity_sizing_factor_on_peak_load'),
    ]

    operations = [
    ]
