# Generated by Django 5.2.5 on 2025-09-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0153_merge_20230329_1652'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagemodel',
            new_name='reo_message_run_uui_a803e6_idx',
            old_fields=('run_uuid',),
        ),
        migrations.RenameIndex(
            model_name='pvmodel',
            new_name='reo_pvmodel_run_uui_5bdbcb_idx',
            old_fields=('run_uuid',),
        ),
    ]
