# Generated by Django 4.0.7 on 2024-12-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reo', '0153_merge_20230329_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemodel',
            name='max_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='min_duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
