apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-db-migrate-job-{{ .Release.Revision }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ .Chart.Name }}-ecr-image-pull-secret
      volumes:
        - name: {{ .Chart.Name }}-secrets-volume
          secret:
            secretName: {{ .Chart.Name }}-secrets
      containers:
        - name: {{ .Chart.Name }}-job
          image: {{ index .Values.werf.image "reopt-api" }}
          args: ["bin/migrate"]
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-base-config-map
          volumeMounts:
            - name: {{ .Chart.Name }}-secrets-volume
              readOnly: true
              mountPath: /opt/reopt/keys.py
              subPath: {{ .Values.appEnv }}-keys.py
