apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-ecr-login-renew-service-account
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-ecr-login-renew-role
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-ecr-login-renew-role-binding
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-ecr-login-renew-role
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-ecr-login-renew-service-account
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-ecr-login-renew-config-map
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
data:
  DOCKER_SECRET_NAME: {{ .Chart.Name }}-ecr-image-pull-secret
  TARGET_NAMESPACE: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-ecr-login-renew-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  AWS_REGION: {{ .Values.ecrAwsRegion | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.ecrAwsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ecrAwsSecretAccessKey | b64enc | quote }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-ecr-login-renew-initial-setup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      serviceAccountName: {{ .Chart.Name }}-ecr-login-renew-service-account
      containers:
        - name: {{ .Chart.Name }}-ecr-login-renew
          image: ghcr.io/nabsul/k8s-ecr-login-renew:v1.7.1
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-ecr-login-renew-config-map
            - secretRef:
                name: {{ .Chart.Name }}-ecr-login-renew-secrets
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-ecr-login-renew-cron-job
spec:
  schedule: "37 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          serviceAccountName: {{ .Chart.Name }}-ecr-login-renew-service-account
          containers:
            - name: {{ .Chart.Name }}-ecr-login-renew
              image: ghcr.io/nabsul/k8s-ecr-login-renew:v1.7.1
              envFrom:
                - configMapRef:
                    name: {{ .Chart.Name }}-ecr-login-renew-config-map
                - secretRef:
                    name: {{ .Chart.Name }}-ecr-login-renew-secrets
