apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis-service
  annotations:
    "helm.sh/resource-policy": keep
spec:
  selector:
    app: {{ .Chart.Name }}-redis
  ports:
    - protocol: TCP
      port: 6379
