apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  development-keys.py: {{ werf_secret_file "development-keys.py" | b64enc | quote }}
  staging-keys.py: {{ werf_secret_file "staging-keys.py" | b64enc | quote }}
  production-keys.py: {{ werf_secret_file "production-keys.py" | b64enc | quote }}
  redis_password: {{ .Values.secrets.redis_password | b64enc | quote }}
