apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  staging-keys.py: {{ werf_secret_file "staging-keys.py" | b64enc | quote }}
  production-keys.py: {{ werf_secret_file "production-keys.py" | b64enc | quote }}
