appEnv: staging
djangoSettingsModule: reopt_api.staging_settings
djangoReplicas: 4
djangoCpuRequest: "200m"
djangoCpuLimit: "8000m"
djangoMemoryRequest: "1600Mi"
djangoMemoryLimit: "1600Mi"
celeryReplicas: 4
celeryCpuRequest: "200m"
celeryCpuLimit: "8000m"
celeryMemoryRequest: "1400Mi"
celeryMemoryLimit: "1400Mi"
juliaReplicas: 4
juliaCpuRequest: "600m"
juliaCpuLimit: "8000m"
juliaMemoryRequest: "8000Mi"
juliaMemoryLimit: "8000Mi"
