# Generated by Django 4.0.2 on 2022-03-21 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricutilityinputs',
            name='outage_end_time_step',
            field=models.IntegerField(blank=True, help_text='Time step that grid outage ends. Must be greater than or equal to outage_start_time_step.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='electricutilityinputs',
            name='outage_start_time_step',
            field=models.IntegerField(blank=True, help_text='Time step that grid outage starts. Must be less than or equal to outage_end_time_step.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
