# Generated by Django 4.0.4 on 2022-07-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_electrictariffinputs_coincident_peak_load_active_timesteps_and_more'),
        ('job', '0005_siteoutputs_settings_include_climate_in_objective_and_more'),
    ]

    operations = [
    ]
