# Generated by Django 4.0.6 on 2022-07-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_boilerinputs_boileroutputs_existingboilerinputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvoutputs',
            name='lifecycle_om_cost_after_tax_bau',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
