# Generated by Django 4.0.4 on 2022-07-14 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_merge_20220714_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteoutputs',
            old_name='lifecycle_emissions_climate_cost',
            new_name='lifecycle_emissions_cost_climate',
        ),
        migrations.RenameField(
            model_name='siteoutputs',
            old_name='lifecycle_emissions_climate_cost_bau',
            new_name='lifecycle_emissions_cost_climate_bau',
        ),
        migrations.RenameField(
            model_name='siteoutputs',
            old_name='lifecycle_emissions_health_cost',
            new_name='lifecycle_emissions_cost_health',
        ),
        migrations.RenameField(
            model_name='siteoutputs',
            old_name='lifecycle_emissions_health_cost_bau',
            new_name='lifecycle_emissions_cost_health_bau',
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='CO2_cost_escalation_pct',
            field=models.FloatField(blank=True, default=0.042173, help_text='Annual nominal Social Cost of CO2 escalation rate (as a decimal).', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='CO2_cost_per_tonne',
            field=models.FloatField(blank=True, default=51.0, help_text='Social Cost of CO2 in the first year of the analysis. Units are US dollars per metric ton of CO2. The default of $51/t is the 2020 value (using a 3 pct discount rate) estimated by the U.S. Interagency Working Group on Social Cost of Greenhouse Gases.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='NOx_cost_escalation_pct',
            field=models.FloatField(blank=True, help_text='Annual nominal escalation rate of the public health cost of 1 tonne of NOx emissions (as a decimal). The default value is calculated from the EASIUR model for a height of 150m.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='NOx_grid_cost_per_tonne',
            field=models.FloatField(blank=True, help_text='Public health cost of NOx emissions from grid electricity in the first year of the analysis. Units are US dollars per metric ton. Default values for the U.S. obtained from the EASIUR model.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='NOx_onsite_fuelburn_cost_per_tonne',
            field=models.FloatField(blank=True, help_text='Public health cost of NOx from onsite fuelburn in the first year of the analysis. Units are US dollars per metric ton. Default values for the U.S. obtained from the EASIUR model.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='PM25_cost_escalation_pct',
            field=models.FloatField(blank=True, help_text='Annual nominal escalation rate of the public health cost of 1 tonne of PM2.5 emissions (as a decimal). The default value is calculated from the EASIUR model for a height of 150m.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='PM25_grid_cost_per_tonne',
            field=models.FloatField(blank=True, help_text='Public health cost of PM2.5 emissions from grid electricity in the first year of the analysis. Units are US dollars per metric ton. Default values for the U.S. obtained from the EASIUR model.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='PM25_onsite_fuelburn_cost_per_tonne',
            field=models.FloatField(blank=True, help_text='Public health cost of PM2.5 from onsite fuelburn in the first year of the analysis. Units are US dollars per metric ton. Default values for the U.S. obtained from the EASIUR model.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='SO2_cost_escalation_pct',
            field=models.FloatField(blank=True, help_text='Annual nominal escalation rate of the public health cost of 1 tonne of SO2 emissions (as a decimal). The default value is calculated from the EASIUR model for a height of 150m.', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='SO2_grid_cost_per_tonne',
            field=models.FloatField(blank=True, help_text='Public health cost of SO2 emissions from grid electricity in the first year of the analysis. Units are US dollars per metric ton. Default values for the U.S. obtained from the EASIUR model.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='SO2_onsite_fuelburn_cost_per_tonne',
            field=models.FloatField(blank=True, help_text='Public health cost of SO2 from onsite fuelburn in the first year of the analysis. Units are US dollars per metric ton. Default values for the U.S. obtained from the EASIUR model.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000.0)]),
        ),
    ]
