# Generated by Django 4.0.4 on 2022-07-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_lifecycle_emissions_climate_cost_siteoutputs_lifecycle_emissions_cost_climate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoutputs',
            name='breakeven_cost_of_emissions_reduction_per_tonnes_CO2',
            field=models.FloatField(blank=True, help_text='Cost of emissions required to breakeven (NPV = 0) compared to the BAU case LCC.If the cost of health emissions were included in the objective function,calculation of this output value keeps the cost of those emissions at the values input by the user.', null=True),
        ),
    ]
