# Generated by Django 4.0.6 on 2022-09-20 01:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_domestichotwaterloadinputs_existingboilerinputs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesOutputs',
            fields=[
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='MessagesOutputs', serialize=False, to='job.apimeta')),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=list, size=None)),
                ('warnings', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=list, size=None)),
            ],
            bases=(job.models.BaseModel, models.Model),
        ),
    ]
