# Generated by Django 4.0.6 on 2022-07-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_existingboilerinputs_emissions_factor_lb_co2_per_mmbtu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existingboilerinputs',
            name='can_supply_steam_turbine',
        ),
    ]
