# Generated by Django 4.0.4 on 2022-05-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_spaceheatingloadinputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_fuel_costs_after_tax',
            field=models.FloatField(blank=True, help_text='Life cycle fuel cost over analysis period after tax.', null=True),
        ),
    ]
