# Generated by Django 4.0.6 on 2022-09-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_windinputs_operating_reserve_required_pct_and_more'),
        ('job', '0009_alter_domestichotwaterloadinputs_doe_reference_name'),
    ]

    operations = [
    ]
