# Generated by Django 4.0.6 on 2022-07-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_existingboilerinputs_can_supply_steam_turbine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='lifecycle_fuel_cost',
            new_name='lifecycle_fuel_cost_after_tax',
        ),
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='lifecycle_fuel_cost_bau',
            new_name='lifecycle_fuel_cost_after_tax_bau',
        ),
    ]
