# Generated by Django 4.0.4 on 2022-05-17 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_financialoutputs_lifecycle_fuel_costs_after_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='boileroutputs',
            name='lifecycle_per_unit_prod_om_costs',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000000.0)]),
        ),
    ]
