# Generated by Django 4.0.6 on 2022-07-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_rename_lifecycle_fuel_cost_existingboileroutputs_lifecycle_fuel_cost_after_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='lifecycle_fuel_cost_after_tax',
            new_name='lifecycle_fuel_cost_before_tax',
        ),
    ]
