# Generated by Django 4.0.4 on 2022-07-15 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_electrictariffoutputs_emissions_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorinputs',
            name='emissions_factor_lb_CO2_per_gal',
            field=models.FloatField(blank=True, default=22.51, help_text='Pounds of CO2 emitted per gallon of generator fuel burned.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AddField(
            model_name='generatorinputs',
            name='emissions_factor_lb_NOx_per_gal',
            field=models.FloatField(blank=True, default=0.0775544, help_text='Pounds of CO2 emitted per gallon of generator fuel burned.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AddField(
            model_name='generatorinputs',
            name='emissions_factor_lb_PM25_per_gal',
            field=models.FloatField(blank=True, default=0.0, help_text='Pounds of CO2 emitted per gallon of generator fuel burned.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AddField(
            model_name='generatorinputs',
            name='emissions_factor_lb_SO2_per_gal',
            field=models.FloatField(blank=True, default=0.040020476, help_text='Pounds of CO2 emitted per gallon of generator fuel burned.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AddField(
            model_name='generatorinputs',
            name='fuel_renewable_energy_pct',
            field=models.FloatField(blank=True, default=0.0, help_text='Fraction of the generator fuel considered renewable.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
