# Generated by Django 4.0.4 on 2022-07-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_generatorinputs_emissions_factor_lb_co2_per_gal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteoutputs',
            name='lifecycle_emissions_cost_climate',
        ),
        migrations.RemoveField(
            model_name='siteoutputs',
            name='lifecycle_emissions_cost_health',
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_emissions_cost_climate',
            field=models.FloatField(blank=True, help_text="Total cost of CO2 emissions associated with the site's energy consumption over the analysis period.", null=True),
        ),
        migrations.AddField(
            model_name='financialoutputs',
            name='lifecycle_emissions_cost_health',
            field=models.FloatField(blank=True, help_text="Total cost of NOx, SO2, and PM2.5 emissions associated with the site's energy consumption over the analysis period.", null=True),
        ),
    ]
