# Generated by Django 4.0.4 on 2022-05-18 01:28

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_boileroutputs_year_one_fuel_consumption_mmbtu_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingboileroutputs',
            name='year_one_fuel_consumption_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)]), blank=True, default=list, size=None),
        ),
    ]
