# Generated by Django 4.0.6 on 2022-07-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_rename_lifecycle_fuel_cost_after_tax_existingboileroutputs_lifecycle_fuel_cost_before_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='year_one_fuel_cost',
            new_name='year_one_fuel_cost_before_tax',
        ),
    ]
