# Generated by Django 4.0.6 on 2022-11-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_coolingloadinputs_coolingloadoutputs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existingchillerinputs',
            name='loads_kw_thermal',
        ),
    ]
