# Generated by Django 4.0.6 on 2022-09-22 20:29

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_domestichotwaterloadinputs_addressable_load_fraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceheatingloadinputs',
            name='addressable_load_fraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]), blank=True, default=list, help_text='Fraction of input fuel load which is addressable by heating technologies (default is 1.0).Can be a scalar or vector with length aligned with use of monthly_mmbtu or fuel_loads_mmbtu_per_hour.', size=None),
        ),
        migrations.AlterField(
            model_name='domestichotwaterloadinputs',
            name='addressable_load_fraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]), blank=True, default=list, help_text='Fraction of input fuel load which is addressable by heating technologies (default is 1.0).Can be a scalar or vector with length aligned with use of monthly_mmbtu or fuel_loads_mmbtu_per_hour.', size=None),
        ),
    ]
