# Generated by Django 4.0.6 on 2022-07-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_rename_year_one_fuel_cost_existingboileroutputs_year_one_fuel_cost_before_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='lifecycle_fuel_cost_before_tax',
            new_name='lifecycle_fuel_cost_after_tax',
        ),
    ]
