# Generated by Django 4.0.6 on 2022-09-24 21:35

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_spaceheatingloadinputs_addressable_load_fraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceheatingloadinputs',
            name='addressable_load_fraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1.0)]), blank=True, default=list, help_text='Fraction of input fuel load which is addressable by heating technologies (default is 1.0).Can be a scalar or vector with length aligned with use of monthly_mmbtu (12) or fuel_loads_mmbtu_per_hour.', size=None),
        ),
        migrations.AlterField(
            model_name='spaceheatingloadinputs',
            name='monthly_mmbtu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000.0)]), blank=True, default=list, help_text="Monthly site space heating energy consumption in [MMbtu] (array of length 12). Used to scale simulated default building load profile for the site's climate zone", size=None),
        ),
    ]
