# Generated by Django 4.0.4 on 2022-11-08 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_rename_max_outage_cost_per_outage_duration_series_outageoutputs_max_outage_cost_per_outage_duration_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outageoutputs',
            name='generator_fuel_used_per_outage',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, size=None), blank=True, default=list, help_text='Generator fuel used in each outage modeled. Outage duration changes along the first dimension and outage start time changes along the second dimention.', size=None),
        ),
    ]
