# Generated by Django 4.0.6 on 2022-11-14 04:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_chpinputs_om_cost_per_kw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='thermal_to_tes_series_mmbtu_per_hour',
            new_name='year_one_fuel_consumption_series_mmbtu_per_hour',
        ),
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='year_one_fuel_consumption_mmbtu_per_hour',
            new_name='year_one_thermal_production_series_mmbtu_per_hour',
        ),
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='year_one_thermal_production_mmbtu_per_hour',
            new_name='year_one_thermal_to_steamturbine_series_mmbtu_per_hour',
        ),
        migrations.AddField(
            model_name='chpoutputs',
            name='year_one_thermal_to_steamturbine_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Thermal power to TES time-series array [MMBtu/hr]', size=None),
        ),
        migrations.AddField(
            model_name='existingboileroutputs',
            name='year_one_thermal_to_tes_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), default=list, size=None),
        ),
    ]
