# Generated by Django 4.0.4 on 2022-08-16 15:58

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_electricutilityinputs_emissions_factor_series_lb_co2_per_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrictariffinputs',
            name='coincident_peak_load_active_time_steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)]), blank=True, default=list, size=None), blank=True, default=list, help_text='The optional coincident_peak_load_charge_per_kw will apply to the max grid-purchased power during these time steps. Note time steps are indexed to a base of 1 not 0.', size=None),
        ),
    ]
