# Generated by Django 4.0.6 on 2022-09-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_existingboileroutputs_year_one_fuel_consumption_series_mmbtu_per_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existingboileroutputs',
            old_name='thermal_to_tes_series_mmbtu_per_hour',
            new_name='year_one_thermal_production_series_mmbtu_per_hour',
        ),
        migrations.RemoveField(
            model_name='existingboileroutputs',
            name='year_one_fuel_consumption_mmbtu_per_hour',
        ),
        migrations.RemoveField(
            model_name='existingboileroutputs',
            name='year_one_thermal_production_mmbtu_per_hour',
        ),
    ]
