# Generated by Django 4.0.4 on 2023-01-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_outageoutputs_generator_fuel_used_per_outage'),
        ('job', '0016_coldthermalstorageinputs_coldthermalstorageoutputs_and_more'),
    ]

    operations = [
    ]
