# Generated by Django 4.0.7 on 2023-01-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_merge_20230112_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialoutputs',
            name='replacement_costs',
        ),
    ]
