# Generated by Django 4.0.4 on 2023-01-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_merge_20230110_1712'),
        ('job', '0021_merge_20230112_1748'),
    ]

    operations = [
    ]
