# Generated by Django 4.0.7 on 2023-02-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_ghpinputs_ghpoutputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpoutputs',
            name='ghp_chosen_option',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
