# Generated by Django 4.0.7 on 2023-02-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_absorptionchillerinputs_absorptionchilleroutputs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absorptionchilleroutputs',
            old_name='year_one_electric_consumption_kwh',
            new_name='annual_electric_consumption_kwh',
        ),
        migrations.RenameField(
            model_name='absorptionchilleroutputs',
            old_name='year_one_thermal_consumption_mmbtu',
            new_name='annual_thermal_consumption_mmbtu',
        ),
        migrations.RenameField(
            model_name='absorptionchilleroutputs',
            old_name='year_one_thermal_production_tonhour',
            new_name='annual_thermal_production_tonhour',
        ),
        migrations.RenameField(
            model_name='absorptionchilleroutputs',
            old_name='year_one_electric_consumption_series_kw',
            new_name='electric_consumption_series_kw',
        ),
        migrations.RenameField(
            model_name='absorptionchilleroutputs',
            old_name='year_one_thermal_consumption_series_mmbtu_per_hr',
            new_name='thermal_consumption_series_mmbtu_per_hour',
        ),
        migrations.RenameField(
            model_name='absorptionchilleroutputs',
            old_name='year_one_to_load_series_ton',
            new_name='thermal_to_load_series_ton',
        ),
        migrations.RenameField(
            model_name='absorptionchilleroutputs',
            old_name='year_one_to_tes_series_ton',
            new_name='thermal_to_storage_series_ton',
        ),
    ]
