# Generated by Django 4.0.7 on 2023-02-01 16:17

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_ghpinputs_ghpoutputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpinputs',
            name='building_sqft',
            field=models.FloatField(help_text='Building square footage for GHP/HVAC cost calculations', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000000.0)]),
        ),
        migrations.AlterField(
            model_name='ghpinputs',
            name='ghpghx_inputs',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), blank=True, default=list, help_text='GhpGhx.jl inputs/POST to ghpghx app', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ghpinputs',
            name='ghpghx_response_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, help_text="List of ghp_uuid's (like run_uuid for REopt) from ghpghx app, used to get GhpGhx.jl run data", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ghpinputs',
            name='ghpghx_responses',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), blank=True, default=list, help_text='ghpghx app response(s) to re-use a previous GhpGhx.jl run without relying on a database entry', null=True, size=None),
        ),
    ]
