# Generated by Django 4.0.7 on 2023-02-08 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_ghpoutputs_ghp_chosen_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghpoutputs',
            old_name='ghp_chosen_option',
            new_name='ghp_option_chosen',
        ),
    ]
