# Generated by Django 4.0.7 on 2023-02-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_rename_year_one_electric_consumption_kwh_absorptionchilleroutputs_annual_electric_consumption_kwh_an'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absorptionchillerinputs',
            name='thermal_consumption_hot_water_or_steam',
            field=models.TextField(blank=True, choices=[('steam', 'Steam'), ('hot_water', 'Hot Water')], help_text='Boiler thermal production type, hot water or steam', null=True),
        ),
    ]
