# Generated by Django 4.0.4 on 2023-02-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_merge_20230101_0043'),
        ('job', '0024_alter_electrictariffinputs_blended_annual_demand_rate'),
    ]

    operations = [
    ]
