# Generated by Django 4.0.7 on 2023-03-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_merge_20230202_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='reoptjlmessageoutputs',
            name='has_stacktrace',
            field=models.BooleanField(blank=True, default=False, help_text='True if the error message has a stacktrace, false otherwise'),
        ),
    ]
