# Generated by Django 4.0.7 on 2023-03-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_absorptionchillerinputs_absorptionchilleroutputs'),
        ('job', '0025_merge_20230202_1907'),
    ]

    operations = [
    ]
