# Generated by Django 4.0.7 on 2023-03-06 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_alter_boilerinputs_installed_cost_per_mmbtu_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamturbineinputs',
            name='inlet_steam_superheat_degF',
            field=models.FloatField(default=0.0, help_text='Alternative input to inlet steam temperature, this is the superheat amount (delta from T_saturation) to the steam turbine', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(700.0)]),
        ),
        migrations.AlterField(
            model_name='steamturbineinputs',
            name='om_cost_per_kw',
            field=models.FloatField(default=0.0, help_text='Annual steam turbine fixed operations and maintenance costs in $/kW', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5000.0)]),
        ),
    ]
