# Generated by Django 4.0.7 on 2023-03-07 20:00

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_alter_steamturbineinputs_inlet_steam_superheat_degf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerinputs',
            name='fuel_cost_per_mmbtu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)]), default=list, help_text='Fuel cost in [$/MMBtu]', null=True, size=None),
        ),
    ]
