# Generated by Django 4.0.4 on 2023-03-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_merge_20230308_0636'),
        ('job', '0027_reoptjlmessageoutputs_has_stacktrace'),
    ]

    operations = [
    ]
