# Generated by Django 4.0.7 on 2023-03-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_merge_20230309_2246'),
        ('job', '0028_merge_20230314_2001'),
    ]

    operations = [
    ]
