# Generated by Django 4.0.7 on 2023-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_userunlinkedruns'),
        ('job', '0030_merge_20230317_1434'),
    ]

    operations = [
    ]
