# Generated by Django 4.0.7 on 2023-03-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_absorptionchillerinputs_absorptionchilleroutputs'),
        ('job', '0030_merge_20230317_1434'),
    ]

    operations = [
    ]
