# Generated by Django 4.0.7 on 2023-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_merge_0026_userunlinkedruns_0030_merge_20230317_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reoptjlmessageoutputs',
            name='has_stacktrace',
            field=models.BooleanField(blank=True, default=False, help_text='REopt.jl can return a handled error with corrective instructions or an unhandled error with a stacktrace of what went wrong for further insepction.This field is True if the error message has a stacktrace, otherwise False.'),
        ),
    ]
