# Generated by Django 4.0.4 on 2023-03-30 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_outageoutputs_chp_curtailed_series_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatorinputs',
            name='fuel_higher_heating_value_kwh_per_gal',
            field=models.FloatField(blank=True, default=40.7, help_text='Higher heating value of the generator fuel in kWh/gal. Defaults to the HHV of diesel.', null=True, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(100000000.0)]),
        ),
    ]
