# Generated by Django 4.0.7 on 2023-03-30 00:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_merge_20230329_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windinputs',
            name='production_factor_series',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), blank=True, default=list, help_text='Optional user-defined production factors. Must be normalized to units of kW-AC/kW-DC nameplate, representing the AC power (kW) output per 1 kW-DC of system capacity in each time step. The series must be one year (January through December) of hourly, 30-minute, or 15-minute  generation data.', size=None),
        ),
    ]
