# Generated by Django 4.0.7 on 2023-04-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_alter_financialinputs_value_of_lost_load_per_kwh_and_more'),
        ('job', '0034_alter_windinputs_production_factor_series'),
    ]

    operations = [
    ]
