# Generated by Django 4.0.7 on 2023-06-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_merge_20230321_2118'),
        ('job', '0036_merge_20230424_1645'),
    ]

    operations = [
    ]
