# Generated by Django 4.0.4 on 2023-07-03 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_merge_20230424_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorinputs',
            name='installed_cost_per_kw',
            field=models.FloatField(blank=True, default=650, help_text='Installed diesel generator cost in $/kW', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000.0)]),
        ),
    ]
