# Generated by Django 4.0.4 on 2023-05-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_merge_20230413_0504'),
        ('job', '0036_merge_20230424_1645'),
    ]

    operations = [
    ]
