# Generated by Django 4.0.7 on 2023-06-06 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0038_existingboilerinputs_can_supply_steam_turbine'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinputs',
            name='boiler_fuel_escalation_rate_fraction',
            field=models.FloatField(blank=True, default=0.034, help_text='Annual nominal boiler fuel cost escalation rate', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='chp_fuel_escalation_rate_fraction',
            field=models.FloatField(blank=True, default=0.034, help_text='Annual nominal chp fuel cost escalation rate', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='existing_boiler_fuel_escalation_rate_fraction',
            field=models.FloatField(blank=True, default=0.034, help_text='Annual nominal existing boiler fuel cost escalation rate', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='financialinputs',
            name='generator_fuel_cost_escalation_rate_fraction',
            field=models.FloatField(blank=True, default=0.027, help_text='Annual nominal boiler fuel cost escalation rate', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
