# Generated by Django 3.1.12 on 2021-09-26 19:50

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import ghpghx.models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GHPGHXInputs',
            fields=[
                ('ghp_uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude of the site', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(blank=True, help_text='Longitude of the site', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('borehole_depth_ft', models.FloatField(blank=True, default=400.0, help_text='Vertical depth of each borehole [ft]', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(600.0)])),
                ('ghx_header_depth_ft', models.FloatField(blank=True, default=4.0, help_text='Depth under the ground of the GHX header pipe [ft]', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50.0)])),
                ('borehole_spacing_ft', models.FloatField(blank=True, default=20.0, help_text='Distance from the centerline of each borehole to the centerline of its adjacent boreholes [ft]', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)])),
                ('borehole_diameter_inch', models.FloatField(blank=True, default=5.0, help_text='Diameter of the borehole/well drilled in the ground [in]', validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24.0)])),
                ('borehole_spacing_type', models.TextField(blank=True, choices=[('rectangular', 'rectangular'), ('hexagonal', 'hexagonal')], default='rectangular', help_text='Borehole spacing pattern type: rectangular or hexagonal')),
                ('ghx_pipe_outer_diameter_inch', models.FloatField(blank=True, default=1.66, help_text='Outer diameter of the GHX pipe [in]', validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24.0)])),
                ('ghx_pipe_wall_thickness_inch', models.FloatField(blank=True, default=0.16, help_text='Wall thickness of the GHX pipe [in]', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5.0)])),
                ('ghx_pipe_thermal_conductivity_btu_per_hr_ft_f', models.FloatField(blank=True, default=0.25, help_text='Thermal conductivity of the GHX pipe [Btu/(hr-ft-degF)]', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('ghx_shank_space_inch', models.FloatField(blank=True, default=2.5, help_text='Distance between the centerline of the upwards and downwards u-tube legs [in]', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(100.0)])),
                ('ground_thermal_conductivity_btu_per_hr_ft_f', models.FloatField(blank=True, default=1.18, help_text='Thermal conductivity of the ground surrounding the borehole field [Btu/(hr-ft-degF)]', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(15.0)])),
                ('ground_mass_density_lb_per_ft3', models.FloatField(blank=True, default=162.3, help_text='Mass density of the ground surrounding the borehole field [lb/ft^3]', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(500.0)])),
                ('ground_specific_heat_btu_per_lb_f', models.FloatField(blank=True, default=0.211, help_text='Specific heat of the ground surrounding the borehole field', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5.0)])),
                ('grout_thermal_conductivity_btu_per_hr_ft_f', models.FloatField(blank=True, default=1.0, help_text='Thermal conductivity of the grout material in a borehole [Btu/(hr-ft-degF)]', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)])),
                ('ghx_fluid_specific_heat_btu_per_lb_f', models.FloatField(blank=True, default=1.0, help_text='Specific heat of the fluid in the GHX (nominally water) [Btu/(lb-degF)]', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('ghx_fluid_mass_density_lb_per_ft3', models.FloatField(blank=True, default=62.4, help_text='Mass density of the fluid in the GHX (nominally water) [lb/ft^3]', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(200.0)])),
                ('ghx_fluid_thermal_conductivity_btu_per_hr_ft_f', models.FloatField(blank=True, default=0.34, help_text='Thermal conductivity of the fluid in the GHX (nominally water) [Btu/(hr-ft-degF)]', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5.0)])),
                ('ghx_fluid_dynamic_viscosity_lbm_per_ft_hr', models.FloatField(blank=True, default=2.75, help_text='Dynamic viscosity of the fluid in the GHX (nominally water) [lb/(ft-hr)]', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('ghx_fluid_flow_rate_gpm_per_ton', models.FloatField(blank=True, default=2.5, help_text='Volumetric flow rate of the fluid in the GHX per peak ton heating/cooling [GPM/ton]', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('ghx_pump_power_watt_per_gpm', models.FloatField(blank=True, default=15.0, help_text='Pumping power required for a given volumetric flow rate of the fluid in the GHX [Watt/GPM]', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ghx_pump_min_speed_fraction', models.FloatField(blank=True, default=0.1, help_text='The minimum turndown fraction of the pump. 1.0 is a constant speed pump.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ghx_pump_power_exponent', models.FloatField(blank=True, default=2.2, help_text='The pump power curve exponent', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('max_eft_allowable_f', models.FloatField(blank=True, default=104.0, help_text='Maximum allowable entering fluid temperature (EFT) of the heat pump (used in cooling dominated loads) [degF]', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(150.0)])),
                ('min_eft_allowable_f', models.FloatField(blank=True, default=23.0, help_text='Minimum allowable entering fluid temperature (EFT) of the heat pump (used in heating dominated loads) [degF]', validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('heating_thermal_load_mmbtu_per_hr', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly heating thermal load that GHP serves [MMBtu/hr]', null=True, size=None)),
                ('heating_fuel_load_mmbtu_per_hr', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly heating fuel load that GHP serves [MMBtu/hr]', null=True, size=None)),
                ('existing_boiler_efficiency', models.FloatField(blank=True, default=0.8, help_text='Efficiency of the existing boiler/heater serving the heating load', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('cooling_thermal_load_ton', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly cooling thermal load that GHP serves [ton]', null=True, size=None)),
                ('ambient_temperature_f', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly outdoor air dry bulb temperature, typically TMY3 data [degF]', null=True, size=None)),
                ('cop_map_eft_heating_cooling', django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False), default=ghpghx.models.GHPGHXInputs._get_cop_map, help_text='Heat pump coefficient of performance (COP) map: list of dictionaries, each with 3 keys: 1) EFT, 2) HeatingCOP, 3) CoolingCOP', null=True, size=None)),
                ('simulation_years', models.IntegerField(blank=True, default=25, help_text='The time span for which GHX is sized to meet the entering fluid temperature constraints [year]', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('solver_eft_tolerance_f', models.FloatField(blank=True, default=2.0, help_text='Tolerance for GHX sizing based on the entering fluid temperature limits [degF]', validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(5.0)])),
                ('ghx_model', models.TextField(blank=True, choices=[('TESS', 'TESS'), ('DST', 'DST')], default='TESS', help_text='GHX model to use in the simulation: TESS or DST')),
                ('dst_ghx_timesteps_per_hour', models.IntegerField(blank=True, default=12, help_text='Time steps per hour to use for the DST GHX model', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('tess_ghx_minimum_timesteps_per_hour', models.IntegerField(blank=True, default=1, help_text='Minimum time steps per hour to use for the TESS GHX model; the model will decide if more is needed each hour', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('max_sizing_iterations', models.IntegerField(blank=True, default=15, help_text='Maximum number of sizing iterations before the GHPGHX model times out', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('init_sizing_factor_ft_per_peak_ton', models.FloatField(blank=True, default=246.1, help_text='Initial guess of total feet of GHX boreholes (total feet = N bores * Length bore) based on peak ton heating/cooling [ft/ton]', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5000.0)])),
            ],
        ),
        migrations.CreateModel(
            name='GHPGHXOutputs',
            fields=[
                ('ghp_uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_boreholes', models.FloatField(blank=True, help_text='Minimum required number of boreholes to meet heat pump EWT constraints', null=True)),
                ('length_boreholes_ft', models.FloatField(blank=True, help_text='Length of each borehole, drilled vertically in the ground [ft]', null=True)),
                ('yearly_heating_heatpump_electric_consumption_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly heating heat pump electric consumption, average across simulation years [kW]', null=True, size=None)),
                ('yearly_cooling_heatpump_electric_consumption_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly cooling heat pump electric consumption, average across simulation years [kW]', null=True, size=None)),
                ('yearly_ghx_pump_electric_consumption_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly GHX pump electric consumption, average across simulation years [kW]', null=True, size=None)),
                ('yearly_total_electric_consumption_series_kw', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly total GHP electric consumption, average across simulation years [kW]', null=True, size=None)),
                ('yearly_total_electric_consumption_kwh', models.FloatField(blank=True, help_text='Total yearly electric consumption by GHPGHX system [kWh]', null=True)),
                ('peak_heating_heatpump_thermal_ton', models.FloatField(blank=True, help_text='Peak heating heat pump thermal load served [ton]', null=True)),
                ('peak_cooling_heatpump_thermal_ton', models.FloatField(blank=True, help_text='Peak cooling heat pump thermal load served [ton]', null=True)),
                ('peak_combined_heatpump_thermal_ton', models.FloatField(blank=True, help_text='Peak combined heating/cooling heat pump thermal load served [ton]', null=True)),
                ('max_eft_f', models.FloatField(blank=True, help_text='Maximum entering fluid temperature (to heat pump, from ghx) throughout the GHPGHX simulation period', null=True)),
                ('min_eft_f', models.FloatField(blank=True, help_text='Minimum entering fluid temperature (to heat pump, from ghx) throughout the GHPGHX simulation period', null=True)),
                ('heating_cop_avg', models.FloatField(blank=True, help_text='Average heating heatpump system coefficient of performance (COP) (includes ghx pump allocation)', null=True)),
                ('cooling_cop_avg', models.FloatField(blank=True, help_text='Average cooling heatpump system coefficient of performance (COP) (includes ghx pump allocation)', null=True)),
                ('solved_eft_error_f', models.FloatField(blank=True, help_text='Error between the solved GHPGHX system EFT and the max or min limit for EFT', null=True)),
            ],
        ),
    ]
