# Generated by Django 3.1.8 on 2021-05-19 16:17

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpghxmodel',
            name='ewt_error',
            field=models.FloatField(blank=True, help_text='Error of entering water temperature of solved GHPGHX system', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='existing_boiler_efficiency',
            field=models.FloatField(blank=True, default=0.8, help_text='Efficiency of the existing boiler/heater serving the heating load', null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='heating_fuel_load_mmbtu_per_hr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly heating fuel load that GHP serves [MMBtu/hr]', null=True, size=None),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the site', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the site', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
