# Generated by Django 3.1.13 on 2021-12-06 22:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='yearly_heat_pump_eft_series_f',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly heat pump entering fluid temperature (eft), average across simulation years [kW]', null=True, size=None),
        ),
    ]
