# Generated by Django 3.1.8 on 2021-05-24 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0002_auto_20210519_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxmodel',
            name='init_sizing_factor_ft_per_peak_ton',
            field=models.FloatField(blank=True, default=246.1, help_text='Initial guess of total feet of GHX boreholes (total feet = N bores * Length bore) based on peak ton heating/cooling [ft/ton]', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5000.0)]),
        ),
    ]
