# Generated by Django 3.1.13 on 2021-12-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0002_ghpghxoutputs_yearly_heat_pump_eft_series_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='ghx_model',
            field=models.TextField(blank=True, choices=[('TESS', 'TESS')], default='TESS', help_text="GHX model to use in the simulation: 'TESS' is the only option currently"),
        ),
    ]
