# Generated by Django 3.1.8 on 2021-05-24 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0003_auto_20210524_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxmodel',
            name='borehole_depth_ft',
            field=models.FloatField(blank=True, default=400.0, help_text='Vertical depth of each borehole [ft]', null=True, validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(600.0)]),
        ),
    ]
