# Generated by Django 4.0.7 on 2023-03-07 01:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0003_auto_20211222_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='end_of_year_eft_f',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='End of year entering fluid temperature for all years in the last iteration of GHX sizing [degF]', null=True, size=None),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='peak_auxiliary_boiler_mmbtu_per_hour',
            field=models.FloatField(blank=True, help_text='Peak auxiliary boiler consumption for boiler sizing [MMBtu/hr]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='peak_auxiliary_cooling_tower_ton',
            field=models.FloatField(blank=True, help_text='Peak auxiliary cooling tower consumption for cooling tower sizing [ton]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='yearly_auxiliary_boiler_consumption_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly auxiliary boiler consumption, average across simulation years [MMBtu/hr]', null=True, size=None),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='yearly_auxiliary_cooling_tower_consumption_series_ton',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly auxiliary cooling tower consumption, average across simulation years [ton]', null=True, size=None),
        ),
    ]
