# Generated by Django 4.0.7 on 2023-03-10 02:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0004_ghpghxoutputs_end_of_year_eft_f_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghpghxoutputs',
            name='peak_auxiliary_boiler_mmbtu_per_hour',
        ),
        migrations.RemoveField(
            model_name='ghpghxoutputs',
            name='peak_auxiliary_cooling_tower_ton',
        ),
        migrations.RemoveField(
            model_name='ghpghxoutputs',
            name='yearly_auxiliary_boiler_consumption_series_mmbtu_per_hour',
        ),
        migrations.RemoveField(
            model_name='ghpghxoutputs',
            name='yearly_auxiliary_cooling_tower_consumption_series_ton',
        ),
        migrations.AddField(
            model_name='ghpghxinputs',
            name='is_hybrid_ghx',
            field=models.BooleanField(blank=True, default=True, help_text='If the GHP system uses a hybrid GHX with auxiliary heater or cooler', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='annual_aux_cooler_electric_consumption_kwh',
            field=models.FloatField(blank=True, help_text='Annual auxiliary cooler electrical consumption [kWh]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='annual_aux_heater_electric_consumption_kwh',
            field=models.FloatField(blank=True, help_text='Annual auxiliary heater electrical consumption [kWh]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='peak_aux_cooler_thermal_production_ton',
            field=models.FloatField(blank=True, help_text='Peak auxiliary cooler thermal production for cooler sizing [ton]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='peak_aux_heater_thermal_production_mmbtu_per_hour',
            field=models.FloatField(blank=True, help_text='Peak auxiliary heater thermal production for heater sizing [MMBtu/hr]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='yearly_aux_cooler_electric_consumption_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly auxiliary cooler electrical consumption, average across simulation years [kW]', null=True, size=None),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='yearly_aux_cooler_thermal_production_series_kwt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly auxiliary cooler thermal production, average across simulation years [kW-thermal]', null=True, size=None),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='yearly_aux_heater_electric_consumption_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly auxiliary heater electrical consumption, average across simulation years [kW]', null=True, size=None),
        ),
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='yearly_aux_heater_thermal_production_series_mmbtu_per_hour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly auxiliary heater thermal production, average across simulation years [MMBtu/hr]', null=True, size=None),
        ),
    ]
