# Generated by Django 3.1.8 on 2021-05-24 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0004_auto_20210524_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghpghxmodel',
            name='ewt_error',
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='cooling_cop_avg',
            field=models.FloatField(blank=True, help_text='Average cooling heatpump system coefficient of performance (COP) (includes ghx pump allocation)', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='heating_cop_avg',
            field=models.FloatField(blank=True, help_text='Average heating heatpump system coefficient of performance (COP) (includes ghx pump allocation)', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='max_eft_f',
            field=models.FloatField(blank=True, help_text='Maximum entering fluid temperature (to heat pump, from ghx) throughout the GHPGHX simulation period', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='min_eft_f',
            field=models.FloatField(blank=True, help_text='Minimum entering fluid temperature (to heat pump, from ghx) throughout the GHPGHX simulation period', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='peak_combined_heatpump_thermal_ton',
            field=models.FloatField(blank=True, help_text='Peak combined heating/cooling heat pump thermal load served [ton]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='peak_cooling_heatpump_thermal_ton',
            field=models.FloatField(blank=True, help_text='Peak cooling heat pump thermal load served [ton]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='peak_heating_heatpump_thermal_ton',
            field=models.FloatField(blank=True, help_text='Peak heating heat pump thermal load served [ton]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='solved_eft_error_f',
            field=models.FloatField(blank=True, help_text='Error between the solved GHPGHX system EFT and the max or min limit for EFT', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='yearly_total_electric_consumption_kwh',
            field=models.FloatField(blank=True, help_text='Total yearly electric consumption by GHPGHX system [kWh]', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='yearly_total_electric_consumption_series_kw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Hourly total GHP electric consumption, average across simulation years [kW]', null=True, size=None),
        ),
    ]
