# Generated by Django 4.0.7 on 2023-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0005_remove_ghpghxoutputs_peak_auxiliary_boiler_mmbtu_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='is_hybrid_ghx',
            field=models.BooleanField(blank=True, help_text='If the GHP system uses a hybrid GHX with auxiliary heater or cooler', null=True),
        ),
    ]
