# Generated by Django 3.1.8 on 2021-05-25 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0005_auto_20210524_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghpghxmodel',
            name='solver_ewt_tolerance',
        ),
        migrations.AddField(
            model_name='ghpghxmodel',
            name='solver_eft_tolerance_f',
            field=models.FloatField(blank=True, default=0.1, help_text='Tolerance for GHX sizing based on the entering fluid temperature limits [degF]', null=True, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='ghpghxmodel',
            name='simulation_years',
            field=models.IntegerField(blank=True, default=25, help_text='The time span for which GHX is sized to meet the entering fluid temperature constraints [year]', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
