# Generated by Django 3.1.8 on 2021-05-25 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0007_auto_20210525_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxmodel',
            name='borehole_diameter_inch',
            field=models.FloatField(blank=True, default=10.0, help_text='Diameter of the borehole/well drilled in the ground [in]', null=True, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24.0)]),
        ),
    ]
