# Generated by Django 4.0.7 on 2023-03-12 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0007_ghpghxoutputs_aux_heat_exchange_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpghxinputs',
            name='aux_cooler_energy_use_intensity_kwe_per_kwt',
            field=models.FloatField(blank=True, default=0.2, help_text='The energy use intensity of the auxiliary cooler [kWe/kWt]', null=True, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='ghpghxinputs',
            name='aux_heater_thermal_efficiency',
            field=models.FloatField(blank=True, default=0.98, help_text='The thermal efficiency (thermal_out/fuel_in) of the auxiliary heater', null=True, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
