# Generated by Django 3.1.8 on 2021-05-25 20:23

import django.contrib.postgres.fields
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0008_auto_20210525_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxmodel',
            name='cop_map_eft_heating_cooling',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), default=[{'cool_cop': 7.7, 'eft': 20, 'heat_cop': 3.33}, {'cool_cop': 7.7, 'eft': 30, 'heat_cop': 3.66}, {'cool_cop': 7.7, 'eft': 40, 'heat_cop': 4.05}, {'cool_cop': 7.63, 'eft': 50, 'heat_cop': 4.42}, {'cool_cop': 7.13, 'eft': 60, 'heat_cop': 4.76}, {'cool_cop': 6.19, 'eft': 70, 'heat_cop': 5.04}, {'cool_cop': 5.29, 'eft': 80, 'heat_cop': 5.24}, {'cool_cop': 4.55, 'eft': 90, 'heat_cop': 5.27}, {'cool_cop': 3.75, 'eft': 100, 'heat_cop': 5.27}, {'cool_cop': 3.13, 'eft': 110, 'heat_cop': 5.27}, {'cool_cop': 2.62, 'eft': 120, 'heat_cop': 5.27}], help_text='Heat pump coefficient of performance (COP) map: list of dictionaries, each with 3 keys: 1) EFT, 2) HeatingCOP, 3) CoolingCOP', null=True, size=None),
        ),
    ]
