# Generated by Django 4.0.7 on 2023-03-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0008_ghpghxinputs_aux_cooler_energy_use_intensity_kwe_per_kwt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpghxinputs',
            name='hybrid_sizing_flag',
            field=models.FloatField(blank=True, default=1.0, help_text='Possible values: -2 (size for heating), -1.0 (size for cooling), 1.0 (non-hybrid), value between 0-1 (fraction of full GHE size)', null=True),
        ),
        migrations.AddField(
            model_name='ghpghxinputs',
            name='is_heating_electric',
            field=models.BooleanField(blank=True, default=True, help_text='Set to True if heating is electric, false otherwise', null=True),
        ),
    ]
