# Generated by Django 3.1.8 on 2021-05-25 20:39

import django.contrib.postgres.fields
from django.db import migrations
import ghpghx.models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0009_auto_20210525_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxmodel',
            name='cop_map_eft_heating_cooling',
            field=django.contrib.postgres.fields.ArrayField(base_field=picklefield.fields.PickledObjectField(editable=False, null=True), default=ghpghx.models.GHPGHXModel._get_cop_map, help_text='Heat pump coefficient of performance (COP) map: list of dictionaries, each with 3 keys: 1) EFT, 2) HeatingCOP, 3) CoolingCOP', null=True, size=None),
        ),
    ]
