# Generated by Django 4.0.7 on 2023-03-22 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0010_remove_ghpghxoutputs_end_of_year_eft_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpghxinputs',
            name='hybrid_ghx_sizing_fraction',
            field=models.FloatField(blank=True, default=0.6, help_text='Applies fraction to full GHX size for hybrid sizing (value between 0.1 - 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='ghpghxinputs',
            name='hybrid_ghx_sizing_method',
            field=models.TextField(blank=True, default='None', help_text="Possible values: 'Fractional' (user inputs fraction of full GHX size), 'Automatic' (REopt determines based on the smaller heating or cooling load), 'None' (non-hybrid)", null=True),
        ),
    ]
