# Generated by Django 3.1.12 on 2021-09-08 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0011_auto_20210621_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxmodel',
            name='ghx_fluid_dynamic_viscosity_lbm_per_ft_hr',
            field=models.FloatField(blank=True, default=2.75, help_text='Dynamic viscosity of the fluid in the GHX (nominally water) [lb/(ft-hr)]', null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='ghpghxmodel',
            name='ghx_fluid_thermal_conductivity_btu_per_hr_ft_f',
            field=models.FloatField(blank=True, default=0.34, help_text='Thermal conductivity of the fluid in the GHX (nominally water) [Btu/(hr-ft-degF)]', null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
