# Generated by Django 4.0.7 on 2023-03-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0011_ghpghxinputs_hybrid_ghx_sizing_fraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghpghxinputs',
            name='is_hybrid_ghx',
        ),
    ]
