# Generated by Django 4.0.7 on 2023-03-28 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0012_remove_ghpghxinputs_is_hybrid_ghx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='init_sizing_factor_ft_per_peak_ton',
            field=models.FloatField(blank=True, default=75, help_text='Initial guess of total feet of GHX boreholes (total feet = N bores * Length bore) based on peak ton heating/cooling [ft/ton]', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5000.0)]),
        ),
    ]
