# Generated by Django 4.0.7 on 2023-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0014_ghpghxoutputs_hybrid_auto_ghx_sizing_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghpghxoutputs',
            name='hybrid_auto_ghx_sizing_flag',
        ),
        migrations.AddField(
            model_name='ghpghxinputs',
            name='hybrid_auto_ghx_sizing_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
