# Generated by Django 4.0.7 on 2023-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0015_remove_ghpghxoutputs_hybrid_auto_ghx_sizing_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpghxoutputs',
            name='heat_pump_configuration',
            field=models.TextField(blank=True, help_text='Specifies if the auxiliary heat exchange unit is a heater or cooler', null=True),
        ),
    ]
