# Generated by Django 4.0.7 on 2023-10-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0016_ghpghxoutputs_heat_pump_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghpghxinputs',
            name='heat_pump_configuration',
            field=models.TextField(blank=True, help_text='Specifies if the auxiliary heat exchange unit is a heater or cooler', null=True),
        ),
    ]
