# Generated by Django 4.0.7 on 2025-01-14 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghpghx', '0018_ghpghxinputs_wwhp_cooling_pump_fluid_flow_rate_gpm_per_ton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='borehole_depth_ft',
            field=models.FloatField(blank=True, default=443.0, help_text='Vertical depth of each borehole [ft]', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(600.0)]),
        ),
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='borehole_diameter_inch',
            field=models.FloatField(blank=True, default=6.0, help_text='Diameter of the borehole/well drilled in the ground [in]', validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24.0)]),
        ),
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='ghx_header_depth_ft',
            field=models.FloatField(blank=True, default=6.6, help_text='Depth under the ground of the GHX header pipe [ft]', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='ghx_pipe_thermal_conductivity_btu_per_hr_ft_f',
            field=models.FloatField(blank=True, default=0.23, help_text='Thermal conductivity of the GHX pipe [Btu/(hr-ft-degF)]', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='ghx_shank_space_inch',
            field=models.FloatField(blank=True, default=1.27, help_text='Distance between the centerline of the upwards and downwards u-tube legs [in]', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='ghpghxinputs',
            name='grout_thermal_conductivity_btu_per_hr_ft_f',
            field=models.FloatField(blank=True, default=0.75, help_text='Thermal conductivity of the grout material in a borehole [Btu/(hr-ft-degF)]', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
