name: CI

on:

  pull_request:
    branches: develop

jobs:

  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: decrypt
        env:
          TRANSCRYPT_PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}
        run: ./.github/scripts/decrypt.sh 
      - name: test
        run: ./.github/scripts/test.sh
