name: CI

on:

  pull_request:
    branches: develop

jobs:

  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: decrypt
        env:
          TRANSCRYPT_PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}
        run: ./.github/scripts/decrypt.sh 
      - name: build
        run: docker-compose --file docker-compose.xpress.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker logs celery
      - name: test
        run: docker-compose exec celery python manage.py test -v 2 --failfast --no-input
